//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndMovieRes.c"
#include "UIFlowWndMovie.h"
#include "PrjCfg.h"

//---------------------UIFlowWndMovieCtrl Debug Definition -----------------------------
#define _UIFLOWWNDMOVIE_ERROR_MSG        1
#define _UIFLOWWNDMOVIE_TRACE_MSG        0

#if (_UIFLOWWNDMOVIE_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndMovieErrMsg(...)            debug_msg ("^R UIFlowWndMovie: "__VA_ARGS__)
#else
#define UIFlowWndMovieErrMsg(...)
#endif

#if (_UIFLOWWNDMOVIE_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndMovieTraceMsg(...)          debug_msg ("^B UIFlowWndMovie: "__VA_ARGS__)
#else
#define UIFlowWndMovieTraceMsg(...)
#endif

//---------------------UIFlowWndMovieCtrl Global Variables -----------------------------

//---------------------UIFlowWndMovieCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndMovieCtrl Public API  ----------------------------------

//---------------------UIFlowWndMovieCtrl Private API  ---------------------------------
//---------------------UIFlowWndMovieCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie)
CTRL_LIST_ITEM(UIFlowWndMovie_RecPanel)
CTRL_LIST_ITEM(UIFlowWndMovie_Resolution)
CTRL_LIST_ITEM(UIFlowWndMovie_Status_battery)
CTRL_LIST_ITEM(UIFlowWndMovie_Status_Return)
CTRL_LIST_ITEM(UIFlowWndMovie_Radar_Mode)
CTRL_LIST_ITEM(UIFlowWndMovie_Radar_Vol)
CTRL_LIST_ITEM(UIFlowWndMovie_Radar_Vol_Lvl)
CTRL_LIST_ITEM(UIFlowWndMovie_Angle)
CTRL_LIST_ITEM(UIFlowWndMovie_Icon_GPS)
CTRL_LIST_ITEM(UIFlowWndMovie_Icon_Speed_limit_Panel)
CTRL_LIST_ITEM(UIFlowWndMovie_Distance)
CTRL_LIST_ITEM(UIFlowWndMovie_CurSpeed)
CTRL_LIST_ITEM(UIFlowWndMovie_Status_Storage)
CTRL_LIST_ITEM(UIFlowWndMovie_Icon_Radar_Waring)
CTRL_LIST_ITEM(UIFlowWndMovie_Icon_Radar_SingalLvl)
CTRL_LIST_ITEM(UIFlowWndMovie_Icon_RD_EYE)
CTRL_LIST_ITEM(UIFlowWndMovie_Icon_RD_ON)
CTRL_LIST_ITEM(UIFlowWndMovie_TXT_REC)
CTRL_LIST_ITEM(UIFlowWndMovie_GPSDB)
CTRL_LIST_ITEM(UIFlowWndMovie_Audio)
CTRL_LIST_ITEM(UIFlowWndMovie_Lock)
CTRL_LIST_ITEM(UIFlowWndMovie_HMS)
CTRL_LIST_ITEM(UIFlowWndMovie_Status_REC)
CTRL_LIST_END

//----------------------UIFlowWndMovieCtrl Event---------------------------
INT32 UIFlowWndMovie_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndMovie)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndMovie_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndMovie_OnClose)
EVENT_END

INT32 UIFlowWndMovie_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIFlowWndMovie_RecPanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_RecPanel)
CTRL_LIST_END

//----------------------UIFlowWndMovie_RecPanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_RecPanel)
EVENT_END

//----------------------UIFlowWndMovie_ResolutionCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Resolution)
EVENT_END

//----------------------UIFlowWndMovie_Status_batteryCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Status_battery)
EVENT_END

//----------------------UIFlowWndMovie_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Status_Return)
EVENT_END

//----------------------UIFlowWndMovie_Radar_ModeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Radar_Mode)
EVENT_END

//----------------------UIFlowWndMovie_Radar_VolCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Radar_Vol)
EVENT_END

//----------------------UIFlowWndMovie_Radar_Vol_LvlCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Radar_Vol_Lvl)
EVENT_END

//----------------------UIFlowWndMovie_AngleCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Angle)
EVENT_END

//----------------------UIFlowWndMovie_Icon_GPSCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Icon_GPS)
EVENT_END

//---------------------UIFlowWndMovie_Icon_Speed_limit_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_Icon_Speed_limit_Panel)
CTRL_LIST_ITEM(UIFlowWndMovie_Panel_WarHighSpeed)
CTRL_LIST_ITEM(UIFlowWndMovie_Panel_WarLowSpeed)
CTRL_LIST_ITEM(UIFlowWndMovie_Panel_Warning)
CTRL_LIST_END

//----------------------UIFlowWndMovie_Icon_Speed_limit_PanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Icon_Speed_limit_Panel)
EVENT_END

//---------------------UIFlowWndMovie_Panel_WarHighSpeedCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_Panel_WarHighSpeed)
CTRL_LIST_ITEM(UIFlowWndMovie_Speed_H)
CTRL_LIST_ITEM(UIFlowWndMovie_Speed_M)
CTRL_LIST_ITEM(UIFlowWndMovie_Speed_L)
CTRL_LIST_END

//----------------------UIFlowWndMovie_Panel_WarHighSpeedCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Panel_WarHighSpeed)
EVENT_END

//----------------------UIFlowWndMovie_Speed_HCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Speed_H)
EVENT_END

//----------------------UIFlowWndMovie_Speed_MCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Speed_M)
EVENT_END

//----------------------UIFlowWndMovie_Speed_LCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Speed_L)
EVENT_END

//---------------------UIFlowWndMovie_Panel_WarLowSpeedCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_Panel_WarLowSpeed)
CTRL_LIST_ITEM(UIFlowWndMovie_Speed_LowModeH)
CTRL_LIST_ITEM(UIFlowWndMovie_Speed_LowModeL)
CTRL_LIST_END

//----------------------UIFlowWndMovie_Panel_WarLowSpeedCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Panel_WarLowSpeed)
EVENT_END

//----------------------UIFlowWndMovie_Speed_LowModeHCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Speed_LowModeH)
EVENT_END

//----------------------UIFlowWndMovie_Speed_LowModeLCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Speed_LowModeL)
EVENT_END

//---------------------UIFlowWndMovie_Panel_WarningCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_Panel_Warning)
CTRL_LIST_ITEM(UIFlowWndMovie_Panel_Warning_Type)
CTRL_LIST_END

//----------------------UIFlowWndMovie_Panel_WarningCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Panel_Warning)
EVENT_END

//----------------------UIFlowWndMovie_Panel_Warning_TypeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Panel_Warning_Type)
EVENT_END

//---------------------UIFlowWndMovie_DistanceCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_Distance)
CTRL_LIST_ITEM(UIFlowWndMovie_Distance_H)
CTRL_LIST_ITEM(UIFlowWndMovie_Distance_M)
CTRL_LIST_ITEM(UIFlowWndMovie_Distance_L)
CTRL_LIST_ITEM(UIFlowWndMovie_Distance_Uint)
CTRL_LIST_END

//----------------------UIFlowWndMovie_DistanceCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Distance)
EVENT_END

//----------------------UIFlowWndMovie_Distance_HCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Distance_H)
EVENT_END

//----------------------UIFlowWndMovie_Distance_MCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Distance_M)
EVENT_END

//----------------------UIFlowWndMovie_Distance_LCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Distance_L)
EVENT_END

//----------------------UIFlowWndMovie_Distance_UintCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Distance_Uint)
EVENT_END

//---------------------UIFlowWndMovie_CurSpeedCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_CurSpeed)
CTRL_LIST_ITEM(UIFlowWndMovie_CurSpeed_H)
CTRL_LIST_ITEM(UIFlowWndMovie_CurSpeed_M)
CTRL_LIST_ITEM(UIFlowWndMovie_CurSpeed_L)
CTRL_LIST_ITEM(UIFlowWndMovie_CurSpeed_Uint)
CTRL_LIST_END

//----------------------UIFlowWndMovie_CurSpeedCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_CurSpeed)
EVENT_END

//----------------------UIFlowWndMovie_CurSpeed_HCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_CurSpeed_H)
EVENT_END

//----------------------UIFlowWndMovie_CurSpeed_MCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_CurSpeed_M)
EVENT_END

//----------------------UIFlowWndMovie_CurSpeed_LCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_CurSpeed_L)
EVENT_END

//----------------------UIFlowWndMovie_CurSpeed_UintCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_CurSpeed_Uint)
EVENT_END

//----------------------UIFlowWndMovie_Status_StorageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Status_Storage)
EVENT_END

//---------------------UIFlowWndMovie_Icon_Radar_WaringCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_Icon_Radar_Waring)
CTRL_LIST_ITEM(UIFlowWndMovie_Icon_Radar_Waring_Panel_Warning)
CTRL_LIST_END

//----------------------UIFlowWndMovie_Icon_Radar_WaringCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Icon_Radar_Waring)
EVENT_END

//---------------------UIFlowWndMovie_Icon_Radar_Waring_Panel_WarningCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_Icon_Radar_Waring_Panel_Warning)
CTRL_LIST_ITEM(UIFlowWndMovie_Icon_Radar_Waring_Panel_Warning_Type)
CTRL_LIST_END

//----------------------UIFlowWndMovie_Icon_Radar_Waring_Panel_WarningCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Icon_Radar_Waring_Panel_Warning)
EVENT_END

//----------------------UIFlowWndMovie_Icon_Radar_Waring_Panel_Warning_TypeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Icon_Radar_Waring_Panel_Warning_Type)
EVENT_END

//---------------------UIFlowWndMovie_Icon_Radar_SingalLvlCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_Icon_Radar_SingalLvl)
CTRL_LIST_ITEM(UIFlowWndMovie_Icon_Radar_SingalLvl_Icon)
CTRL_LIST_ITEM(UIFlowWndMovie_Icon_Radar_SingalLvl_Panel0)
CTRL_LIST_END

//----------------------UIFlowWndMovie_Icon_Radar_SingalLvlCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Icon_Radar_SingalLvl)
EVENT_END

//----------------------UIFlowWndMovie_Icon_Radar_SingalLvl_IconCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Icon_Radar_SingalLvl_Icon)
EVENT_END

//---------------------UIFlowWndMovie_Icon_Radar_SingalLvl_Panel0Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_Icon_Radar_SingalLvl_Panel0)
CTRL_LIST_ITEM(Static93)
CTRL_LIST_ITEM(Static94)
CTRL_LIST_ITEM(Static95)
CTRL_LIST_ITEM(Static95C)
CTRL_LIST_END

//----------------------UIFlowWndMovie_Icon_Radar_SingalLvl_Panel0Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Icon_Radar_SingalLvl_Panel0)
EVENT_END

//----------------------Static93Ctrl Event---------------------------
EVENT_BEGIN(Static93)
EVENT_END

//----------------------Static94Ctrl Event---------------------------
EVENT_BEGIN(Static94)
EVENT_END

//----------------------Static95Ctrl Event---------------------------
EVENT_BEGIN(Static95)
EVENT_END

//----------------------Static95CCtrl Event---------------------------
EVENT_BEGIN(Static95C)
EVENT_END

//----------------------UIFlowWndMovie_Icon_RD_EYECtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Icon_RD_EYE)
EVENT_END

//----------------------UIFlowWndMovie_Icon_RD_ONCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Icon_RD_ON)
EVENT_END

//----------------------UIFlowWndMovie_TXT_RECCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_TXT_REC)
EVENT_END

//----------------------UIFlowWndMovie_GPSDBCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_GPSDB)
EVENT_END

//----------------------UIFlowWndMovie_AudioCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Audio)
EVENT_END

//----------------------UIFlowWndMovie_LockCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Lock)
EVENT_END

//---------------------UIFlowWndMovie_HMSCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_HMS)
CTRL_LIST_ITEM(UIFlowWndMovie_HMS_Hour_H)
CTRL_LIST_ITEM(UIFlowWndMovie_HMS_Hour_L)
CTRL_LIST_ITEM(UIFlowWndMovie_HMS_Dot1)
CTRL_LIST_ITEM(UIFlowWndMovie_HMS_Min_H)
CTRL_LIST_ITEM(UIFlowWndMovie_HMS_Min_L)
CTRL_LIST_ITEM(UIFlowWndMovie_HMS_Dot2)
CTRL_LIST_ITEM(UIFlowWndMovie_HMS_Sec_H)
CTRL_LIST_ITEM(UIFlowWndMovie_HMS_Sec_L)
CTRL_LIST_END

//----------------------UIFlowWndMovie_HMSCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_HMS)
EVENT_END

//----------------------UIFlowWndMovie_HMS_Hour_HCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_HMS_Hour_H)
EVENT_END

//----------------------UIFlowWndMovie_HMS_Hour_LCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_HMS_Hour_L)
EVENT_END

//----------------------UIFlowWndMovie_HMS_Dot1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_HMS_Dot1)
EVENT_END

//----------------------UIFlowWndMovie_HMS_Min_HCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_HMS_Min_H)
EVENT_END

//----------------------UIFlowWndMovie_HMS_Min_LCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_HMS_Min_L)
EVENT_END

//----------------------UIFlowWndMovie_HMS_Dot2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_HMS_Dot2)
EVENT_END

//----------------------UIFlowWndMovie_HMS_Sec_HCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_HMS_Sec_H)
EVENT_END

//----------------------UIFlowWndMovie_HMS_Sec_LCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_HMS_Sec_L)
EVENT_END

//----------------------UIFlowWndMovie_Status_RECCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Status_REC)
EVENT_END

