//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAY_H
#define UIFLOWWNDPLAY_H

#include "UIFramework.h"

extern VControl UIFlowWndPlayCtrl;//Panel type 

extern VControl UIFlowWndPlay_StaticICN_ProtectCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_FilenameCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_SpeedCtrl;//Static type 

extern VControl UIFlowWndPlay_Status_PRE_ONECtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_PRE_ONE_ICONID_NULL,
UIFlowWndPlay_Status_PRE_ONE_MAX
}UIFlowWndPlay_Status_PRE_ONE_Setting;

extern VControl UIFlowWndPlay_Status_ReturnCtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_Return_STRID_NULL_,
UIFlowWndPlay_Status_Return_MAX
}UIFlowWndPlay_Status_Return_Setting;
#endif
