//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDEDOG_H
#define UIFLOWWNDEDOG_H

#include "UIFramework.h"

extern VControl UIFlowwndEdogCtrl;//Panel type 

extern VControl UIFlowwndEdogMenuItemCtrl;//Status type 

typedef enum
{
UIFlowwndEdogMenuItem_ICON_EDOG_MENU_VOLUME,
UIFlowwndEdogMenuItem_ICON_EDOG_MENU_RADAR_MUTE,
UIFlowwndEdogMenuItem_ICON_EDOG_MENU_MODE,
UIFlowwndEdogMenuItem_ICON_EDOG_MENU_SENSITIVITY,
UIFlowwndEdogMenuItem_ICON_EDOG_MENU_OVERSPEED,
UIFlowwndEdogMenuItem_ICON_EDOG_MENU_SPEEDOFFSET,
UIFlowwndEdogMenuItem_ICON_EDOG_MENU_BROADCAST,
UIFlowwndEdogMenuItem_ICON_EDOG_MENU_DEFAULT,
UIFlowwndEdogMenuItem_MAX
}UIFlowwndEdogMenuItem_Setting;

//---------------------UIFlowwndEdogCtrl User Export---------------------------
#endif
