//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONOPTION_H
#define MENUCOMMONOPTION_H

#include "UIFramework.h"

extern VControl MenuCommonOptionCtrl;//Panel type 

extern VControl UIMenuCommonOptionTitleCtrl;//Static type 

extern VControl MenuCommonOptionPanelCtrl;//Panel type 

extern VControl MenuCommonOptionReturnCtrl;//List type 

typedef enum
{
MenuCommonOptionReturn_STRID_RETURN_FORWARD,
MenuCommonOptionReturn_MAX
}MenuCommonOptionReturn_Setting;

extern VControl MenuCommonOption_InfoCtrl;//Static type 

extern VControl MenuCommonOption_RightCtrl;//Static type 

extern VControl MenuCommonOption_LeftCtrl;//Static type 

#endif
