//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndCalLCDRes.c"
#include "UIFlowWndCalLCD.h"


//#define factor_x  1.17375//  1.162500//(((float)(978 - 48)/(800.0)))
//#define factor_y  1.78125 // 1.766666//(((float)(950 - 102)/480.0))
//#define factor_x  ((TP_HW_MAX_X - TP_HW_MIN_X)/TP_PANEL_W)
//#define factor_y  ((TP_HW_MAX_Y - TP_HW_MIN_Y)/TP_PANEL_H)
static float factor_x;  
static float factor_y;  
typedef struct{
    UINT32  Point1_x;
    UINT32  Point1_y;
    UINT32  Point2_x;
    UINT32  Point2_y;
    UINT32  Point3_x;
    UINT32  Point3_y;
    UINT32  Point_LeftTop_x;
    UINT32  Point_LeftTop_y;
    UINT32  Point_RightBottom_x;
    UINT32  Point_RightBottom_y;
}CAL_LCD_POINT;
CAL_LCD_POINT All_Point;

//---------------------UIFlowWndCalLCDCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD)
CTRL_LIST_ITEM(UIFlowWndCalLCD_LeftTop)
CTRL_LIST_ITEM(UIFlowWndCalLCD_Tip)
CTRL_LIST_ITEM(UIFlowWndCalLCD_RightTop)
CTRL_LIST_ITEM(UIFlowWndCalLCD_LeftBottom)
CTRL_LIST_ITEM(UIFlowWndCalLCD_LeftTopPoint)
CTRL_LIST_ITEM(UIFlowWndCalLCD_RightBottomPoint)
CTRL_LIST_END

//----------------------UIFlowWndCalLCDCtrl Event---------------------------
INT32 UIFlowWndCalLCD_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndCalLCD_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndCalLCD_TP(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndCalLCD)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndCalLCD_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndCalLCD_OnClose)
EVENT_ITEM(NVTEVT_KEY_TP,UIFlowWndCalLCD_TP)
EVENT_END




static int Cal_Step = 0;


static INT32 TP_CAL_MAX_X = 973;//960;
static INT32 TP_CAL_MAX_Y    =    947;//928;
static INT32 TP_CAL_MIN_X     =   34;//76;
static INT32 TP_CAL_MIN_Y    =    92;//92;

enum
{
    CAL_LEFT_TOP = 0,
    CAL_RIGHT_TOP = 1,
    CAL_LEFT_BOTTOM = 2,
    CAL_WINDOW_LEFT_TOP = 3,
    CAL_WINDOW_RIGHT_BOTTOM = 4,
    CAL_LCD_OK = 5,
    CAL_LCD_FAIL = 6,
    CAL_MAX
};
void ShowCalIcon(int Step)
{
    UxCtrl_SetShow(&UIFlowWndCalLCD_LeftTopCtrl, FALSE);
    UxCtrl_SetShow(&UIFlowWndCalLCD_RightTopCtrl, FALSE);
    UxCtrl_SetShow(&UIFlowWndCalLCD_LeftBottomCtrl, FALSE);
    UxCtrl_SetShow(&UIFlowWndCalLCD_TipCtrl, FALSE);
    UxCtrl_SetShow(&UIFlowWndCalLCD_LeftTopPointCtrl, FALSE);
    UxCtrl_SetShow(&UIFlowWndCalLCD_RightBottomPointCtrl, FALSE);
    switch(Step)
    {
    case CAL_LEFT_TOP:
        UxCtrl_SetShow(&UIFlowWndCalLCD_LeftTopCtrl, TRUE);
        UxStatic_SetData(&UIFlowWndCalLCD_TipCtrl,STATIC_VALUE,STRID_CALLCD_TOUCH_CENTER);
        break;
    case CAL_RIGHT_TOP:
        UxCtrl_SetShow(&UIFlowWndCalLCD_RightTopCtrl, TRUE);
        UxStatic_SetData(&UIFlowWndCalLCD_TipCtrl,STATIC_VALUE,STRID_CALLCD_TOUCH_CENTER);
        break;
    case CAL_LEFT_BOTTOM:
        UxCtrl_SetShow(&UIFlowWndCalLCD_LeftBottomCtrl, TRUE);
        UxStatic_SetData(&UIFlowWndCalLCD_TipCtrl,STATIC_VALUE,STRID_CALLCD_TOUCH_CENTER);
        break;  
    case CAL_WINDOW_LEFT_TOP:
        UxCtrl_SetShow(&UIFlowWndCalLCD_LeftTopPointCtrl, TRUE);
        UxStatic_SetData(&UIFlowWndCalLCD_TipCtrl,STATIC_VALUE,STRID_CALLCD_TOUCH_LEFTTOP);
        break;  
        case CAL_WINDOW_RIGHT_BOTTOM:
        UxCtrl_SetShow(&UIFlowWndCalLCD_RightBottomPointCtrl, TRUE);
        UxStatic_SetData(&UIFlowWndCalLCD_TipCtrl,STATIC_VALUE,STRID_CALLCD_TOUCH_RIGHTBOTTOM);
        break;  
    case CAL_LCD_OK:
        UxStatic_SetData(&UIFlowWndCalLCD_TipCtrl,STATIC_VALUE,STRID_CALLCD_OK);
        break;  
    case CAL_LCD_FAIL:
        UxStatic_SetData(&UIFlowWndCalLCD_TipCtrl,STATIC_VALUE,STRID_CALLCD_FAIL);
        break;  
    }
    UxCtrl_SetShow(&UIFlowWndCalLCD_TipCtrl, TRUE);    
}
INT32 UIFlowWndCalLCD_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Cal_Step = 0;
    GetTPWindow(&TP_CAL_MAX_X,&TP_CAL_MIN_X,&TP_CAL_MAX_Y,&TP_CAL_MIN_Y);
    factor_x = (((float)(TP_CAL_MAX_X - TP_CAL_MIN_X)/(800.0)));
        factor_y = (((float)(TP_CAL_MAX_Y - TP_CAL_MIN_Y)/(480.0))); 
        debug_msg("^G  factor point: (%f  ,  %f)\r\n",factor_x,factor_y);
    ShowCalIcon(Cal_Step);
    SetCALLCDMode(TRUE);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndCalLCD_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    SetCALLCDMode(FALSE);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}


#define Difference_Value  200

//  point (75,75);(725,75);(75,405)
INT32 UIFlowWndCalLCD_TP(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiEvent;
    UINT32 P1,P2;
    UINT32  uiSoundMask;
    UINT32 TP_X_Value,TP_Y_Value;
    static INT32 TP_MAX_X,TP_MIN_X,TP_MAX_Y,TP_MIN_Y;
    INT32 OLD_TP_MAX_X,OLD_TP_MIN_X,OLD_TP_MAX_Y,OLD_TP_MIN_Y;
    float unit_adc_x,unit_adc_y;
    if(paramNum>0)
        uiEvent = paramArray[0];	
	
	switch(uiEvent)
	{
		case GESTURE_DOWN2UP://GESTURE_RIGHT2LEFT:
		   
		break;			
		
		case GESTURE_UP2DOWN://GESTURE_LEFT2RIGHT:
		    		
		break;	
 
		case GESTURE_PRESSONLY:
			
                    
		   	
		break;

		case GESTURE_CKICK:
			P1= paramArray[1];
			P2=paramArray[2];  

                    switch(Cal_Step)
                    {
                    case CAL_LEFT_TOP:
                                All_Point.Point1_x = P1;
                                All_Point.Point1_y = P2;
                                debug_msg("^G  Step 1 point: (%d  ,  %d)\r\n",All_Point.Point1_x,All_Point.Point1_y);
				    Cal_Step  = CAL_RIGHT_TOP;
                                ShowCalIcon(Cal_Step);
                        break;
                    case CAL_RIGHT_TOP:
                                All_Point.Point2_x = P1;
                                All_Point.Point2_y = P2;
                                debug_msg("^G  Step 2 point: (%d  ,  %d)\r\n",All_Point.Point2_x,All_Point.Point2_y);
				    Cal_Step = CAL_LEFT_BOTTOM;
                                ShowCalIcon(Cal_Step);
                        break;
                    case CAL_LEFT_BOTTOM:
                        #if 1
                                All_Point.Point3_x = P1;
                                All_Point.Point3_y = P2;
                                GetTPWindow(&OLD_TP_MAX_X,&OLD_TP_MIN_X,&OLD_TP_MAX_Y,&OLD_TP_MIN_Y);
                                debug_msg("^G  Get TP window: (%d  ,  %d  ,%d  ,%d)\r\n",OLD_TP_MAX_X,OLD_TP_MIN_X,OLD_TP_MAX_Y,OLD_TP_MIN_Y);
                                /*
                                unit_adc_x = ((All_Point.Point2_x*factor_x)-(All_Point.Point1_x*factor_x))/((float)((725.0-75.0)/5));
                                unit_adc_y = ((All_Point.Point3_y*factor_y)-(All_Point.Point1_y*factor_y))/((float)((405.0-75.0)/5));
                                debug_msg("^G  unit_adc_x  ,y (%f  ,  %f )\r\n",unit_adc_x,unit_adc_y);
                                debug_msg("^G  unit_adc_x  ,y (%f  ,  %f )\r\n",unit_adc_x,unit_adc_y);
                                
                                TP_MAX_X = (All_Point.Point2_x*factor_x) + ((800.0 - 725.0)/5)*unit_adc_x;
                                TP_MIN_X = (All_Point.Point1_x*factor_x) - (75/5)*unit_adc_x;
                                TP_MAX_Y = (All_Point.Point3_y*factor_y) + ((480.0 - 405.0)/5)*unit_adc_y;
                                TP_MIN_Y = (All_Point.Point1_y*factor_y) - (75/5)*unit_adc_y;
                                */
                                
                                debug_msg("^G  (%f  ,  %f )\r\n",(All_Point.Point2_x*factor_x),(All_Point.Point1_x*factor_x));
                                debug_msg("^G  (%f  ,  %f )\r\n",(All_Point.Point3_y*factor_y),(All_Point.Point1_y*factor_y));
                                unit_adc_x = ((All_Point.Point2_x*factor_x)-(All_Point.Point1_x*factor_x))/650.0;
                                unit_adc_y = ((All_Point.Point3_y*factor_y)-(All_Point.Point1_y*factor_y))/330.0;
                                debug_msg("^G  unit_adc_x  ,y (%f  ,  %f )\r\n",unit_adc_x,unit_adc_y);
                                debug_msg("^G  unit_adc_x  ,y (%f  ,  %f )\r\n",unit_adc_x,unit_adc_y);
                                
                                TP_MAX_X = (((All_Point.Point2_x*factor_x) + ((800 - 725))*unit_adc_x) + ((All_Point.Point1_x*factor_x) + ((800 - 75))*unit_adc_x) + ((All_Point.Point3_x*factor_x) + ((800 - 75))*unit_adc_x))/3;
                                TP_MIN_X = (((All_Point.Point1_x*factor_x) - (75)*unit_adc_x) + ((All_Point.Point2_x*factor_x) - (725)*unit_adc_x) + ((All_Point.Point3_x*factor_x) - (75)*unit_adc_x))/3;
                                TP_MAX_Y = (((All_Point.Point3_y*factor_y) + ((480 - 405))*unit_adc_y) + ((All_Point.Point2_y*factor_y) + ((480 - 75))*unit_adc_y) + ((All_Point.Point1_y*factor_y) + ((480 - 75))*unit_adc_y))/3;
                                TP_MIN_Y = (((All_Point.Point1_y*factor_y) - (75)*unit_adc_y) + ((All_Point.Point2_y*factor_y) - (75)*unit_adc_y) + ((All_Point.Point3_y*factor_y) - (405)*unit_adc_y))/3;
                                #endif
                                debug_msg("^G  Set TP window: (%d  ,  %d  ,%d  ,%d)\r\n",TP_MAX_X,TP_MIN_X,TP_MAX_Y,TP_MIN_Y);
                                //SetTPWindow(TP_MAX_X,TP_MIN_X,TP_MAX_Y,TP_MIN_Y);
                                //SetSPITPData(TP_MAX_X,TP_MIN_X,TP_MAX_Y,TP_MIN_Y);
				    //Ux_CloseWindowClear(&UIFlowWndCalLCDCtrl, 0);
				    Cal_Step  = CAL_WINDOW_LEFT_TOP;
                                ShowCalIcon(Cal_Step);
                        break;
                    case CAL_WINDOW_LEFT_TOP:
                                GetCurTPXY(&TP_Y_Value,&TP_X_Value);
                                debug_msg("^G LeftTop Value (%d,%d)\r\n",TP_X_Value,TP_Y_Value);
                                All_Point.Point_LeftTop_x= TP_X_Value;//max X
                                All_Point.Point_LeftTop_y= TP_Y_Value;//min Y
                                
                                Cal_Step  = CAL_WINDOW_RIGHT_BOTTOM;
                                ShowCalIcon(Cal_Step);
                        break;
                    case CAL_WINDOW_RIGHT_BOTTOM:
                                GetCurTPXY(&TP_Y_Value,&TP_X_Value);
                                debug_msg("^G RightBottom Value (%d,%d)\r\n",TP_X_Value,TP_Y_Value);
                                All_Point.Point_RightBottom_x= TP_X_Value;//min X
                                All_Point.Point_RightBottom_y= TP_Y_Value;   //max Y 
                                debug_msg("^Y  differ (%d:%d:%d:%d)\r\n",abs(TP_MAX_X - All_Point.Point_LeftTop_x),abs(TP_MAX_Y - All_Point.Point_RightBottom_y) > Difference_Value,
                                    abs(TP_MIN_X - All_Point.Point_RightBottom_x),abs(TP_MIN_Y - All_Point.Point_LeftTop_y));
                                if(abs(TP_MAX_X - All_Point.Point_LeftTop_x) > Difference_Value ||abs(TP_MAX_Y - All_Point.Point_RightBottom_y) > Difference_Value||
                                    abs(TP_MIN_X - All_Point.Point_RightBottom_x) > Difference_Value||abs(TP_MIN_Y - All_Point.Point_LeftTop_y) > Difference_Value)
                                    {
                                    Cal_Step  = CAL_LCD_FAIL;
                                    }
                                else
                                    {
                                    TP_MAX_X = All_Point.Point_LeftTop_x;
                                    TP_MAX_Y = All_Point.Point_RightBottom_y;
                                    TP_MIN_X = All_Point.Point_RightBottom_x;
                                    TP_MIN_Y = All_Point.Point_LeftTop_y;
                                    if(abs(TP_MAX_X - TP_MIN_X) < 800 ||abs(TP_MAX_Y - TP_MIN_Y) < 480)
                                        {
                                        Cal_Step  = CAL_LCD_FAIL;
                                        }
                                    else
                                        {
                                        debug_msg("^Y  Set TP window: (%d  ,  %d  ,%d  ,%d)\r\n",TP_MAX_X,TP_MIN_X,TP_MAX_Y,TP_MIN_Y);
                                        SetTPWindow(TP_MAX_X,TP_MIN_X,TP_MAX_Y,TP_MIN_Y);
                                        SetSPITPData(TP_MAX_X,TP_MIN_X,TP_MAX_Y,TP_MIN_Y);
                                        Cal_Step  = CAL_LCD_OK;
                                        }
                                    }
                                ShowCalIcon(Cal_Step);
                        break;
                    case CAL_LCD_OK:
                                SetCALLCDMode(FALSE);
				    Ux_CloseWindowClear(&UIFlowWndCalLCDCtrl, 0);
                        break;
                    case CAL_LCD_FAIL:
                                Cal_Step  = CAL_LEFT_TOP;
                                ShowCalIcon(Cal_Step);
                        break;
                    }
   #if 0     
	            //debug_msg("^G movie GESTURE_CKICK\r\n");
		    if(TPIsOnRange(&UIFlowWndCalLCD_LeftTopCtrl,P1,P2)==TRUE)
		    	{
				if(Cal_Step == CAL_LEFT_TOP)	
				    {
				    //debug_msg("^G  change point: (%d  ,  %d)\r\n",P1,P2);
				    //GetCurTPXY(&All_Point.Point1_x,&All_Point.Point1_y);
				    //GetCurTPXY(&All_Point.Point1_x,&All_Point.Point1_y);
                                 All_Point.Point1_x = P1;
                                All_Point.Point1_y = P2;
                                debug_msg("^G  Step 1 point: (%d  ,  %d)\r\n",All_Point.Point1_x,All_Point.Point1_y);
				    Cal_Step  = CAL_RIGHT_TOP;
                                ShowCalIcon(Cal_Step);
                                
                                
				    }
		    	}	
                    else if(TPIsOnRange(&UIFlowWndCalLCD_RightTopCtrl,P1,P2)==TRUE)
		    	{
		    	      if(Cal_Step == CAL_RIGHT_TOP)	
				    {
				    //debug_msg("^G  change point: (%d  ,  %d)\r\n",P1,P2);
				    //GetCurTPXY(&All_Point.Point2_x,&All_Point.Point2_y);
				    //GetCurTPXY(&All_Point.Point2_x,&All_Point.Point2_y);
				    All_Point.Point2_x = P1;
                                All_Point.Point2_y = P2;
                                debug_msg("^G  Step 2 point: (%d  ,  %d)\r\n",All_Point.Point2_x,All_Point.Point2_y);
				    Cal_Step = CAL_LEFT_BOTTOM;
                                ShowCalIcon(Cal_Step);
                                
				    }
                                    
		    	}	
                    else if(TPIsOnRange(&UIFlowWndCalLCD_LeftBottomCtrl,P1,P2)==TRUE)
		    	{
		    	      if(Cal_Step == CAL_LEFT_BOTTOM)	
				    {
				    
                                #if 1
                                All_Point.Point3_x = P1;
                                All_Point.Point3_y = P2;
                                GetTPWindow(&OLD_TP_MAX_X,&OLD_TP_MIN_X,&OLD_TP_MAX_Y,&OLD_TP_MIN_Y);
                                debug_msg("^G  Get TP window: (%d  ,  %d  ,%d  ,%d)\r\n",OLD_TP_MAX_X,OLD_TP_MIN_X,OLD_TP_MAX_Y,OLD_TP_MIN_Y);
                                /*
                                unit_adc_x = ((All_Point.Point2_x*factor_x)-(All_Point.Point1_x*factor_x))/((float)((725.0-75.0)/5));
                                unit_adc_y = ((All_Point.Point3_y*factor_y)-(All_Point.Point1_y*factor_y))/((float)((405.0-75.0)/5));
                                debug_msg("^G  unit_adc_x  ,y (%f  ,  %f )\r\n",unit_adc_x,unit_adc_y);
                                debug_msg("^G  unit_adc_x  ,y (%f  ,  %f )\r\n",unit_adc_x,unit_adc_y);
                                
                                TP_MAX_X = (All_Point.Point2_x*factor_x) + ((800.0 - 725.0)/5)*unit_adc_x;
                                TP_MIN_X = (All_Point.Point1_x*factor_x) - (75/5)*unit_adc_x;
                                TP_MAX_Y = (All_Point.Point3_y*factor_y) + ((480.0 - 405.0)/5)*unit_adc_y;
                                TP_MIN_Y = (All_Point.Point1_y*factor_y) - (75/5)*unit_adc_y;
                                */
                                
                                debug_msg("^G  (%f  ,  %f )\r\n",(All_Point.Point2_x*factor_x),(All_Point.Point1_x*factor_x));
                                debug_msg("^G  (%f  ,  %f )\r\n",(All_Point.Point3_y*factor_y),(All_Point.Point1_y*factor_y));
                                unit_adc_x = ((All_Point.Point2_x*factor_x)-(All_Point.Point1_x*factor_x))/650.0;
                                unit_adc_y = ((All_Point.Point3_y*factor_y)-(All_Point.Point1_y*factor_y))/330.0;
                                debug_msg("^G  unit_adc_x  ,y (%f  ,  %f )\r\n",unit_adc_x,unit_adc_y);
                                debug_msg("^G  unit_adc_x  ,y (%f  ,  %f )\r\n",unit_adc_x,unit_adc_y);
                                
                                TP_MAX_X = (((All_Point.Point2_x*factor_x) + ((800 - 725))*unit_adc_x) + ((All_Point.Point1_x*factor_x) + ((800 - 75))*unit_adc_x) + ((All_Point.Point3_x*factor_x) + ((800 - 75))*unit_adc_x))/3;
                                TP_MIN_X = (((All_Point.Point1_x*factor_x) - (75)*unit_adc_x) + ((All_Point.Point2_x*factor_x) - (725)*unit_adc_x) + ((All_Point.Point3_x*factor_x) - (75)*unit_adc_x))/3;
                                TP_MAX_Y = (((All_Point.Point3_y*factor_y) + ((480 - 405))*unit_adc_y) + ((All_Point.Point2_y*factor_y) + ((480 - 75))*unit_adc_y) + ((All_Point.Point1_y*factor_y) + ((480 - 75))*unit_adc_y))/3;
                                TP_MIN_Y = (((All_Point.Point1_y*factor_y) - (75)*unit_adc_y) + ((All_Point.Point2_y*factor_y) - (75)*unit_adc_y) + ((All_Point.Point3_y*factor_y) - (405)*unit_adc_y))/3;
                                #endif
                                debug_msg("^G  Set TP window: (%d  ,  %d  ,%d  ,%d)\r\n",TP_MAX_X,TP_MIN_X,TP_MAX_Y,TP_MIN_Y);
                                SetTPWindow(TP_MAX_X,TP_MIN_X,TP_MAX_Y,TP_MIN_Y);
                                SetSPITPData(TP_MAX_X,TP_MIN_X,TP_MAX_Y,TP_MIN_Y);
				    Ux_CloseWindowClear(&UIFlowWndCalLCDCtrl, 0);
				    }
						
		    	}	
  
#endif		
		break;
	}	  
	

	  
	return NVTEVT_CONSUME;
}
//---------------------UIFlowWndCalLCD_LeftTopCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD_LeftTop)
CTRL_LIST_END

//----------------------UIFlowWndCalLCD_LeftTopCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_LeftTop)
EVENT_END

//----------------------UIFlowWndCalLCD_TipCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_Tip)
EVENT_END

//---------------------UIFlowWndCalLCD_RightTopCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD_RightTop)
CTRL_LIST_END

//----------------------UIFlowWndCalLCD_RightTopCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_RightTop)
EVENT_END

//---------------------UIFlowWndCalLCD_LeftBottomCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD_LeftBottom)
CTRL_LIST_END

//----------------------UIFlowWndCalLCD_LeftBottomCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_LeftBottom)
EVENT_END

//---------------------UIFlowWndCalLCD_LeftTopPointCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD_LeftTopPoint)
CTRL_LIST_END

//----------------------UIFlowWndCalLCD_LeftTopPointCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_LeftTopPoint)
EVENT_END

//---------------------UIFlowWndCalLCD_RightBottomPointCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD_RightBottomPoint)
CTRL_LIST_END

//----------------------UIFlowWndCalLCD_RightBottomPointCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_RightBottomPoint)
EVENT_END
