//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuSetupSettingRes.c"
#include "UIMenuSetupSetting.h"

#include "UIFlow.h"
#include "MenuId.h"

//---------------------UIMenuSetupSettingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuSetupSetting)
CTRL_LIST_ITEM(UIMenuSetupSetting_TXT_Title)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_Return)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_CALLCD)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_AutoPWROff)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_TVMode)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_Language)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_Version)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_HZ)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_AutoLCDOff)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_Format)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_Default)
CTRL_LIST_END

//----------------------UIMenuSetupSettingCtrl Event---------------------------
INT32 UIMenuSetupSetting_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuSetupSetting_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuSetupSetting_TP(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuSetupSetting)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuSetupSetting_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuSetupSetting_OnClose)
EVENT_ITEM(NVTEVT_KEY_TP,UIMenuSetupSetting_TP)

EVENT_END

INT32 UIMenuSetupSetting_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuSetupSetting_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

void  GotoSetupMenuItemOption(int pCtrl)
{
  TM_MENU*    pMenu = TM_GetMenu();
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;
    int ItemNum = 0;
    pMenu->Status = TMS_ON_ITEM;
    {
        pPage = &pMenu->pPages[pMenu->SelPage];
       
                pPage->SelItem = pCtrl;
               
        pItem = &pPage->pItems[pPage->SelItem];

        if (pItem->Count != 0 && pItem->SysFlag != 0)   // standard process
        {
            if (TM_MENU_CALLBACK(pMenu, TMM_ENTER_OPTION, MAKE_LONG(pItem->ItemId, 0)) == TMF_PASS_MESSAGE)
            {
                return NVTEVT_CONSUME;
            }
        }

       
        Ux_Redraw();

        if (pItem->Count != 0 && pItem->SysFlag != 0)   // standard process
        {
            pMenu->Status = TMS_ON_OPTION;
            Ux_OpenWindow(&MenuCommonOptionCtrl, 0);
        }
        else if (pItem->pOptions != 0)                  // custom process
        {
            pMenu->Status = TMS_ON_CUSTOM;
            TM_ITEM_CALLBACK(pItem, 0, 0);              // execute custom menu flow
        }
    }
}

INT32 UIMenuSetupSetting_TP(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
  UINT32 uiEvent;
    UINT32 P1,P2;
    UINT32  uiSoundMask;
  
    if(paramNum>0)
        uiEvent = paramArray[0];	
	
	switch(uiEvent)
	{
		case GESTURE_DOWN2UP://GESTURE_RIGHT2LEFT:
		   
		break;			
		
		case GESTURE_UP2DOWN://GESTURE_LEFT2RIGHT:
		    		
		break;	
 
		case GESTURE_PRESSONLY:
			P1= paramArray[1];
			P2=paramArray[2];  
		    if(TPIsOnRange(&UIMenuSetupSetting_Status_ReturnCtrl,P1,P2)==TRUE)
		    	{
		    	       
		       	//Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);	
		    	}		
                    
		   	
		break;

		case GESTURE_CKICK:
			P1= paramArray[1];
			P2=paramArray[2];  
        
	            //debug_msg("^G movie GESTURE_CKICK\r\n");
		    if(TPIsOnRange(&UIMenuSetupSetting_Status_ReturnCtrl,P1,P2)==TRUE)
		    	{
		    	     
		    	       {
			       	
                                 
							Ux_CloseWindow((VControl *)(&UIMenuSetupSettingCtrl), 0);
					
		    	       }
								   
		    	}	
            else if(TPIsOnRange(&UIMenuSetupSetting_Status_CALLCDCtrl,P1,P2)==TRUE)
		    	{
		    	      
                                    GotoSetupMenuItemOption(MENU_CALLCD);
		    	}	
            /*
            else if(TPIsOnRange(&UIMenuSetupSetting_Status_DateTimeCtrl,P1,P2)==TRUE)
		    	{
		    	      
                                    GotoSetupMenuItemOption(MENU_DATE_TIME);
		    	}	
		    	*/
            else if(TPIsOnRange(&UIMenuSetupSetting_Status_AutoPWROffCtrl,P1,P2)==TRUE)
		    	{
		    	      
						GotoSetupMenuItemOption(MENU_AUTO_POWER_OFF);	
		    	}	
            /*else if(TPIsOnRange(&UIMenuSetupSetting_Status_BeepCtrl,P1,P2)==TRUE)
		    	{
		    	      
						GotoSetupMenuItemOption(MENU_BEEP);	
		    	}*/	
            else if(TPIsOnRange(&UIMenuSetupSetting_Status_LanguageCtrl,P1,P2)==TRUE)
		    	{
		    	      
							GotoSetupMenuItemOption(MENU_LANGUAGE);	
		    	}	
            else if(TPIsOnRange(&UIMenuSetupSetting_Status_TVModeCtrl,P1,P2)==TRUE)
		    	{
		    	      GotoSetupMenuItemOption(MENU_TV_MODE);	
								   
		    	}	
            else if(TPIsOnRange(&UIMenuSetupSetting_Status_HZCtrl,P1,P2)==TRUE)
		    	{
		    	      GotoSetupMenuItemOption(MENU_FREQUENCY);	
								   
		    	}	
            else if(TPIsOnRange(&UIMenuSetupSetting_Status_AutoLCDOffCtrl,P1,P2)==TRUE)
		    	{
		    	      
						GotoSetupMenuItemOption(MENU_LCDOFF);		
		    	}	
            else if(TPIsOnRange(&UIMenuSetupSetting_Status_FormatCtrl,P1,P2)==TRUE)
		    	{
		    	     
								   GotoSetupMenuItemOption(MENU_FORMAT);
		    	}	
            else if(TPIsOnRange(&UIMenuSetupSetting_Status_DefaultCtrl,P1,P2)==TRUE)
		    	{
		    	      	GotoSetupMenuItemOption(MENU_DEFAULT);
								   
		    	}	
            else if(TPIsOnRange(&UIMenuSetupSetting_Status_VersionCtrl,P1,P2)==TRUE)
		    	{
		    	      
								   GotoSetupMenuItemOption(MENU_VERSION);
		    	}	
           else
			    {
			    
			    }
		   
				
		    
		
		break;
	}	  
	

	  
	return NVTEVT_CONSUME;
}

//----------------------UIMenuSetupSetting_TXT_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_TXT_Title)
EVENT_END

//----------------------UIMenuSetupSetting_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_Return)
EVENT_END

//----------------------UIMenuSetupSetting_Status_CALLCDCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_CALLCD)
EVENT_END

//----------------------UIMenuSetupSetting_Status_AutoPWROffCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_AutoPWROff)
EVENT_END

//----------------------UIMenuSetupSetting_Status_LanguageCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_Language)
EVENT_END

//----------------------UIMenuSetupSetting_Status_TVModeCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_TVMode)
EVENT_END

//----------------------UIMenuSetupSetting_Status_HZCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_HZ)
EVENT_END

//----------------------UIMenuSetupSetting_Status_AutoLCDOffCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_AutoLCDOff)
EVENT_END

//----------------------UIMenuSetupSetting_Status_FormatCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_Format)
EVENT_END

//----------------------UIMenuSetupSetting_Status_DefaultCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_Default)
EVENT_END

//----------------------UIMenuSetupSetting_Status_VersionCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_Version)
EVENT_END

