//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayFileListRes.c"
#include "UIFlowWndPlayFileList.h"
#include "UIFlow.h"

#include "UIFlowWndHome.h"
#include "UIPlayComm.h"

#if USE_FILEDB
#include "FileDB.h"
#include "namerule_fileDB.h"
#endif
//---------------------UIFlowWndPlayFileListCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileList)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_Video)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_Photo)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_Status_Return)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel1)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel2)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel3)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel4)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel5)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel6)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile1)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile2)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile3)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile4)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile5)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile6)
CTRL_LIST_ITEM(UIFlowWndPlayFilelist_FileNum)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_PrePage)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_NextPage)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListCtrl Event---------------------------
INT32 UIFlowWndPlayFileList_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayFileList_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayFileList_TP(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlayFileList)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPlayFileList_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPlayFileList_OnClose)
EVENT_ITEM(NVTEVT_KEY_TP,UIFlowWndPlayFileList_TP)
EVENT_END

static BOOL PLAYBACK_filelistWindow = FALSE;

static UINT32 g_uiOpenFilePage       = 0;




static int PLAYBACK_WindowType = MovieFile;
static int PLAYBACK_WindowPage = 0;
static int PLAYBACK_TotleMoviePage = 0;
static int PLAYBACK_TotlePhotoPage = 0;
static int PLAYBACK_Totlefilenum = 0;
BOOL GetFilelistStatus(void)
{
    return PLAYBACK_filelistWindow;
}

int GetPlaybackFileType(void)
{
    return PLAYBACK_WindowType;
}

/*
void SetFilelistStatus(BOOL Enb)
{
    PLAYBACK_filelistWindow = Enb;
}
*/
//static CHAR    g_filenameStr[64] = {0};

UINT32 GetCurFileNum(UINT32 num)
{
     FILEDB_HANDLE     FileDBHdl = 0;
    PFILEDB_FILE_ATTR FileAttr = NULL;
    INT32             ret;
    UINT32             i,j;
    FileDB_Refresh(FileDBHdl);
    j = 0;
        for (i=0;i< PLAYBACK_Totlefilenum;i++)
        {
            
            FileAttr = FileDB_SearhFile2(FileDBHdl,i);
            FileSys_WaitFinish();    
            debug_msg("^Y GetCurFileNum  i = %d  name :%s \r\n",i,FileAttr->filename);
            if(GetPlaybackFileType() == MovieFile)
            {
                if(FileAttr->fileType == FILEDB_FMT_MOV)//if(FileAttr->fileType == FILEDB_FMT_JPG)
                {           
                    
                    if(j>= num)
                        break;
                    j++; 
                }
            }
            else if(GetPlaybackFileType() == PhotoFile)
            {
                if(FileAttr->fileType == FILEDB_FMT_JPG)
                {
                
                if(j>= num)
                        break;
                j++; 
                }
            }
                
        }
        debug_msg("^Y GetCurFileNum  %d : %d: %d \r\n",num,j,i );
    return i ;
}

void CheackTotleMoviePhotoFile(UINT32 num)
{
     FILEDB_HANDLE     FileDBHdl = 0;
    PFILEDB_FILE_ATTR FileAttr = NULL;
    INT32             ret;
    UINT32             i,j;
    PLAYBACK_TotlePhotoPage = 0;
    PLAYBACK_TotleMoviePage = 0;
    FileDB_Refresh(FileDBHdl);
        
        for (i=0;i< num;i++)
        {
            FileAttr = FileDB_SearhFile2(FileDBHdl,i);
            FileSys_WaitFinish();  
            debug_msg("^R file num : %d     File name : %s \r\n",i,FileAttr->filename);
            if(FileAttr->fileType == FILEDB_FMT_MOV)//if(FileAttr->fileType == FILEDB_FMT_JPG)
            {           
                PLAYBACK_TotleMoviePage++; 
            }
            else if(FileAttr->fileType == FILEDB_FMT_JPG)
            {
            PLAYBACK_TotlePhotoPage++; 
            }
                
                
        }
        

        PLAYBACK_TotleMoviePage = (PLAYBACK_TotleMoviePage -1)/6 +1;            

        PLAYBACK_TotlePhotoPage = (PLAYBACK_TotlePhotoPage -1)/6 +1;

        debug_msg("^R page : %d    : %d \r\n",PLAYBACK_TotleMoviePage,PLAYBACK_TotlePhotoPage);

}

UINT32 CheackFilePage(UINT32 num)
{
     FILEDB_HANDLE     FileDBHdl = 0;
    PFILEDB_FILE_ATTR FileAttr = NULL;
    INT32             ret;
    UINT32             i,j;
    FileDB_Refresh(FileDBHdl);    
    switch(GetPlaybackFileType())
    {
    case MovieFile:
        j=0;
        for (i=0;i< num;i++)
        {
            FileAttr = FileDB_SearhFile2(FileDBHdl,i);
            FileSys_WaitFinish();     
            if(FileAttr->fileType == FILEDB_FMT_MOV)//if(FileAttr->fileType == FILEDB_FMT_JPG)
            {           
                j++; 
            }
                
        }
        break;
    case PhotoFile:
         j=0;
        for (i=0;i< num;i++)
        {
            FileAttr = FileDB_SearhFile2(FileDBHdl,i);
            FileSys_WaitFinish();     
            if(FileAttr->fileType == FILEDB_FMT_JPG)
            {           
                j++; 
            }
                
        }
        break;
    }
    return j/6;
}


static void PayFileListDrawPageNum(BOOL bShow)
{
    static char item1_Buf[32];


    //hide icon
    if (bShow==FALSE)
    {
        UxCtrl_SetShow(&UIFlowWndPlayFilelist_FileNumCtrl, FALSE);
        return;
    }

    switch(GetPlaybackFileType())
    {
    case MovieFile:
        snprintf(item1_Buf,32,"%d / %d",PLAYBACK_WindowPage+1,PLAYBACK_TotleMoviePage);
        break;
    case PhotoFile:
        snprintf(item1_Buf,32,"%d / %d",PLAYBACK_WindowPage+1,PLAYBACK_TotlePhotoPage);
        break;
    }
    //snprintf(item1_Buf,32,"%d / %d",g_uiOpenFilePage+ 1,PLAYBACK_Totlefilenum/6 +1);
      
    UxStatic_SetData(&UIFlowWndPlayFilelist_FileNumCtrl,STATIC_VALUE,Txt_Pointer(item1_Buf));
    UxCtrl_SetShow(&UIFlowWndPlayFilelist_FileNumCtrl, TRUE);
}


void Update_FileList(int page)
{
    FILEDB_HANDLE     FileDBHdl = 0;
    PFILEDB_FILE_ATTR FileAttr = NULL;
    INT32             ret;
    INT32             FileNum,i,j,k;
    char ptrFileNameData[64];
        
    PayFileListDrawPageNum(TRUE);
    UxCtrl_SetShow(&UIFlowWndPlayFileListFile1Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndPlayFileListFile2Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndPlayFileListFile3Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndPlayFileListFile4Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndPlayFileListFile5Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndPlayFileListFile6Ctrl,FALSE);
    FileDB_Refresh(FileDBHdl);
    j=0;
    k= 0;
    for (i=0;i<=PLAYBACK_Totlefilenum-1;i++)//for (i=Fileid;i<=PLAYBACK_Totlefilenum-1;i++)
    {
        FileAttr = FileDB_SearhFile2(FileDBHdl,i);
        FileSys_WaitFinish();
       switch(PLAYBACK_WindowType)
        {
        case MovieFile:
            if(FileAttr->fileType == FILEDB_FMT_MOV)//if(FileAttr->fileType == FILEDB_FMT_JPG)
            // if (FileAttr)
            {            
            debug_msg("^G   num : %d    File name  : %s\r\n",i,FileAttr->filename); 
            //memset(g_filenameStr,0,sizeof(g_filenameStr));
            //sprintf(g_filenameStr,"%s", FileAttr->filename);
                
                if(j >= page*6)
                    {
                    k++;
                switch(k)
                    {
                    case 1:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile1Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile1Ctrl,TRUE);
                        break;
                    case 2:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile2Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile2Ctrl,TRUE);
                        break;
                    case 3:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile3Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile3Ctrl,TRUE);
                        break;
                    case 4:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile4Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile4Ctrl,TRUE);
                        break;
                    case 5:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile5Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile5Ctrl,TRUE);
                        break;
                    case 6:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile6Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile6Ctrl,TRUE);
                        break;
                    }
                    }
                j++;
            }
            else
            {}
            break;
        case PhotoFile:
            if(FileAttr->fileType == FILEDB_FMT_JPG)//if(FileAttr->fileType == FILEDB_FMT_JPG)
            // if (FileAttr)
            {          
                debug_msg("^G   num : %d    File name  : %s\r\n",i,FileAttr->filename); 
                
                if(j >= page*6)
                    {
                    k++;
                switch(k)
                    {
                    case 1:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile1Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile1Ctrl,TRUE);
                        break;
                    case 2:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile2Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile2Ctrl,TRUE);
                        break;
                    case 3:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile3Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile3Ctrl,TRUE);
                        break;
                    case 4:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile4Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile4Ctrl,TRUE);
                        break;
                    case 5:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile5Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile5Ctrl,TRUE);
                        break;
                    case 6:
                        UxStatic_SetData(&UIFlowWndPlayFileListFile6Ctrl,STATIC_VALUE,Txt_Pointer(FileAttr->filename));
                        UxCtrl_SetShow(&UIFlowWndPlayFileListFile6Ctrl,TRUE);
                        break;
                    }
                    }
                j++;
            }
            else
            {}
            break;
        }
        if(k>=6)
        {
        break;
        }

    }

    //FileSys_WaitFinish();
  
    //FileDB_Refresh(FileDBHdl);
}

INT32 UIFlowWndPlayFileList_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
FILEDB_HANDLE     FileDBHdl = 0;
    PFILEDB_FILE_ATTR FileAttr = NULL;
    if(paramNum > 0)
    {
        PLAYBACK_WindowPage = 0;//CheackFilePage(paramArray[1]);
        debug_ind(("UIFlowWndPlayFileList_OnOpen  File num: %d\r\n", PLAYBACK_WindowPage));
        
    }
    else
    PLAYBACK_WindowPage = 0;    
    PLAYBACK_filelistWindow = TRUE;


    FileSys_WaitFinish();
    FileAttr = FileDB_CurrFile(FileDBHdl);
    FileDB_Refresh(FileDBHdl);
    PLAYBACK_Totlefilenum = FileDB_GetTotalFileNum(FileDBHdl);
   CheackTotleMoviePhotoFile(PLAYBACK_Totlefilenum);
    //PLAYBACK_TotlePhotoPage = FileDB_GetFilesNumByFileType(FileDBHdl, FILEDB_FMT_JPG)/6 +1;
   // PLAYBACK_TotleMoviePage = FileDB_GetFilesNumByFileType(FileDBHdl, FILEDB_FMT_MOV)/6 +1;
    switch(GetPlaybackFileType())
    {
    case MovieFile:
        if(g_uiOpenFilePage > PLAYBACK_TotleMoviePage)
            g_uiOpenFilePage = PLAYBACK_TotleMoviePage;
        break;
    case PhotoFile:
        if(g_uiOpenFilePage > PLAYBACK_TotlePhotoPage)
            g_uiOpenFilePage = PLAYBACK_TotlePhotoPage;
        break;
    }
   
    Update_FileList(g_uiOpenFilePage);
    
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayFileList_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
PLAYBACK_filelistWindow = FALSE;
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

void Cheack_PlayFile(UINT32 page,int Item)
{
    UINT32 Filenum;
    PLAYBACK_Totlefilenum = FileDB_GetTotalFileNum(0);
    if(page*6+Item  > PLAYBACK_Totlefilenum - 1)
        {
        }
    else
        {
        Filenum = GetCurFileNum(page*6+Item );
        Ux_CloseWindow(&UIFlowWndPlayFileListCtrl, 2,NVTRET_THUMBNAIL,Filenum);
        }
}

INT32 UIFlowWndPlayFileList_TP(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
UINT32 uiEvent;
    UINT32 P1,P2;
    UINT32  uiSoundMask;
  
    if(paramNum>0)
        uiEvent = paramArray[0];	
	
	switch(uiEvent)
	{

		case GESTURE_CKICK:
			P1= paramArray[1];
			P2=paramArray[2];  
		    if(TPIsOnRange(&UIFlowWndPlayFileList_Status_ReturnCtrl,P1,P2)==TRUE)
		    	{
		    	    Ux_OpenWindow((VControl *)(&UIFlowWndHomeCtrl), 0);
		    	     //Ux_CloseWindow(&UIFlowWndPlayFileListCtrl, 0);
								   
		    	}	
                else  if(TPIsOnRange(&UIFlowWndPlayFileListFile1Ctrl,P1,P2)==TRUE)
		    	{
		    	    Cheack_PlayFile(PLAYBACK_WindowPage,0);    
		    	     
		    	}	
                else  if(TPIsOnRange(&UIFlowWndPlayFileListFile2Ctrl,P1,P2)==TRUE)
		    	{
		    	Cheack_PlayFile(PLAYBACK_WindowPage,1); 
		    	}
                else  if(TPIsOnRange(&UIFlowWndPlayFileListFile3Ctrl,P1,P2)==TRUE)
		    	{
		    	Cheack_PlayFile(PLAYBACK_WindowPage,2); 
		    	}
                else  if(TPIsOnRange(&UIFlowWndPlayFileListFile4Ctrl,P1,P2)==TRUE)
		    	{
		    	Cheack_PlayFile(PLAYBACK_WindowPage,3); 
		    	}
                else  if(TPIsOnRange(&UIFlowWndPlayFileListFile5Ctrl,P1,P2)==TRUE)
		    	{
		    	Cheack_PlayFile(PLAYBACK_WindowPage,4); 
		    	}
                else  if(TPIsOnRange(&UIFlowWndPlayFileListFile6Ctrl,P1,P2)==TRUE)
		    	{
		    	Cheack_PlayFile(PLAYBACK_WindowPage,5); 		       	
		    	}
                else  if(TPIsOnRange(&UIFlowWndPlayFileList_PrePageCtrl,P1,P2)==TRUE)
		    	{
		    	     if(PLAYBACK_WindowPage <= 0)
		    	        {
		    	        if(GetPlaybackFileType() == MovieFile)
                                PLAYBACK_WindowPage = PLAYBACK_TotleMoviePage -1;
                            else
                                PLAYBACK_WindowPage = PLAYBACK_TotlePhotoPage -1;
		    	        }
                          else
                            PLAYBACK_WindowPage --;
		       	Update_FileList(PLAYBACK_WindowPage);
		    	}
                else  if(TPIsOnRange(&UIFlowWndPlayFileList_NextPageCtrl,P1,P2)==TRUE)
		    	{
		    	    if(GetPlaybackFileType() == MovieFile)
		    	        {
        		    	     if(PLAYBACK_WindowPage >= PLAYBACK_TotleMoviePage -1)
                                    PLAYBACK_WindowPage = 0;
                                  else
                                PLAYBACK_WindowPage ++;
		    	        }
                        else
                            {
                                if(PLAYBACK_WindowPage >= PLAYBACK_TotlePhotoPage -1)
                                        PLAYBACK_WindowPage = 0;
                                      else
                                    PLAYBACK_WindowPage ++;
                            }
                         
		       	Update_FileList(PLAYBACK_WindowPage);
		       	
		    	}
                else  if(TPIsOnRange(&UIFlowWndPlayFileList_VideoCtrl,P1,P2)==TRUE)
		    	{
                        if(PLAYBACK_WindowType == MovieFile)
                        {

                        }
                        else
                        {
                        PLAYBACK_WindowType = MovieFile;
                        PLAYBACK_WindowPage = 0;
                        Update_FileList(PLAYBACK_WindowPage);
                        }
		       	
		    	}
                else  if(TPIsOnRange(&UIFlowWndPlayFileList_PhotoCtrl,P1,P2)==TRUE)
		    	{
                        if(PLAYBACK_WindowType == PhotoFile)
                        {

                        }
                        else
                        {
                        PLAYBACK_WindowType = PhotoFile;
                        PLAYBACK_WindowPage = 0;
                        Update_FileList(PLAYBACK_WindowPage);
                        }
		       	
		    	}
		
		
		break;
	}	  
	

	  
	return NVTEVT_CONSUME;
}

//----------------------UIFlowWndPlayFileList_VideoCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_Video)
EVENT_END

//----------------------UIFlowWndPlayFileList_PhotoCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_Photo)
EVENT_END

//----------------------UIFlowWndPlayFileList_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_Status_Return)
EVENT_END

//---------------------UIFlowWndPlayFileListPanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel1Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel1)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel1)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel2Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel2)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel2)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel3Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel3)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel3Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel3)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel4Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel4)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel4Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel4)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel5Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel5)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel5Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel5)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel6Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel6)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel6Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel6)
EVENT_END

//----------------------UIFlowWndPlayFileListFile1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile1)
EVENT_END

//----------------------UIFlowWndPlayFileListFile2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile2)
EVENT_END

//----------------------UIFlowWndPlayFileListFile3Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile3)
EVENT_END

//----------------------UIFlowWndPlayFileListFile4Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile4)
EVENT_END

//----------------------UIFlowWndPlayFileListFile5Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile5)
EVENT_END

//----------------------UIFlowWndPlayFileListFile6Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile6)
EVENT_END

//----------------------UIFlowWndPlayFilelist_FileNumCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFilelist_FileNum)
EVENT_END
//----------------------UIFlowWndPlayFileList_PrePageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_PrePage)
EVENT_END

//----------------------UIFlowWndPlayFileList_NextPageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_NextPage)
EVENT_END
