//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayRes.c"
#include "UIFlowWndPlay.h"


#include "UIFlowWndPlayMagnify.h"
#include "AppCommon.h"
#include "Audio.h"
#include "UIPlayObj.h"
#include "UICommon.h"
#include "UIFlow.h"
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
#include "MediaPlayAPI.h"
#include "DCF.h"
#include "UIMovieObj.h"
#include "UIFlowWndHome.h"
#include "UIFlowWndPlayFileList.h"
#if USE_FILEDB
#include "FileDB.h"
#include "namerule_fileDB.h"
#endif
#define FULL_FILE_PATH_LEN      64

UINT32         g_uiUIFlowWndPlayCurrentVolume   = AUDIO_VOL_5;
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
UINT32         g_uiUIFlowWndPlayCurrenSpeed     = MEDIAPLAY_SPEED_NORMAL;
UINT32         g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;
MEDIAPLAY_OBJ  g_UIPlayMediaObj                 = {0};
FST_FILE       gphUIFlowMovPlay_Filehdl         = NULL;

static UINT32  g_uiDateTimerID = NULL_TIMER;
//---------------------UIFlowWndPlayCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay)
CTRL_LIST_ITEM(UIFlowWndPlay_Panel_PlayMovie)
CTRL_LIST_ITEM(UIFlowWndPlay_Panel_PlayPhoto)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_Protect)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Filename)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_MovPlayTime)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Speed)
CTRL_LIST_END

//----------------------UIFlowWndPlayCtrl Event---------------------------
INT32 UIFlowWndPlay_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_TP(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieFinish(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnTimer(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlay)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPlay_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPlay_OnClose)
EVENT_ITEM(NVTEVT_KEY_TP,UIFlowWndPlay_TP)
EVENT_ITEM(NVTEVT_KEY_UP,UIFlowWndPlay_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIFlowWndPlay_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIFlowWndPlay_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndPlay_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIFlowWndPlay_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIFlowWndPlay_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_MENU,UIFlowWndPlay_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_DISPLAY,UIFlowWndPlay_OnKeyDisplay)
EVENT_ITEM(NVTEVT_KEY_MODE,UIFlowWndPlay_OnKeyMode)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIFlowWndPlay_OnChildClose)
EVENT_ITEM(NVTEVT_BATTERY,UIFlowWndPlay_OnBattery)
EVENT_ITEM(NVTEVT_BATTERY_LOW,UIFlowWndPlay_OnBatteryLow)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIFlowWndPlay_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIFlowWndPlay_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK,UIFlowWndPlay_OnKeyPlayback)
EVENT_ITEM(NVTEVT_CB_MOVIE_FINISH,UIFlowWndPlay_OnMovieFinish)
EVENT_ITEM(NVTEVT_CB_MOVIE_ONE_SEC,UIFlowWndPlay_OnMovieOneSec)
EVENT_ITEM(NVTEVT_STORAGE_INIT,UIFlowWndPlay_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE,UIFlowWndPlay_OnStorageChange)
EVENT_ITEM(NVTEVT_KEY_TP,UIFlowWndPlay_TP)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndPlay_OnTimer)

EVENT_END

static void UIFlowWndPlay_CheckStatus(void)
{
    UINT32 uiStatus, uiCurrMode;
    uiStatus = AppPlay_GetData(PLAY_PBSTATUS);
    uiCurrMode = AppPlay_GetData(PLAY_CURRMODE);

    // Decode Error & Read Error
    if( uiStatus & (PB_STA_ERR_FILE | PB_STA_ERR_DECODE) )
    {
        if(uiCurrMode == PLAYMODE_AVI || uiCurrMode == PLAYMODE_MOVMJPG)
        {
            UINT32  uiBuffAddr, uiBuffSize;
            CHAR    chaFullName[64] = { 0 };

            PB_GetParam(PBPRMID_DATABUF_ADDR, &uiBuffAddr);
            PB_GetParam(PBPRMID_DATABUF_SIZE, &uiBuffSize);
            PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)&chaFullName);
            MediaPlay_FileRecovery(chaFullName, uiBuffAddr, uiBuffSize);
#if USE_FILEDB
            FileDB_Refresh(0); // should refresh FileDB
#else
            DCF_Refresh(); // should refresh DCF
#endif
            Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 1, PB_SINGLE_CURR);
            uiStatus = AppPlay_GetData(PLAY_PBSTATUS);
            if( uiStatus == PB_STA_DONE)
                return;
        }
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_PICTURE_ERR,FLOWWRNMSG_TIMER_KEEP);
    }
}


typedef enum
{
	UIFLOW_PLAYBACK_TOUCH_KEY_NONE,
	UIFLOW_PLAYBACK_TOUCH_KEY_SHU,				
	UIFLOW_PLAYBACK_TOUCH_KEY_HOME,			
	UIFLOW_PHOTO_TOUCH_KEY_MAX	
}UIFLOW_PLAYBACK_TOUCH_KEY;
static UIFLOW_PLAYBACK_TOUCH_KEY uiPlaybackKeyPressed=UIFLOW_PLAYBACK_TOUCH_KEY_NONE;
#if 0
static INT32 UIFlowWndPlay_OnExeUpKeyAct(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            if (AppPlay_GetData(PLAY_CURRMODE) == PLAYMODE_PRIMARY && AppPlay_GetData(PLAY_PBSTATUS) == PB_STA_DONE)
            {
                Ux_OpenWindow((VControl *)(&UIFlowWndPlayMagnifyCtrl), 0);
            }
            break;
        case PLB_ST_PLAY_MOV:
                if (g_uiUIFlowWndPlayCurrentVolume < AUDIO_VOL_7)
                {
                    // Start to Play
                    g_uiUIFlowWndPlayCurrentVolume++;
                    Ux_SendEvent(&CustomMovieObjCtrl,NVTEVT_EXE_MOVIEAUDPLAYVOLUME,1,g_uiUIFlowWndPlayCurrentVolume);
                    //Ux_SendEvent(&UIMoviePlayObjCtrl,
                    //             NVTEVT_PLAY_PLAY_MOVIE,
                    //             2,
                    //             g_uiUIFlowWndPlayCurrenSpeed,
                    //             g_uiUIFlowWndPlayCurrenDirection);
                    FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
                }
            break;

    }
    return NVTEVT_CONSUME;
}
#endif

#if 0
static INT32 UIFlowWndPlay_OnExeDownKeyAct(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32 uiActKey;

    if (paramNum >= 1)
        uiActKey = paramArray[0];
    else {
        debug_msg("error parameter!!\r\n");
        return NVTEVT_CONSUME;
    }

    switch (uiActKey)
    {
      case NVTEVT_KEY_PRESS:
           switch(g_PlbData.State)
            {
                case PLB_ST_FULL:
                    Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
                    break;
                case PLB_ST_PLAY_MOV:
                        if (g_uiUIFlowWndPlayCurrentVolume > AUDIO_VOL_MUTE)
                        {
                            // Start to Play
                            g_uiUIFlowWndPlayCurrentVolume--;
                            Ux_SendEvent(&CustomMovieObjCtrl,NVTEVT_EXE_MOVIEAUDPLAYVOLUME,1,g_uiUIFlowWndPlayCurrentVolume);
                            //Ux_SendEvent(&UIMoviePlayObjCtrl,
                            //             NVTEVT_PLAY_PLAY_MOVIE,
                            //             2,
                            //             g_uiUIFlowWndPlayCurrenSpeed,
                            //             g_uiUIFlowWndPlayCurrenDirection);
                            FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
                        }
                    break;
            }
        break;
    }
    return NVTEVT_CONSUME;
}
#endif
static BOOL IsMovieFile_Status = TRUE;

void SetIsMovieFile_Status(BOOL Enb)
{
    IsMovieFile_Status = Enb;
}

BOOL GetIsMovieFile_Status(void)
{
    return IsMovieFile_Status;
}

#if 0
#define PREONE 0 
#define NEXTONE 1 

void PlayOtherFile(int FileType,int type)
{
    FILEDB_HANDLE     FileDBHdl = 0;
    PFILEDB_FILE_ATTR FileAttr = NULL;
    INT32             ret;
    INT32             CurFileNum,i,j,TotleFileNum;
    CurFileNum = AppPlay_GetData(PLAY_FILESEQ) - 1;
    TotleFileNum = FileDB_GetTotalFileNum(FileDBHdl);
    j = 0;
    switch(type)
    {
    case NEXTONE:

        for (i=CurFileNum+1;i<=TotleFileNum-1;i++)
        {
            FileAttr = FileDB_SearhFile2(FileDBHdl,i);
            FileSys_WaitFinish();
            switch(FileType)
            {
            case MovieFile:
                if(FileAttr->fileType == FILEDB_FMT_MOV)//if(FileAttr->fileType == FILEDB_FMT_JPG)
                // if (FileAttr)
                {           
                    j++;
                    debug_msg("^G CurFileNum: %d  num : %d    File name  : %s\r\n",CurFileNum,i,FileAttr->filename); 
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_NEXT, i - CurFileNum);
                    break;
                }
                break;
            case PhotoFile:
                if(FileAttr->fileType == FILEDB_FMT_JPG)//if(FileAttr->fileType == FILEDB_FMT_JPG)
                // if (FileAttr)
                {        
                    j++;
                    debug_msg("^G CurFileNum: %d  num : %d    File name  : %s\r\n",CurFileNum,i,FileAttr->filename); 
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_NEXT, i - CurFileNum);
                    break;
                }
                break;
            }
            if(j != 0)
                break;
        }
        break;
    case PREONE:
        for (i=CurFileNum-1;i>=0;i--)
        {
            FileAttr = FileDB_SearhFile2(FileDBHdl,i);
            FileSys_WaitFinish();
            switch(FileType)
            {
            case MovieFile:
                if(FileAttr->fileType == FILEDB_FMT_MOV)//if(FileAttr->fileType == FILEDB_FMT_JPG)
                // if (FileAttr)
                {           
                    j++;
                    debug_msg("^G CurFileNum: %d  num : %d    File name  : %s\r\n",CurFileNum,i,FileAttr->filename); 
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_PREV, CurFileNum - i);
                    break;
                }
                break;
            case PhotoFile:
                if(FileAttr->fileType == FILEDB_FMT_JPG)//if(FileAttr->fileType == FILEDB_FMT_JPG)
                // if (FileAttr)
                {        
                    j++;
                    debug_msg("^G CurFileNum: %d  num : %d    File name  : %s\r\n",CurFileNum,i,FileAttr->filename); 
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_PREV, CurFileNum - i);
                    break;
                }
                break;
            }
            if(j != 0)
                break;
        }
        break;
    }
    FileSys_WaitFinish();
  
    FileDB_Refresh(FileDBHdl);
}
#endif

INT32 UIFlowWndPlay_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
      UINT32  uiSoundMask,uiStatus;
      
    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYINIT,0);
    //After playback ready, point to the last file

//    PB_OpenSpecFileBySeq(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT), TRUE);
    PB_OpenSpecFileBySeq(AppPlay_GetData(PLAY_FILENUM), TRUE);

    
    
    uiStatus = AppPlay_GetData(PLAY_PBSTATUS);
    
    if (uiStatus & PB_STA_NOIMAGE)
    //if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
    {
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_IMAGE,FLOWWRNMSG_TIMER_KEEP);

    }
    else
    {
    /*
        g_PlbData.VideoPBSpeed=PLB_FWD_MOV_1x;
        g_PlbData.State = PLB_ST_FULL;
        UIFlowWndPlay_CheckStatus();
        */
        if(!GetFilelistStatus())
        {
        Ux_OpenWindow((VControl *)(&UIFlowWndPlayFileListCtrl), 1,0);
        return NVTEVT_CONSUME;
        }
        
    }
    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_CURR, 1);
    FlowPB_UpdateIcons(1);
    //jacky lan mark, 2015.08.24	
/*
    if (g_uiDateTimerID == NULL_TIMER)
    {
        g_uiDateTimerID = GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
    }
    */
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiSoundMask;

    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            break;

        case PLB_ST_PLAY_MOV:
        case PLB_ST_PAUSE_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            g_PlbData.State        = PLB_ST_FULL;
            g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
            UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
            g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;

            Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_PAUSE_PLAY_MOVIE, 0);
            Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_CLOSE_PLAY_MOVIE, 0);

            if (gphUIFlowMovPlay_Filehdl)
            {
                FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                gphUIFlowMovPlay_Filehdl = NULL;
            }
            break;
    }

    // disable shutter2 sound
    uiSoundMask = Input_GetKeySoundMask(KEY_PRESS);
    uiSoundMask &= ~FLGKEY_SHUTTER2;
    Input_SetKeySoundMask(KEY_PRESS, uiSoundMask);

    //#NT#2012/10/23#Philex Lin - begin
    // enable auto power off/USB detect timer
    // enable sound key tone
    KeyScan_EnableMisc(TRUE);
    //#NT#2012/10/23#Philex Lin - end
    //g_PlbData.VideoPBSpeed=PLB_FWD_MOV_1x;
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_TP(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
  UINT32 uiEvent;
    UINT32 P1,P2;
    UINT32  uiSoundMask;
  
    if(paramNum>0)
        uiEvent = paramArray[0];	
	
	switch(uiEvent)
	{
		case GESTURE_DOWN2UP://GESTURE_RIGHT2LEFT:		    	
		break;			
		
		case GESTURE_UP2DOWN://GESTURE_LEFT2RIGHT:		    		
		break;	
 
		case GESTURE_PRESSONLY:
                break;

	       case GESTURE_RELEASE:
		   break;
		   
		case GESTURE_CKICK:
			P1= paramArray[1];
			P2=paramArray[2];  
	            //debug_msg("^G movie GESTURE_CKICK\r\n");
	            if (AppPlay_GetData(PLAY_CURRMODE) == PLAYMODE_PRIMARY)
	            {
                     if(TPIsOnRange(&UIFlowWndPlay_Status_PhotoReturnCtrl,P1,P2)==TRUE)
            		    	{
            		    	      // if(uiPlaybackKeyPressed==UIFLOW_PLAYBACK_TOUCH_KEY_HOME)
            		    	       {            			       	                                               
                                       switch(g_PlbData.State)
            				    {
            				    case PLB_ST_FULL:    
                                            Ux_OpenWindow((VControl *)(&UIFlowWndPlayFileListCtrl), 1,0);
            					   //Ux_OpenWindow((VControl *)(&UIFlowWndHomeCtrl), 0);                                                
            				        break;
                                            case PLB_ST_PAUSE_MOV:
                                                #if 1

                                                debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());
                                                Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_PAUSE_PLAY_MOVIE, 0);
                                                debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());
                                                Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_CLOSE_PLAY_MOVIE, 0);
                                                debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());

                                                //#NT#2012/10/23#Philex Lin - begin
                                                // enable auto power off/USB detect timer
                                                // enable key tone flag
                                                KeyScan_EnableMisc(TRUE);
                                                //#NT#2012/10/23#Philex Lin - end


                                                Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 1, PB_SINGLE_CURR);
                                                g_PlbData.State = PLB_ST_MENU;
                                                Ux_OpenWindow((VControl *)(&UIFlowWndPlayFileListCtrl), 1,0);
                                                //Ux_OpenWindow((VControl *)(&UIFlowWndHomeCtrl), 0);
                                                    #endif
                                              break;
            					default:
            			            		FlowPB_UpdateIcons(1);
            			               break;							
            				    }	
            		    	      	}
            				
            		    	  }

            			else if(TPIsOnRange(&UIFlowWndPlay_Status_PhotoPRE_ONECtrl,P1,P2)==TRUE)
            			    {
            			    Ux_PostEvent(NVTEVT_KEY_UP, 1, NVTEVT_KEY_PRESS);
            			    }
                                else if(TPIsOnRange(&UIFlowWndPlay_Status_PhotoZoomoutCtrl,P1,P2)==TRUE)
            			    {
            			    FlowPB_UpdateIcons(1);
            			    }
                                else if(TPIsOnRange(&UIFlowWndPlay_Status_PhotoZoominCtrl,P1,P2)==TRUE)
            			    {
            			    switch(g_PlbData.State)
                                    {
                                        case PLB_ST_FULL:
                                            if (AppPlay_GetData(PLAY_CURRMODE) == PLAYMODE_PRIMARY && AppPlay_GetData(PLAY_PBSTATUS) == PB_STA_DONE)
                                            {
                                                Ux_OpenWindow((VControl *)(&UIFlowWndPlayMagnifyCtrl), 0);
                                            }
                                            break;
                                        case PLB_ST_PLAY_MOV:
                                              
                                            break;

                                    }
                      
            			    }
                                else if(TPIsOnRange(&UIFlowWndPlay_Status_PhotoNextOneCtrl,P1,P2)==TRUE)
            			    {
            			    Ux_PostEvent(NVTEVT_KEY_DOWN, 1, NVTEVT_KEY_PRESS);
            			    }
                                
            		   else
            		    {
            		    
            		    }
                    }
                else
	            //if(GetIsMovieFile_Status())
	                {
            		    if(TPIsOnRange(&UIFlowWndPlay_Status_ReturnCtrl,P1,P2)==TRUE)
            		    	{
            		    	      // if(uiPlaybackKeyPressed==UIFLOW_PLAYBACK_TOUCH_KEY_HOME)
            		    	       {            			       	                                               
                                      switch(g_PlbData.State)
            				    {
            				    case PLB_ST_FULL:      
                                            Ux_OpenWindow((VControl *)(&UIFlowWndPlayFileListCtrl), 1,0);
            					   //Ux_OpenWindow((VControl *)(&UIFlowWndHomeCtrl), 0);                                                
            				        break;
                                            case PLB_ST_PAUSE_MOV:
            									#if 1
                                          
                                                     debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());
            				            Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_PAUSE_PLAY_MOVIE, 0);
                                                     debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());
            				            Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_CLOSE_PLAY_MOVIE, 0);
                                                    debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());

            				            //#NT#2012/10/23#Philex Lin - begin
            				            // enable auto power off/USB detect timer
            				            // enable key tone flag
            				            KeyScan_EnableMisc(TRUE);
            				            //#NT#2012/10/23#Philex Lin - end

            				            
                                                    //Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 1, PB_SINGLE_CURR);
                                                    g_PlbData.State = PLB_ST_MENU;
            					   Ux_OpenWindow((VControl *)(&UIFlowWndPlayFileListCtrl), 1,0);
            					   //Ux_OpenWindow((VControl *)(&UIFlowWndHomeCtrl), 0);
            					   #endif
                                                    break;
            					default:
            			            		FlowPB_UpdateIcons(1);
            			               break;							
            				    }	
            		    	      	}
            				
            		    	  }

            			else if(TPIsOnRange(&UIFlowWndPlay_Status_PRE_ONECtrl,P1,P2)==TRUE)
            			    {
            			    Ux_PostEvent(NVTEVT_KEY_UP, 1, NVTEVT_KEY_PRESS);
            			    }
                                else if(TPIsOnRange(&UIFlowWndPlay_Status_BackwardCtrl,P1,P2)==TRUE)
            			    {
            			    Ux_PostEvent(NVTEVT_KEY_LEFT, 1, NVTEVT_KEY_PRESS);
            			    }
                                else if(TPIsOnRange(&UIFlowWndPlay_Status_PlayCtrl,P1,P2)==TRUE)
            			    {
            			    Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);
            			    }
                                else if(TPIsOnRange(&UIFlowWndPlay_Status_ForwardCtrl,P1,P2)==TRUE)
            			    {
            			    Ux_PostEvent(NVTEVT_KEY_RIGHT, 1, NVTEVT_KEY_PRESS);
            			    }
                                else if(TPIsOnRange(&UIFlowWndPlay_Status_NextOneCtrl,P1,P2)==TRUE)
            			    {
            			    Ux_PostEvent(NVTEVT_KEY_DOWN, 1, NVTEVT_KEY_PRESS);
            			    }
            		   else
            		    {
            		    
            		    }
	                }                                    		  		
		break;
	}	  
	
	  
	return NVTEVT_CONSUME;
}


//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel)
{
    switch (uiChangeSpeedLevel)
    {
        default:
        case PLB_FWD_MOV_1x:
            g_uiUIFlowWndPlayCurrenSpeed = MEDIAPLAY_SPEED_NORMAL;
        break;

        case PLB_FWD_MOV_2x:
        case PLB_BWD_MOV_2x:
            g_uiUIFlowWndPlayCurrenSpeed = MEDIAPLAY_SPEED_7_5X;
        break;

        case PLB_FWD_MOV_4x:
        case PLB_BWD_MOV_4x:
            g_uiUIFlowWndPlayCurrenSpeed = MEDIAPLAY_SPEED_15X;
        break;

        case PLB_FWD_MOV_8x:
        case PLB_BWD_MOV_8x:
            g_uiUIFlowWndPlayCurrenSpeed = MEDIAPLAY_SPEED_30X;
        break;

    }
}
INT32 UIFlowWndPlay_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
    return UIFlowWndPlay_OnExeUpKeyAct(pCtrl, paramNum, paramArray);
#else
    // the same behavior as LEFT key!
    switch(g_PlbData.State)
    {
    case PLB_ST_FULL:
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
        Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_PREV, 1);
        FlowPB_UpdateIcons(1);
        UIFlowWndPlay_CheckStatus();
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
        break;
    case PLB_ST_PAUSE_MOV:
        case PLB_ST_PLAY_MOV:
    case PLB_ST_FWD_MOV:
    case PLB_ST_BWD_MOV:
                g_PlbData.State        = PLB_ST_FULL;
                g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;
                debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());
                Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_PAUSE_PLAY_MOVIE, 0);
                debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());
                Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_CLOSE_PLAY_MOVIE, 0);
                debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());

                //#NT#2012/10/23#Philex Lin - begin
                // enable auto power off/USB detect timer
                // enable key tone flag
                KeyScan_EnableMisc(TRUE);
                //#NT#2012/10/23#Philex Lin - end

                if (gphUIFlowMovPlay_Filehdl)
                {
                FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                gphUIFlowMovPlay_Filehdl = NULL;
                }
                //Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 1, PB_SINGLE_CURR);
                 Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
                 
                //PlayOtherFile(GetPlaybackFileType(),PREONE);
                Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_PREV, 1);
                FlowPB_UpdateIcons(1);
                UIFlowWndPlay_CheckStatus();
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
                break;
        }
    //return UIFlowWndPlay_OnKeyLeft(pCtrl, paramNum, paramArray);
#endif
}
INT32 UIFlowWndPlay_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
    return UIFlowWndPlay_OnExeDownKeyAct(pCtrl, paramNum, paramArray);
#else
    // the same behavior as RIGHT key!
     switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
            Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_NEXT, 1);
            FlowPB_UpdateIcons(1);
        UIFlowWndPlay_CheckStatus();
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            break;
        case PLB_ST_PAUSE_MOV:
            case PLB_ST_PLAY_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
                g_PlbData.State        = PLB_ST_FULL;
                g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;
                debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());
                Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_PAUSE_PLAY_MOVIE, 0);
                debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());
                Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_CLOSE_PLAY_MOVIE, 0);
                debug_msg("^G ==== MediaPlay_GetStatus = %d \r\n",MediaPlay_GetStatus());

                //#NT#2012/10/23#Philex Lin - begin
                // enable auto power off/USB detect timer
                // enable key tone flag
                KeyScan_EnableMisc(TRUE);
                //#NT#2012/10/23#Philex Lin - end

                if (gphUIFlowMovPlay_Filehdl)
                {
                FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                gphUIFlowMovPlay_Filehdl = NULL;
                }
                //Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 1, PB_SINGLE_CURR);
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
                Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_NEXT, 1);
                FlowPB_UpdateIcons(1);
                UIFlowWndPlay_CheckStatus();
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
                break;
        }
    //return UIFlowWndPlay_OnKeyRight(pCtrl, paramNum, paramArray);
#endif
}


INT32 UIFlowWndPlay_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(g_PlbData.State)
    {
    case PLB_ST_FULL:
        
        break;
    case PLB_ST_PAUSE_MOV:
               
                break;
    case PLB_ST_PLAY_MOV:
    case PLB_ST_FWD_MOV:
    case PLB_ST_BWD_MOV:
        //#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
        if(g_PlbData.VideoPBSpeed > PLB_BWD_MOV_4x)
        {
            g_PlbData.VideoPBSpeed --;

            Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);


            if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
            {
                g_PlbData.State = PLB_ST_FWD_MOV;
                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;

                // Play
                Ux_SendEvent(&UIMoviePlayObjCtrl,
                             NVTEVT_PLAY_PLAY_MOVIE,
                             2,
                             g_uiUIFlowWndPlayCurrenSpeed,
                             g_uiUIFlowWndPlayCurrenDirection);
            }
            else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
            {
                g_PlbData.State = PLB_ST_BWD_MOV;
                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_BACKWARD;

                // Play
                Ux_SendEvent(&UIMoviePlayObjCtrl,
                             NVTEVT_PLAY_PLAY_MOVIE,
                             2,
                             g_uiUIFlowWndPlayCurrenSpeed,
                             g_uiUIFlowWndPlayCurrenDirection);

            }
            else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
            {
                g_PlbData.State = PLB_ST_PLAY_MOV;
                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;

                // Play
                Ux_SendEvent(&UIMoviePlayObjCtrl,
                             NVTEVT_PLAY_PLAY_MOVIE,
                             2,
                             g_uiUIFlowWndPlayCurrenSpeed,
                             g_uiUIFlowWndPlayCurrenDirection);
            }

            //FlowPB_IconDrawMovSpeed();
            //Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
        }
        else
            {
            
             g_PlbData.State = PLB_ST_FWD_MOV;
                UIFlowMoviePlay_SetSpeed(PLB_FWD_MOV_1x);
                g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
                g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;

                // Play
                Ux_SendEvent(&UIMoviePlayObjCtrl,
                             NVTEVT_PLAY_PLAY_MOVIE,
                             2,
                             g_uiUIFlowWndPlayCurrenSpeed,
                             g_uiUIFlowWndPlayCurrenDirection);
               // FlowPB_IconDrawMovSpeed();
                
            }
        
        //#NT#2012/08/31#Calvin Chang -end
#if 0
        if (KeyScan_IsHDMIPlugIn()==FALSE) {
            if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_8x)
            {
                g_PlbData.VideoPBSpeed ++;

                Ux_FlushEvent();
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

                if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVFWD,1,g_PlbData.VideoPBSpeed);
                    g_PlbData.State = PLB_ST_FWD_MOV;
                    // set mute in FWD playing
                    hdmitx_setAudMute(TRUE);
                }
                else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVBWD,1,g_PlbData.VideoPBSpeed);
                    g_PlbData.State = PLB_ST_BWD_MOV;
                    // set mute in BWD playing
                    hdmitx_setAudMute(TRUE);
                }
                else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVFWDSTOP,0);
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    /* Since Media FWD/BWD will set volume mute, we should restore current volume. */
                    hdmitx_setAudMute(FALSE);
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_AUD_VOLUME,1,g_uiUIFlowWndPlayCurrentVolume);
                }

                FlowPB_IconDrawMovSpeed();
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            }
        }
#endif
        break;
    }
    FlowPB_UpdateIcons(1);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
           
            break;
        case PLB_ST_PAUSE_MOV:
                
                break;
        case PLB_ST_PLAY_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            //#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
            if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_4x)
            {
                g_PlbData.VideoPBSpeed ++;

                Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

                if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
                {
                    g_PlbData.State = PLB_ST_FWD_MOV;
                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                    g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;

                    // Play
                    Ux_SendEvent(&UIMoviePlayObjCtrl,
                                 NVTEVT_PLAY_PLAY_MOVIE,
                                 2,
                                 g_uiUIFlowWndPlayCurrenSpeed,
                                 g_uiUIFlowWndPlayCurrenDirection);
                }
                else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
                {
                    g_PlbData.State = PLB_ST_BWD_MOV;
                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                    g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_BACKWARD;

                    // Play
                    Ux_SendEvent(&UIMoviePlayObjCtrl,
                                 NVTEVT_PLAY_PLAY_MOVIE,
                                 2,
                                 g_uiUIFlowWndPlayCurrenSpeed,
                                 g_uiUIFlowWndPlayCurrenDirection);

                }
                else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
                {
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                    g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;

                    // Play
                    Ux_SendEvent(&UIMoviePlayObjCtrl,
                                 NVTEVT_PLAY_PLAY_MOVIE,
                                 2,
                                 g_uiUIFlowWndPlayCurrenSpeed,
                                 g_uiUIFlowWndPlayCurrenDirection);
                }
               // FlowPB_IconDrawMovSpeed();
               // Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            }
            else
            {
            
             g_PlbData.State = PLB_ST_FWD_MOV;
                UIFlowMoviePlay_SetSpeed(PLB_FWD_MOV_1x);
                g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;
                g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
                // Play
                Ux_SendEvent(&UIMoviePlayObjCtrl,
                             NVTEVT_PLAY_PLAY_MOVIE,
                             2,
                             g_uiUIFlowWndPlayCurrenSpeed,
                             g_uiUIFlowWndPlayCurrenDirection);
               // FlowPB_IconDrawMovSpeed();
                
            }
            break;
            //#NT#2012/08/31#Calvin Chang -end
//#NT#2012/7/6#Philex mark temp
#if 0
        if (KeyScan_IsHDMIPlugIn()==FALSE) {
            if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_8x)
            {
                g_PlbData.VideoPBSpeed ++;

                Ux_FlushEvent();
                KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_NULL);

                if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVFWD,1,g_PlbData.VideoPBSpeed);
                    g_PlbData.State = PLB_ST_FWD_MOV;
                    // set mute in FWD playing
                    hdmitx_setAudMute(TRUE);
                }
                else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVBWD,1,g_PlbData.VideoPBSpeed);
                    g_PlbData.State = PLB_ST_BWD_MOV;
                    // set mute in BWD playing
                    hdmitx_setAudMute(TRUE);
                }
                else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVFWDSTOP,0);
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    /* Since Media FWD/BWD will set volume mute, we should restore current volume. */
                    hdmitx_setAudMute(FALSE);
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_AUD_VOLUME,1,g_uiUIFlowWndPlayCurrentVolume);
                }

                FlowPB_IconDrawMovSpeed();
                KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            }
        }
        break;
#endif

    }
    FlowPB_UpdateIcons(1);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(g_PlbData.State)
    {
    case PLB_ST_FULL:
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //if (KeyScan_IsHDMIPlugIn()==TRUE)
    //    return NVTEVT_CONSUME;

    switch(g_PlbData.State)
    {
    case PLB_ST_PLAY_MOV:
    case PLB_ST_PAUSE_MOV:
    case PLB_ST_FWD_MOV:
    case PLB_ST_BWD_MOV:
        // stop movie play
        return UIFlowWndPlay_OnMovieFinish(pCtrl, paramNum, paramArray);

    default:
        Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
        Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
        Input_SetKeyMask(KEY_CONTINUE, FLGKEY_KEY_MASK_NULL);
        Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
        break;
    }

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32 uiStatus;
    UINT32 CurFile;
    //#NT#2012/12/27#Hideo Lin -begin
    //#NT#Fix close child window hang up as card removed
    if(Ux_IsForceCloseWindow())
    {
        return NVTEVT_CONSUME;
    }
    //#NT#2012/12/27#Hideo Lin -end

    if(paramNum > 0)
    {
        //Return from thumbnail, magnify or delete mode and play current image again.
        switch(paramArray[0])
        {
        case NVTRET_THUMBNAIL:
        case NVTRET_MAGNIFY:
            if(paramNum > 1)
                {
                CurFile = AppPlay_GetData(PLAY_FILESEQ) - 1;
                debug_msg("^Y  Cur file : %d    play file : %d\r\n",CurFile,paramArray[1]);
                if(paramArray[1] > CurFile)
                Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_NEXT, paramArray[1] - CurFile);
                else
                Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_PREV, CurFile - paramArray[1]);
                }
            else
            Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_CURR, 1);
            FlowPB_UpdateIcons(1);
            UIFlowWndPlay_CheckStatus();
            break;
        case NVTRET_DELETE:
        case NVTRET_DELETEALL:
            uiStatus = AppPlay_GetData(PLAY_PBSTATUS);

            if (uiStatus & PB_STA_NOIMAGE)
            //if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
            {
               
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_IMAGE,FLOWWRNMSG_TIMER_KEEP);
                  
            }
            else
            {
                Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_CURR, 1);
                FlowPB_UpdateIcons(1);
                //UIFlowWndPlay_CheckStatus();
            }
            break;
        case NVTRET_ENTER_MENU:
            // Reset specific menu items
            SysSetFlag(FL_PROTECT, PROTECT_ONE);
            // Set Tab menu to Playback menu
            //TM_SetMenu(&gPlaybackMenu);
            // Open common item menu
            //Ux_OpenWindow(&MenuCommonItemCtrl, 0);
           // g_bUIFlowWndPlayNoImgWndOpened = FALSE;
            break;
        case NVTRET_WARNING:
            Ux_PostEvent(paramArray[1], 0);
            break;
        }
    }
    else
    {
        uiStatus = AppPlay_GetData(PLAY_PBSTATUS);
        if (uiStatus & PB_STA_NOIMAGE)
        //if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
        {
            
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_IMAGE,FLOWWRNMSG_TIMER_KEEP);
             
        }
        else
        {
            Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_CURR, 1);
            FlowPB_UpdateIcons(1);
          //  UIFlowWndPlay_CheckStatus();
        }
    }
    g_PlbData.State = PLB_ST_FULL;

    //#NT#2012/10/23#Philex Lin - begin
    // enable auto power off/USB detect timer
    // enable sound key tone flag
    KeyScan_EnableMisc(TRUE);
    //#NT#2012/10/23#Philex Lin - end
    Display_SetEnable(LAYER_VDO1, TRUE);				

    // set mask key
    //Ux_FlushEvent();
   
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
  static volatile BOOL bBatteryOn = FALSE;

    UxState_SetData(&UIFlowWndPlay_StatusICN_BaterryCtrl,STATE_CURITEM,GetBatteryLevel());
    //if (KeyScan_IsACIn())
    {
        bBatteryOn = !bBatteryOn;
       // if (bBatteryOn==FALSE){
            //UxState_SetData(&UIFlowWndPlay_StatusICN_BaterryCtrl,STATE_CURITEM,UIFlowWndPlay_StatusICN_Battery_ICON_TRANSPAENT);
     //   UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BaterryCtrl,bBatteryOn);
  //  } else {
        UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BaterryCtrl,TRUE);
  //  }
    }
    if(GxUSB_GetIsUSBPlug()&&GetBatteryLevel())//(GetBatteryLevel() == BATTERY_CHARGE)
        UxCtrl_SetShow(&UIFlowWndPlay_StaticICN_BatteryChargeCtrl,TRUE);	
    else
        UxCtrl_SetShow(&UIFlowWndPlay_StaticICN_BatteryChargeCtrl,FALSE);	
#endif
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW, FLOWWRNMSG_TIMER_5SEC);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
#else
    // the same behavior as ENTER key!
    return UIFlowWndPlay_OnKeyEnter(pCtrl, paramNum, paramArray);
#endif
}
INT32 UIFlowWndPlay_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
    //UINT32 uiCurindex;
    UINT32 uiPoolAddr;
    char   pFilePath[FULL_FILE_PATH_LEN];
    UINT32 fileType = DCF_FILE_TYPE_JPG;
    UINT32 uiPBFileFmt;

    switch(g_PlbData.State)
    {
        case PLB_ST_PLAY_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_PAUSE_PLAY_MOVIE, 0);
            //FlowPB_IconDrawMovPlay(TRUE);
            g_PlbData.State = PLB_ST_PAUSE_MOV;
            FlowPB_IconDrawMovPlay(TRUE);			
            //#NT#2012/10/23#Philex Lin - begin
            // enable auto power off/USB detect timer
            // enable sound key tone flag
            KeyScan_EnableMisc(TRUE);
            //#NT#2012/10/23#Philex Lin - end
            break;

        case PLB_ST_PAUSE_MOV:
            //#NT#2012/10/23#Philex Lin - begin
            // disable auto power off/USB detect timer
            // disable key tone flag
            KeyScan_EnableMisc(FALSE);
            //#NT#2012/10/23#Philex Lin - end
            // Start to Play
            Ux_SendEvent(&UIMoviePlayObjCtrl,
                         NVTEVT_PLAY_PLAY_MOVIE,
                         2,
                         g_uiUIFlowWndPlayCurrenSpeed,
                         g_uiUIFlowWndPlayCurrenDirection);
            //FlowPB_IconDrawMovPlay(TRUE);
            g_PlbData.State = PLB_ST_PLAY_MOV;
            FlowPB_IconDrawMovPlay(TRUE);			
            break;

        default:
        case PLB_ST_FULL:
            uiPBFileFmt = AppPlay_GetData(PLAY_FILEFMT);
            if (uiPBFileFmt & PBFMT_AVI ||
                uiPBFileFmt & PBFMT_MOVMJPG ||
                uiPBFileFmt & PBFMT_MP4)
            {
                // Open Video File
                if (gphUIFlowMovPlay_Filehdl)
                {
                    FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                    gphUIFlowMovPlay_Filehdl = NULL;
                }
                if (uiPBFileFmt & PBFMT_AVI)
                  fileType = DCF_FILE_TYPE_AVI;
                else if (uiPBFileFmt & PBFMT_MOVMJPG)
                  fileType = DCF_FILE_TYPE_MOV;
                else if (uiPBFileFmt & PBFMT_MP4)
                  fileType = DCF_FILE_TYPE_MOV;
                else
                {
                    debug_msg("Wrong video file format!! \r\n");
                    break;
                }

                // Get Current index
                PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
#if 0
                uiCurindex = DCF_GetCurIndex();
                DCF_GetObjPath(uiCurindex,fileType,pFilePath);
#endif
                // Open Test Media File
                gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

                if (!gphUIFlowMovPlay_Filehdl)
                {
                    debug_msg("UIFlowWndPlay_OnKeyEnter: Can't open Video file!\r\n");
                    break;
                }
                //#NT#2012/10/23#Philex Lin - begin
                // disable auto power off/USB detect timer
                // disable key tone flag
                KeyScan_EnableMisc(FALSE);
                //#NT#2012/10/23#Philex Lin - end

                // Buffer Allocation
                get_blf((VP*)&(uiPoolAddr), POOL_ID_APP);
                rel_blf(POOL_ID_APP, (VP)uiPoolAddr);

                g_UIPlayMediaObj.hActMediafilehdl = gphUIFlowMovPlay_Filehdl;
                g_UIPlayMediaObj.CallBackFunc     = Play_MovieCB;
//                g_UIPlayMediaObj.uiMemAddr        = uiPoolAddr;
                g_UIPlayMediaObj.uiMemAddr        = (UINT32)OS_GetMempoolAddr(POOL_ID_APP);
                g_UIPlayMediaObj.uiMemSize        = POOL_SIZE_APP;
                //g_UIPlayMediaObj.iAudioType       = AUDIO_OUTPUT_HP;
                g_UIPlayMediaObj.bDisableAudio    = FALSE;

                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;

                //flush event first
                Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);

                //stop scan
                //SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, FALSE);
                SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, FALSE);

                Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_INIT_PLAY_MOVIE, 1, &g_UIPlayMediaObj);

                // Start to Play
                Ux_SendEvent(&UIMoviePlayObjCtrl,
                             NVTEVT_PLAY_PLAY_MOVIE,
                             2,
                             g_uiUIFlowWndPlayCurrenSpeed,
                             g_uiUIFlowWndPlayCurrenDirection);

                if (KeyScan_GetPlugDev()!=PLUG_HDMI)
                {
                    FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
                }
                FlowPB_IconDrawMovPlay(TRUE);
                g_PlbData.State = PLB_ST_PLAY_MOV;
                FlowPB_IconDrawMovPlay(TRUE);				

            }
            break;
    }
    //#NT#2012/08/31#Calvin Chang -end

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            // Set mask key
            Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
           
            Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
            break;

        case PLB_ST_PLAY_MOV:
        case PLB_ST_PAUSE_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            g_PlbData.State        = PLB_ST_FULL;
            g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
            UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
            g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;

            Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_PAUSE_PLAY_MOVIE, 0);
            Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_CLOSE_PLAY_MOVIE, 0);

            //#NT#2012/10/23#Philex Lin - begin
            // enable auto power off/USB detect timer
            // enable key tone flag
            KeyScan_EnableMisc(TRUE);
            //#NT#2012/10/23#Philex Lin - end

            if (gphUIFlowMovPlay_Filehdl)
            {
                FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                gphUIFlowMovPlay_Filehdl = NULL;
            }
            FlowPB_UpdateIcons(1);
            break;

    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnMovieFinish(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
    g_PlbData.State        = PLB_ST_FULL;
    g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
    g_uiUIFlowWndPlayCurrenDirection = MEDIAPLAY_DIR_FORWARD;

    Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_PAUSE_PLAY_MOVIE, 0);
    Ux_SendEvent(&UIMoviePlayObjCtrl, NVTEVT_CLOSE_PLAY_MOVIE, 0);

    //#NT#2012/10/23#Philex Lin - begin
    // enable auto power off/USB detect timer
    // enable key tone flag
    KeyScan_EnableMisc(TRUE);
    //#NT#2012/10/23#Philex Lin - end

    // stop scan
    //if (SxTimer_GetFuncActive(SX_TIMER_DET_STRG_ID)==0)
//        SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, TRUE);

    if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID)==0)
        SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);


    if (gphUIFlowMovPlay_Filehdl)
    {
        FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
        gphUIFlowMovPlay_Filehdl = NULL;
    }

    // Play 1st video frame image
    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 1, PB_SINGLE_CURR);
    //#NT#2012/08/31#Calvin Chang -end

    FlowPB_UpdateIcons(1);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    FlowPB_IconDrawMovPlayTime(TRUE);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 NVTEVT event;


    if(paramNum > 0)
    {
       event = paramArray[0];
    } else {
       return NVTEVT_CONSUME;
    }
    switch(event)
    {
      case NVTEVT_1SEC_TIMER:
		//FlowPB_IconDrawDateTime();
	break;
    }
    return NVTEVT_CONSUME;
}

//---------------------UIFlowWndPlay_Panel_PlayMovieCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay_Panel_PlayMovie)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PRE_ONE)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_Backward)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_Play)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_Forward)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_NextOne)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_Return)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PlayPause_BG)
CTRL_LIST_END
//----------------------UIFlowWndPlay_Panel_PlayMovieCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Panel_PlayMovie)
EVENT_END

//----------------------UIFlowWndPlay_Status_PRE_ONECtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PRE_ONE)
EVENT_END

//----------------------UIFlowWndPlay_Status_BackwardCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_Backward)
EVENT_END

//----------------------UIFlowWndPlay_Status_PlayCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_Play)
EVENT_END

//----------------------UIFlowWndPlay_Status_ForwardCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_Forward)
EVENT_END

//----------------------UIFlowWndPlay_Status_NextOneCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_NextOne)
EVENT_END
//----------------------UIFlowWndPlay_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_Return)
EVENT_END

//----------------------UIFlowWndPlay_Status_PlayPause_BGCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PlayPause_BG)
EVENT_END

//---------------------UIFlowWndPlay_Panel_PlayPhotoCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay_Panel_PlayPhoto)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PhotoPRE_ONE)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PhotoZoomout)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PhotoZoomin)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PhotoNextOne)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PhotoReturn)
CTRL_LIST_END

//----------------------UIFlowWndPlay_Panel_PlayPhotoCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Panel_PlayPhoto)
EVENT_END

//----------------------UIFlowWndPlay_Status_PhotoPRE_ONECtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PhotoPRE_ONE)
EVENT_END

//----------------------UIFlowWndPlay_Status_PhotoZoomoutCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PhotoZoomout)
EVENT_END

//----------------------UIFlowWndPlay_Status_PhotoZoominCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PhotoZoomin)
EVENT_END

//----------------------UIFlowWndPlay_Status_PhotoNextOneCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PhotoNextOne)
EVENT_END

//----------------------UIFlowWndPlay_Status_PhotoReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PhotoReturn)
EVENT_END
//----------------------UIFlowWndPlay_StaticICN_ProtectCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_Protect)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_FilenameCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Filename)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_MovPlayTime)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_SpeedCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Speed)
EVENT_END
