//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAYMAGNIFY_H
#define UIFLOWWNDPLAYMAGNIFY_H

#include "UIFramework.h"

extern VControl UIFlowWndPlayMagnifyCtrl;//Panel type 

extern VControl UIFlowWndPlayMagnify_StaticTXT_DZoomCtrl;//Static type 

extern VControl UIFlowWndPlayMagnify_StaticIcon_DirUpCtrl;//Static type 

extern VControl UIFlowWndPlayMagnify_StaticIcon_DirDownCtrl;//Static type 

extern VControl UIFlowWndPlayMagnify_StaticIcon_DirRightCtrl;//Static type 

extern VControl UIFlowWndPlayMagnify_StaticIcon_DirLeftCtrl;//Static type 

extern VControl UIFlowWndPlayMagnify_Status_PhotoZoominCtrl;//List type 

typedef enum
{
UIFlowWndPlayMagnify_Status_PhotoZoomin_ICON_PLAY_PHOTO_ZOOMIN,
UIFlowWndPlayMagnify_Status_PhotoZoomin_MAX
}UIFlowWndPlayMagnify_Status_PhotoZoomin_Setting;

extern VControl UIFlowWndPlayMagnify_Status_PhotoZoomoutCtrl;//List type 

typedef enum
{
UIFlowWndPlayMagnify_Status_PhotoZoomout_ICON_PLAY_PHOTO_ZOOMOUT,
UIFlowWndPlayMagnify_Status_PhotoZoomout_MAX
}UIFlowWndPlayMagnify_Status_PhotoZoomout_Setting;

extern VControl UIFlowWndPlayMagnify_Status_ReturnCtrl;//List type 

typedef enum
{
UIFlowWndPlayMagnify_Status_Return_STRID_NULL_,
UIFlowWndPlayMagnify_Status_Return_MAX
}UIFlowWndPlayMagnify_Status_Return_Setting;

#endif
