/*//////////////////////////////////////////////////////////////////////////////

 ---------- Document Info ---------------

        Author : Anonymous
       Created : 15:18:17, Mar 22 2013
 Last modified : 15:18:17, Mar 22 2013
   Making tool : UI Designer Studio
   File format : C language header file

 ----------- Object Info ----------------

         Class : IMAGE_TABLE
          Name : DemoKit_Image

*///////////////////////////////////////////////////////////////////////////////

#ifndef _DEMOKIT_IMAGE_H_
#define _DEMOKIT_IMAGE_H_

// IMAGE_TABLE
extern const
unsigned char gDemoKit_Image[];

// IMAGE ID
#define ICON_ABC                                 0x0000
#define ICON_BATTERY_CHARGE                      0x0001
#define ICON_BATTERY_EMPTY                       0x0002
#define ICON_BATTERY_FULL                        0x0003
#define ICON_BATTERY_LOW                         0x0004
#define ICON_BATTERY_MED                         0x0005
#define ICON_BATTERY_ZERO                        0x0006
#define ICON_CAL_LCD                             0x0007
#define ICON_CAR_NUM                             0x0008
#define ICON_CITY_MODE                           0x0009
#define ICON_DISTANCE_0                          0x000A
#define ICON_DISTANCE_1                          0x000B
#define ICON_DISTANCE_2                          0x000C
#define ICON_DISTANCE_3                          0x000D
#define ICON_DISTANCE_4                          0x000E
#define ICON_DISTANCE_5                          0x000F
#define ICON_DISTANCE_6                          0x0010
#define ICON_DISTANCE_7                          0x0011
#define ICON_DISTANCE_8                          0x0012
#define ICON_DISTANCE_9                          0x0013
#define ICON_E                                   0x0014
#define ICON_EN                                  0x0015
#define ICON_ES                                  0x0016
#define ICON_FILE_VIDEO                          0x0017
#define ICON_GPS_OFF                             0x0018
#define ICON_GPS_OFF_RD_DIS                      0x0019
#define ICON_GPS_OFF_RD_EN                       0x001A
#define ICON_GPS_ON                              0x001B
#define ICON_GPS_ON_RD_DIS                       0x001C
#define ICON_GPS_ON_RD_EN                        0x001D
#define ICON_GSENSOR_H                           0x001E
#define ICON_GSENSOR_L                           0x001F
#define ICON_GSENSOR_M                           0x0020
#define ICON_HDR                                 0x0021
#define ICON_HIGHSPEED_MODE                      0x0022
#define ICON_HZ_BACKGROND                        0x0023
#define ICON_HZ_K                                0x0024
#define ICON_HZ_KA                               0x0025
#define ICON_HZ_X                                0x0026
#define ICON_INTERNAL_FLASH                      0x0027
#define ICON_LOCK                                0x0028
#define ICON_LOCK_BIG                            0x0029
#define ICON_MAIN_MENU_MOVIE                     0x002A
#define ICON_MAIN_MENU_PHOTO                     0x002B
#define ICON_MAIN_MENU_RADAR                     0x002C
#define ICON_MAIN_MENU_SETUP                     0x002D
#define ICON_MAIN_PHOTO_MODE                     0x002E
#define ICON_MAIN_PLAYBACK_MODE                  0x002F
#define ICON_MAIN_RETURN                         0x0030
#define ICON_MAIN_VIDEO_MODE                     0x0031
#define ICON_MENU_LEFT_NORMAL                    0x0032
#define ICON_MENU_LEFT_PRESS                     0x0033
#define ICON_MENU_MOVIE_CYCREC                   0x0034
#define ICON_MENU_MOVIE_DATESTAM                 0x0035
#define ICON_MENU_MOVIE_DUALREC                  0x0036
#define ICON_MENU_MOVIE_EV                       0x0037
#define ICON_MENU_MOVIE_GSENSOR                  0x0038
#define ICON_MENU_MOVIE_HDR                      0x0039
#define ICON_MENU_MOVIE_MOTIONDET                0x003A
#define ICON_MENU_MOVIE_MOVIESIZE                0x003B
#define ICON_MENU_MOVIE_PARKINGMODE              0x003C
#define ICON_MENU_MOVIE_TIMELAPSE_REC            0x003D
#define ICON_MENU_PHOTO_AWB                      0x003E
#define ICON_MENU_PHOTO_CNT_SHOOT                0x003F
#define ICON_MENU_PHOTO_DATESTAMP                0x0040
#define ICON_MENU_PHOTO_EV                       0x0041
#define ICON_MENU_PHOTO_ISO                      0x0042
#define ICON_MENU_PHOTO_PHOTOSIZE                0x0043
#define ICON_MENU_PHOTO_QUALITY                  0x0044
#define ICON_MENU_PHOTO_QUIKVIEW                 0x0045
#define ICON_MENU_PHOTO_SELFTIME                 0x0046
#define ICON_MENU_PHOTO_SHARK                    0x0047
#define ICON_MENU_PHOTO_SHARP                    0x0048
#define ICON_MENU_RADAR_CITYMODE_SPEEDLIMIT      0x0049
#define ICON_MENU_RADAR_DRIVERMODE               0x004A
#define ICON_MENU_RADAR_HZ                       0x004B
#define ICON_MENU_RADAR_SPEAKSET                 0x004C
#define ICON_MENU_RADAR_SPEED_SETTING            0x004D
#define ICON_MENU_RADAR_USER_SPEEDLIMIT          0x004E
#define ICON_MENU_RADAR_WARNINGSET               0x004F
#define ICON_MENU_RADAR_X                        0x0050
#define ICON_MENU_RETURN                         0x0051
#define ICON_MENU_RIGHT_NORMAL                   0x0052
#define ICON_MENU_RIGHT_PRESS                    0x0053
#define ICON_MENU_SETUP_AUTO_LCD_OFF             0x0054
#define ICON_MENU_SETUP_AUTO_PWROFF              0x0055
#define ICON_MENU_SETUP_DEFAULT                  0x0056
#define ICON_MENU_SETUP_FORMAT                   0x0057
#define ICON_MENU_SETUP_HZ                       0x0058
#define ICON_MENU_SETUP_KEYBEEP                  0x0059
#define ICON_MENU_SETUP_LANGUAGE                 0x005A
#define ICON_MENU_SETUP_SET_TIME                 0x005B
#define ICON_MENU_SETUP_TV                       0x005C
#define ICON_MENU_SETUP_VERTION                  0x005D
#define ICON_MENU_TIME_BG                        0x005E
#define ICON_MOTION_DET                          0x005F
#define ICON_MOTION_OFF                          0x0060
#define ICON_MOTION_ON                           0x0061
#define ICON_N                                   0x0062
#define ICON_NUM                                 0x0063
#define ICON_NUM_B_0                             0x0064
#define ICON_NUM_B_1                             0x0065
#define ICON_NUM_B_2                             0x0066
#define ICON_NUM_B_3                             0x0067
#define ICON_NUM_B_4                             0x0068
#define ICON_NUM_B_5                             0x0069
#define ICON_NUM_B_6                             0x006A
#define ICON_NUM_B_7                             0x006B
#define ICON_NUM_B_8                             0x006C
#define ICON_NUM_B_9                             0x006D
#define ICON_NUM_B_BG                            0x006E
#define ICON_NUM_B_M                             0x006F
#define ICON_NUM_S_0                             0x0070
#define ICON_NUM_S_1                             0x0071
#define ICON_NUM_S_2                             0x0072
#define ICON_NUM_S_3                             0x0073
#define ICON_NUM_S_4                             0x0074
#define ICON_NUM_S_5                             0x0075
#define ICON_NUM_S_6                             0x0076
#define ICON_NUM_S_7                             0x0077
#define ICON_NUM_S_8                             0x0078
#define ICON_NUM_S_9                             0x0079
#define ICON_NUM_S_BG                            0x007A
#define ICON_NUM_S_KM                            0x007B
#define ICON_OK                                  0x007C
#define ICON_PARKING_MONITOR                     0x007D
#define ICON_PARKING_MONITOR_M                   0x007E
#define ICON_PLAY_PHOTO_ZOOMIN                   0x007F
#define ICON_PLAY_PHOTO_ZOOMOUT                  0x0080
#define ICON_PLAYBACK_BACKWARD                   0x0081
#define ICON_PLAYBACK_FORWARD                    0x0082
#define ICON_PLAYBACK_NEXTONE                    0x0083
#define ICON_PLAYBACK_PAUSE                      0x0084
#define ICON_PLAYBACK_PHOTO                      0x0085
#define ICON_PLAYBACK_PLAY                       0x0086
#define ICON_PLAYBACK_PREONE                     0x0087
#define ICON_PLAYBACK_RETURN                     0x0088
#define ICON_PLAYBACK_VIDEO                      0x0089
#define ICON_PLAYPHOTO_DOWN                      0x008A
#define ICON_PLAYPHOTO_LEFT                      0x008B
#define ICON_PLAYPHOTO_RIGHT                     0x008C
#define ICON_PLAYPHOTO_UP                        0x008D
#define ICON_QUALITY_BASIC                       0x008E
#define ICON_QUALITY_FINE                        0x008F
#define ICON_QUALITY_NORMAL                      0x0090
#define ICON_RADAR_FAIL                          0x0091
#define ICON_RADAR_JG                            0x0092
#define ICON_RADAR_SINGAL                        0x0093
#define ICON_RADAR_SINGAL_OK                     0x0094
#define ICON_RADAR_VOL_STRING                    0x0095
#define ICON_RADAR_WAR_0                         0x0096
#define ICON_RADAR_WAR_1                         0x0097
#define ICON_RADAR_WAR_2                         0x0098
#define ICON_RADAR_WAR_3                         0x0099
#define ICON_RADAR_WAR_4                         0x009A
#define ICON_RADAR_WAR_5                         0x009B
#define ICON_RADAR_WAR_6                         0x009C
#define ICON_RADAR_WAR_7                         0x009D
#define ICON_RADAR_WAR_8                         0x009E
#define ICON_RADAR_WAR_9                         0x009F
#define ICON_RADAR_WAR_BACKGROND                 0x00A0
#define ICON_RD_EYE_OFF                          0x00A1
#define ICON_RD_EYE_ON                           0x00A2
#define ICON_RD_OFF                              0x00A3
#define ICON_RD_ON                               0x00A4
#define ICON_RD_WAR_EYE                          0x00A5
#define ICON_REC_ELIPPSE                         0x00A6
#define ICON_RECORD_START                        0x00A7
#define ICON_REDLED                              0x00A8
#define ICON_S                                   0x00A9
#define ICON_SD_CARD                             0x00AA
#define ICON_SEL_BAR_BEGIN                       0x00AB
#define ICON_SEL_BAR_DATE                        0x00AC
#define ICON_SEL_BAR_END                         0x00AD
#define ICON_SEL_BAR_ITEM                        0x00AE
#define ICON_SEL_BAR_MED                         0x00AF
#define ICON_SEL_BAR_YEAR                        0x00B0
#define ICON_SELFTIMER_2SEC                      0x00B1
#define ICON_SELFTIMER_5SEC                      0x00B2
#define ICON_SELFTIMER_10SEC                     0x00B3
#define ICON_SHAKE_OFF                           0x00B4
#define ICON_SHAKE_ON                            0x00B5
#define ICON_SHARPNESS_HIGH                      0x00B6
#define ICON_SHARPNESS_LOW                       0x00B7
#define ICON_SHARPNESS_MED                       0x00B8
#define ICON_SPEEDLIMIT_0                        0x00B9
#define ICON_SPEEDLIMIT_1                        0x00BA
#define ICON_SPEEDLIMIT_2                        0x00BB
#define ICON_SPEEDLIMIT_3                        0x00BC
#define ICON_SPEEDLIMIT_4                        0x00BD
#define ICON_SPEEDLIMIT_5                        0x00BE
#define ICON_SPEEDLIMIT_6                        0x00BF
#define ICON_SPEEDLIMIT_7                        0x00C0
#define ICON_SPEEDLIMIT_8                        0x00C1
#define ICON_SPEEDLIMIT_9                        0x00C2
#define ICON_SYMBOL                              0x00C3
#define ICON_TIME_0                              0x00C4
#define ICON_TIME_1                              0x00C5
#define ICON_TIME_2                              0x00C6
#define ICON_TIME_3                              0x00C7
#define ICON_TIME_4                              0x00C8
#define ICON_TIME_5                              0x00C9
#define ICON_TIME_6                              0x00CA
#define ICON_TIME_7                              0x00CB
#define ICON_TIME_8                              0x00CC
#define ICON_TIME_9                              0x00CD
#define ICON_TIME_DOT                            0x00CE
#define ICON_TIME_SET_RETURN                     0x00CF
#define ICON_TITLE_BAR                           0x00D0
#define ICON_TRANSPAENT                          0x00D1
#define ICON_VOICE_M                             0x00D2
#define ICON_VOICE_OFF                           0x00D3
#define ICON_VOICE_ON                            0x00D4
#define ICON_VOL_NUM_0                           0x00D5
#define ICON_VOL_NUM_2                           0x00D6
#define ICON_VOL_NUM_3                           0x00D7
#define ICON_VOL_NUM_4                           0x00D8
#define ICON_VOL_NUM_5                           0x00D9
#define ICON_VOL_NUM_6                           0x00DA
#define ICON_VOL_NUM_7                           0x00DB
#define ICON_VOL_NUM_8                           0x00DC
#define ICON_VOL_NUM_9                           0x00DD
#define ICON_W                                   0x00DE
#define ICON_WB_AUTO                             0x00DF
#define ICON_WB_CLOUDY                           0x00E0
#define ICON_WB_DAYLIGHT                         0x00E1
#define ICON_WB_FLUORESCENT                      0x00E2
#define ICON_WB_TUNGSTEN                         0x00E3
#define ICON_WDR                                 0x00E4
#define ICON_WN                                  0x00E5
#define ICON_WS                                  0x00E6
#define DAOCHE                                   0x00E7

#endif //_DEMOKIT_IMAGE_H_
