//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "MenuCommonOptionRes.c"
#include "MenuCommonOption.h"
//---------------------MenuCommonOptionCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonOption)
CTRL_LIST_ITEM(UIMenuCommonOptionTitle)
CTRL_LIST_ITEM(MenuCommonOptionPanel)
CTRL_LIST_ITEM(MenuCommonOptionReturn)
CTRL_LIST_ITEM(MenuCommonOption_Info)
CTRL_LIST_ITEM(MenuCommonOption_Right)
CTRL_LIST_ITEM(MenuCommonOption_Left)
CTRL_LIST_END

//----------------------MenuCommonOptionCtrl Event---------------------------
INT32 MenuCommonOption_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonOption)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,MenuCommonOption_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,MenuCommonOption_OnClose)
EVENT_END

INT32 MenuCommonOption_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuCommonOptionTitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuCommonOptionTitle)
EVENT_END

//---------------------MenuCommonOptionPanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonOptionPanel)
CTRL_LIST_END

//----------------------MenuCommonOptionPanelCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOptionPanel)
EVENT_END

//----------------------MenuCommonOptionReturnCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOptionReturn)
EVENT_END

//----------------------MenuCommonOption_InfoCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOption_Info)
EVENT_END

//----------------------MenuCommonOption_RightCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOption_Right)
EVENT_END

//----------------------MenuCommonOption_LeftCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOption_Left)
EVENT_END

