//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDCALLCD_H
#define UIFLOWWNDCALLCD_H

#include "UIFramework.h"

extern VControl UIFlowWndCalLCDCtrl;//Panel type 

extern VControl UIFlowWndCalLCD_LeftTopCtrl;//Panel type 

extern VControl UIFlowWndCalLCD_TipCtrl;//Static type 

extern VControl UIFlowWndCalLCD_RightTopCtrl;//Panel type 

extern VControl UIFlowWndCalLCD_LeftBottomCtrl;//Panel type 

extern VControl UIFlowWndCalLCD_LeftTopPointCtrl;//Panel type 

extern VControl UIFlowWndCalLCD_RightBottomPointCtrl;//Panel type 

#endif
