//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndCalLCDRes.c"
#include "UIFlowWndCalLCD.h"
//---------------------UIFlowWndCalLCDCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD)
CTRL_LIST_ITEM(UIFlowWndCalLCD_LeftTop)
CTRL_LIST_ITEM(UIFlowWndCalLCD_Tip)
CTRL_LIST_ITEM(UIFlowWndCalLCD_RightTop)
CTRL_LIST_ITEM(UIFlowWndCalLCD_LeftBottom)
CTRL_LIST_ITEM(UIFlowWndCalLCD_LeftTopPoint)
CTRL_LIST_ITEM(UIFlowWndCalLCD_RightBottomPoint)
CTRL_LIST_END

//----------------------UIFlowWndCalLCDCtrl Event---------------------------
INT32 UIFlowWndCalLCD_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndCalLCD_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndCalLCD)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndCalLCD_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndCalLCD_OnClose)
EVENT_END

INT32 UIFlowWndCalLCD_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndCalLCD_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIFlowWndCalLCD_LeftTopCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD_LeftTop)
CTRL_LIST_END

//----------------------UIFlowWndCalLCD_LeftTopCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_LeftTop)
EVENT_END

//----------------------UIFlowWndCalLCD_TipCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_Tip)
EVENT_END

//---------------------UIFlowWndCalLCD_RightTopCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD_RightTop)
CTRL_LIST_END

//----------------------UIFlowWndCalLCD_RightTopCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_RightTop)
EVENT_END

//---------------------UIFlowWndCalLCD_LeftBottomCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD_LeftBottom)
CTRL_LIST_END

//----------------------UIFlowWndCalLCD_LeftBottomCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_LeftBottom)
EVENT_END

//---------------------UIFlowWndCalLCD_LeftTopPointCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD_LeftTopPoint)
CTRL_LIST_END

//----------------------UIFlowWndCalLCD_LeftTopPointCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_LeftTopPoint)
EVENT_END

//---------------------UIFlowWndCalLCD_RightBottomPointCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCalLCD_RightBottomPoint)
CTRL_LIST_END

//----------------------UIFlowWndCalLCD_RightBottomPointCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndCalLCD_RightBottomPoint)
EVENT_END

