//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuSetupSettingRes.c"
#include "UIMenuSetupSetting.h"
//---------------------UIMenuSetupSettingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuSetupSetting)
CTRL_LIST_ITEM(UIMenuSetupSetting_TXT_Title)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_Return)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_CALLCD)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_AutoPWROff)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_Language)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_TVMode)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_HZ)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_AutoLCDOff)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_Format)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_Default)
CTRL_LIST_ITEM(UIMenuSetupSetting_Status_Version)
CTRL_LIST_END

//----------------------UIMenuSetupSettingCtrl Event---------------------------
INT32 UIMenuSetupSetting_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuSetupSetting_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuSetupSetting)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuSetupSetting_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuSetupSetting_OnClose)
EVENT_END

INT32 UIMenuSetupSetting_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuSetupSetting_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuSetupSetting_TXT_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_TXT_Title)
EVENT_END

//----------------------UIMenuSetupSetting_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_Return)
EVENT_END

//----------------------UIMenuSetupSetting_Status_CALLCDCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_CALLCD)
EVENT_END

//----------------------UIMenuSetupSetting_Status_AutoPWROffCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_AutoPWROff)
EVENT_END

//----------------------UIMenuSetupSetting_Status_LanguageCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_Language)
EVENT_END

//----------------------UIMenuSetupSetting_Status_TVModeCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_TVMode)
EVENT_END

//----------------------UIMenuSetupSetting_Status_HZCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_HZ)
EVENT_END

//----------------------UIMenuSetupSetting_Status_AutoLCDOffCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_AutoLCDOff)
EVENT_END

//----------------------UIMenuSetupSetting_Status_FormatCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_Format)
EVENT_END

//----------------------UIMenuSetupSetting_Status_DefaultCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_Default)
EVENT_END

//----------------------UIMenuSetupSetting_Status_VersionCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupSetting_Status_Version)
EVENT_END

