//This source code is generated by UI Designer Studio.

#ifndef UIMENUPHOTOSETTING_H
#define UIMENUPHOTOSETTING_H

#include "UIFramework.h"

extern VControl UIMenuPhotoSettingCtrl;//Panel type 

extern VControl Panel88Ctrl;//Panel type 

extern VControl UIMenuPhotoSetting_TXT_TitleCtrl;//Static type 

extern VControl UIMenuPhotoSetting_Status_ReturnCtrl;//List type 

typedef enum
{
UIMenuPhotoSetting_Status_Return_STRID_RETURN_FORWARD,
UIMenuPhotoSetting_Status_Return_MAX
}UIMenuPhotoSetting_Status_Return_Setting;

extern VControl UIMenuPhotoSetting_Status_SelfTimeCtrl;//List type 

typedef enum
{
UIMenuPhotoSetting_Status_SelfTime_STRID_NULL_,
UIMenuPhotoSetting_Status_SelfTime_MAX
}UIMenuPhotoSetting_Status_SelfTime_Setting;

extern VControl UIMenuPhotoSetting_Status_SizeCtrl;//List type 

typedef enum
{
UIMenuPhotoSetting_Status_Size_STRID_NULL_,
UIMenuPhotoSetting_Status_Size_MAX
}UIMenuPhotoSetting_Status_Size_Setting;

extern VControl UIMenuPhotoSetting_Status_CntShootCtrl;//List type 

typedef enum
{
UIMenuPhotoSetting_Status_CntShoot_STRID_NULL_,
UIMenuPhotoSetting_Status_CntShoot_MAX
}UIMenuPhotoSetting_Status_CntShoot_Setting;

extern VControl UIMenuPhotoSetting_Status_QualityCtrl;//List type 

typedef enum
{
UIMenuPhotoSetting_Status_Quality_STRID_NULL_,
UIMenuPhotoSetting_Status_Quality_MAX
}UIMenuPhotoSetting_Status_Quality_Setting;

extern VControl UIMenuPhotoSetting_Status_SharpCtrl;//List type 

typedef enum
{
UIMenuPhotoSetting_Status_Sharp_STRID_NULL_,
UIMenuPhotoSetting_Status_Sharp_MAX
}UIMenuPhotoSetting_Status_Sharp_Setting;

extern VControl UIMenuPhotoSetting_Status_HandSheakCtrl;//List type 

typedef enum
{
UIMenuPhotoSetting_Status_HandSheak_STRID_NULL_,
UIMenuPhotoSetting_Status_HandSheak_MAX
}UIMenuPhotoSetting_Status_HandSheak_Setting;

extern VControl UIMenuPhotoSetting_Status_EVCtrl;//List type 

typedef enum
{
UIMenuPhotoSetting_Status_EV_STRID_NULL_,
UIMenuPhotoSetting_Status_EV_MAX
}UIMenuPhotoSetting_Status_EV_Setting;

extern VControl UIMenuPhotoSetting_Status_ISOCtrl;//List type 

typedef enum
{
UIMenuPhotoSetting_Status_ISO_STRID_NULL_,
UIMenuPhotoSetting_Status_ISO_MAX
}UIMenuPhotoSetting_Status_ISO_Setting;

extern VControl UIMenuMovieSetting_Status_AWBCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_AWB_STRID_NULL_,
UIMenuMovieSetting_Status_AWB_MAX
}UIMenuMovieSetting_Status_AWB_Setting;

#endif
