//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuMovieSettingRes.c"
#include "UIMenuMovieSetting.h"
//---------------------UIMenuMovieSettingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuMovieSetting)
CTRL_LIST_ITEM(UIMenuMovieSetting_TXT_Title)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_Return)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_Resotion)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_DualRec)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_CycRec)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_TmpRec)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_HDR)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_ParkingMode)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_Gsensor)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_DateStamp)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_MotionDet)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_EV)
CTRL_LIST_END

//----------------------UIMenuMovieSettingCtrl Event---------------------------
INT32 UIMenuMovieSetting_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuMovieSetting_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuMovieSetting)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuMovieSetting_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuMovieSetting_OnClose)
EVENT_END

INT32 UIMenuMovieSetting_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuMovieSetting_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuMovieSetting_TXT_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_TXT_Title)
EVENT_END

//----------------------UIMenuMovieSetting_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_Return)
EVENT_END

//----------------------UIMenuMovieSetting_Status_ResotionCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_Resotion)
EVENT_END

//----------------------UIMenuMovieSetting_Status_DualRecCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_DualRec)
EVENT_END

//----------------------UIMenuMovieSetting_Status_CycRecCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_CycRec)
EVENT_END

//----------------------UIMenuMovieSetting_Status_TmpRecCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_TmpRec)
EVENT_END

//----------------------UIMenuMovieSetting_Status_HDRCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_HDR)
EVENT_END

//----------------------UIMenuMovieSetting_Status_ParkingModeCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_ParkingMode)
EVENT_END

//----------------------UIMenuMovieSetting_Status_GsensorCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_Gsensor)
EVENT_END

//----------------------UIMenuMovieSetting_Status_DateStampCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_DateStamp)
EVENT_END

//----------------------UIMenuMovieSetting_Status_MotionDetCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_MotionDet)
EVENT_END

//----------------------UIMenuMovieSetting_Status_EVCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_EV)
EVENT_END

