//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuRadarSettingRes.c"
#include "UIMenuRadarSetting.h"
//---------------------UIMenuRadarSettingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuRadarSetting)
CTRL_LIST_ITEM(UIMenuRadarSetting_TXT_Title)
CTRL_LIST_ITEM(UIMenuRadarSetting_Status_Return)
CTRL_LIST_ITEM(UIMenuRadarSetting_Status_UserSpeedLimit)
CTRL_LIST_ITEM(UIMenuRadarSetting_Status_CitySpeedLimit)
CTRL_LIST_ITEM(UIMenuRadarSetting_Status_RadarReport)
CTRL_LIST_ITEM(UIMenuRadarSetting_Status_XReport)
CTRL_LIST_ITEM(UIMenuRadarSetting_Status_DrivingMode)
CTRL_LIST_ITEM(UIMenuRadarSetting_Status_SPEED_Correction)
CTRL_LIST_ITEM(UIMenuRadarSetting_Status_EdogOnOff)
CTRL_LIST_END

//----------------------UIMenuRadarSettingCtrl Event---------------------------
INT32 UIMenuRadarSetting_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuRadarSetting_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuRadarSetting)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuRadarSetting_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuRadarSetting_OnClose)
EVENT_END

INT32 UIMenuRadarSetting_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuRadarSetting_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuRadarSetting_TXT_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuRadarSetting_TXT_Title)
EVENT_END

//----------------------UIMenuRadarSetting_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIMenuRadarSetting_Status_Return)
EVENT_END

//----------------------UIMenuRadarSetting_Status_UserSpeedLimitCtrl Event---------------------------
EVENT_BEGIN(UIMenuRadarSetting_Status_UserSpeedLimit)
EVENT_END

//----------------------UIMenuRadarSetting_Status_CitySpeedLimitCtrl Event---------------------------
EVENT_BEGIN(UIMenuRadarSetting_Status_CitySpeedLimit)
EVENT_END

//----------------------UIMenuRadarSetting_Status_RadarReportCtrl Event---------------------------
EVENT_BEGIN(UIMenuRadarSetting_Status_RadarReport)
EVENT_END

//----------------------UIMenuRadarSetting_Status_XReportCtrl Event---------------------------
EVENT_BEGIN(UIMenuRadarSetting_Status_XReport)
EVENT_END

//----------------------UIMenuRadarSetting_Status_DrivingModeCtrl Event---------------------------
EVENT_BEGIN(UIMenuRadarSetting_Status_DrivingMode)
EVENT_END

//----------------------UIMenuRadarSetting_Status_SPEED_CorrectionCtrl Event---------------------------
EVENT_BEGIN(UIMenuRadarSetting_Status_SPEED_Correction)
EVENT_END

//----------------------UIMenuRadarSetting_Status_EdogOnOffCtrl Event---------------------------
EVENT_BEGIN(UIMenuRadarSetting_Status_EdogOnOff)
EVENT_END

