//This source code is generated by UI Designer Studio.

#ifndef UIMENUMOVIESETTING_H
#define UIMENUMOVIESETTING_H

#include "UIFramework.h"

extern VControl UIMenuMovieSettingCtrl;//Panel type 

extern VControl UIMenuMovieSetting_TXT_TitleCtrl;//Static type 

extern VControl UIMenuMovieSetting_Status_ReturnCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_Return_STRID_RETURN_FORWARD,
UIMenuMovieSetting_Status_Return_MAX
}UIMenuMovieSetting_Status_Return_Setting;

extern VControl UIMenuMovieSetting_Status_ResotionCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_Resotion_STRID_NULL_,
UIMenuMovieSetting_Status_Resotion_MAX
}UIMenuMovieSetting_Status_Resotion_Setting;

extern VControl UIMenuMovieSetting_Status_DualRecCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_DualRec_STRID_NULL_,
UIMenuMovieSetting_Status_DualRec_MAX
}UIMenuMovieSetting_Status_DualRec_Setting;

extern VControl UIMenuMovieSetting_Status_CycRecCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_CycRec_STRID_NULL_,
UIMenuMovieSetting_Status_CycRec_MAX
}UIMenuMovieSetting_Status_CycRec_Setting;

extern VControl UIMenuMovieSetting_Status_TmpRecCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_TmpRec_STRID_NULL_,
UIMenuMovieSetting_Status_TmpRec_MAX
}UIMenuMovieSetting_Status_TmpRec_Setting;

extern VControl UIMenuMovieSetting_Status_HDRCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_HDR_STRID_NULL_,
UIMenuMovieSetting_Status_HDR_MAX
}UIMenuMovieSetting_Status_HDR_Setting;

extern VControl UIMenuMovieSetting_Status_ParkingModeCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_ParkingMode_STRID_NULL_,
UIMenuMovieSetting_Status_ParkingMode_MAX
}UIMenuMovieSetting_Status_ParkingMode_Setting;

extern VControl UIMenuMovieSetting_Status_GsensorCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_Gsensor_STRID_NULL_,
UIMenuMovieSetting_Status_Gsensor_MAX
}UIMenuMovieSetting_Status_Gsensor_Setting;

extern VControl UIMenuMovieSetting_Status_DateStampCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_DateStamp_STRID_NULL_,
UIMenuMovieSetting_Status_DateStamp_MAX
}UIMenuMovieSetting_Status_DateStamp_Setting;

extern VControl UIMenuMovieSetting_Status_MotionDetCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_MotionDet_STRID_NULL_,
UIMenuMovieSetting_Status_MotionDet_MAX
}UIMenuMovieSetting_Status_MotionDet_Setting;

extern VControl UIMenuMovieSetting_Status_EVCtrl;//List type 

typedef enum
{
UIMenuMovieSetting_Status_EV_STRID_NULL_,
UIMenuMovieSetting_Status_EV_MAX
}UIMenuMovieSetting_Status_EV_Setting;

#endif
