#ifndef __MENUID_H
#define __MENUID_H

#include "UIResource.h"

// Menu Item ID
enum _MENU_ID
{
    IDM_NULL,

    // Photo Page
    IDM_SELFTIMER,
    IDM_PHOTO_SIZE,
    IDM_CONTINUE_SHOT,
    IDM_QUALITY,
    IDM_SHARPNESS,
    IDM_WB,
    IDM_COLOR_EFFECT,
    IDM_ISO,
    IDM_EV,
    IDM_FD,
    IDM_ANTISHAKE,
    IDM_QUICK_REVIEW,
    IDM_DATE_STAMP,
    IDM_LOW_POWER_TIMELAPSE_REC,
    IDM_TIMELAPSE_REC_MERGEYUV,

    // Movie Page
    IDM_EDOGMODE,
    IDM_EDOGVOLUME,
    IDM_EDOGMUTE,
    IDM_EDOGDRIVEMODE,
    IDM_EDOGSENSITY,
    IDM_EDOGSPEED_LIMIT,
    IDM_EDOGSPEED_ADJUST,
    IDM_EDOGBROADCAST,
    IDM_EDOG_DEFAULT,   
    IDM_EDOG_VERSION,
    IDM_MOVIE_SIZE,
    IDM_MOVIE_SIZE_DUAL,
    IDM_MOVIE_DUAL_REC,
    IDM_MOVIE_CYCLIC_REC,
    IDM_MOVIE_TIMELAPSE_REC,
    IDM_MOVIE_HDR,
    IDM_MOVIE_EV,
    IDM_MOVIE_MOTION_DET,
    IDM_MOVIE_AUDIO,
    IDM_MOVIE_DATEIMPRINT,
    IDM_MOVIE_QUALITY,
    IDM_MOVIE_WB,
    IDM_MOVIE_COLOR,
    IDM_MOVIE_GSENSOR,
    IDM_MOVIE_GPS,
    IDM_MOVIE_PARKING,
    // Playback Page
    IDM_DELETE,
    IDM_PROTECT,
    IDM_ROTATE,
    IDM_SLIDE_SHOW,
    IDM_MAKE_MOVIE,
    IDM_DPOF,

    // Setup Page
    IDM_DATE_TIME,
    IDM_CAR_NUM,
    IDM_AUTO_POWER_OFF,
    IDM_BEEP,
    IDM_SILENT,
    IDM_LANGUAGE,
    IDM_TV_MODE,
    IDM_FREQUENCY,
    IDM_LEDSET,
    IDM_LCDOFF,
    IDM_DELAYOFF,
    IDM_SENSOR_ROTATE,
    IDM_FORMAT,
    IDM_DEFAULT,
    IDM_OPENING_LOGO,
    IDM_PLATENUMBER,
    IDM_VERSION
};

// Menu String ID
enum _MENU_IDS
{
    // Photo Page
    IDS_SELFTIMER           = STRID_CAP_MODE,
    IDS_PHOTO_SIZE          = STRID_RESOLUTION,
    IDS_QUALITY             = STRID_QUALITY,
    IDS_CONTINUE_SHOT       = STRID_CAP_BURST,
    IDS_EV                  = STRID_EXPOSURE,
    IDS_METERING            = STRID_METERING,
    IDS_WB                  = STRID_WB,
    IDS_ISO                 = STRID_ISO,
    IDS_COLOR_EFFECT        = STRID_COLOR,
    IDS_SHARPNESS           = STRID_SHARPNESS,
    IDS_FACE                = STRID_FACE_DET,
    IDS_FD                  = STRID_FACE_DET,
    IDS_ANTISHAKE           = STRID_ANTI_SHAKING,
    IDS_QUICK_REVIEW        = STRID_QUICK_VIEW,
    IDS_DATE_STAMP          = STRID_DATE_STAMP,
    IDS_PHOTO               = STRID_STILL,
    IDS_LOW_POWER_TIMELAPSE_REC         = STRID_TIMELAPSE_CAP,

    // Photo Capture Options
    IDS_SELFTIMER_SINGLE    = STRID_CAP_SINGLE,
    IDS_SELFTIMER_2SEC      = STRID_CAP_TIMER2S,
    IDS_SELFTIMER_5SEC      = STRID_CAP_TIMER5S,
    IDS_SELFTIMER_10SEC     = STRID_CAP_TIMER10S,

    // Photo Size Options
    IDS_PHOTO_SIZE_15M      = STRID_NULL_,
    IDS_PHOTO_SIZE_14M      = STRID_NULL_,
    IDS_PHOTO_SIZE_12M      = STRID_12MWXH,
    IDS_PHOTO_SIZE_10M      = STRID_10MWXH,
    IDS_PHOTO_SIZE_8M       = STRID_8MWXH,
    IDS_PHOTO_SIZE_7M       = STRID_7MWXH,
    IDS_PHOTO_SIZE_7MHD     = STRID_NULL_,
    IDS_PHOTO_SIZE_5M       = STRID_5MWXH,
    IDS_PHOTO_SIZE_4M       = STRID_4MWXH,
    IDS_PHOTO_SIZE_3M       = STRID_3MWXH,
    IDS_PHOTO_SIZE_2M       = STRID_2MWXH,
    IDS_PHOTO_SIZE_2MHD     = STRID_2MHDWXH,
    IDS_PHOTO_SIZE_1M       = STRID_1MWXH,
    IDS_PHOTO_SIZE_VGA      = STRID_VGAWXH,

    //Continue shot
    IDS_CONTINUE_SHOT_OFF      = STRID_OFF,
    IDS_CONTINUE_SHOT_ON      = STRID_ON,

    // Metering Options
    IDS_AVERAGE             = STRID_METER_AVG,
    IDS_CENTER              = STRID_METER_CENTER,
    IDS_SPOT                = STRID_METER_SPOT,

    //ISO
    IDS_ISO_AUTO            = STRID_AUTO,
    IDS_ISO_100             = STRID_ISO100,
    IDS_ISO_200             = STRID_ISO200,
    IDS_ISO_400             = STRID_ISO400,

    // Sharpness Options
    IDS_SHARP_STRONG        = STRID_STRONG,
    IDS_SHARP_NORMAL        = STRID_NORMAL,
    IDS_SHARP_SOFT          = STRID_SOFT,

    // WB Options
    IDS_WB_AUTO             = STRID_AUTO,
    IDS_WB_DAYLIGHT         = STRID_WB_DAY,
    IDS_WB_CLOUDY           = STRID_WB_CLOUDY,
    IDS_WB_TUNGSTEN         = STRID_WB_TUNGSTEN,
    IDS_WB_FLUORESCENT      = STRID_WB_FLUORESCENT,

    // Color Effect Options
    IDS_COLOR_EFFECT_STANDARD     = STRID_COLOR,
    IDS_COLOR_EFFECT_MONOCHROME   = STRID_COLOR_BW,
    IDS_COLOR_EFFECT_SEPIA        = STRID_COLOR_SEPIA,

    // EV Options
    IDS_EV_P20              = STRID_EV_P2P0,
    IDS_EV_P16              = STRID_EV_P1P6,
    IDS_EV_P13              = STRID_EV_P1P3,
    IDS_EV_P10              = STRID_EV_P1P0,
    IDS_EV_P06              = STRID_EV_P0P6,
    IDS_EV_P03              = STRID_EV_P0P3,
    IDS_EV_00               = STRID_EV_P0P0,
    IDS_EV_N03              = STRID_EV_M0P3,
    IDS_EV_N06              = STRID_EV_M0P6,
    IDS_EV_N10              = STRID_EV_M1P0,
    IDS_EV_N13              = STRID_EV_M1P3,
    IDS_EV_N16              = STRID_EV_M1P6,
    IDS_EV_N20              = STRID_EV_M2P0,

    // Face Detection Options
    IDS_FD_OFF              = STRID_OFF,
    IDS_FD_ON               = STRID_FACE_DET,
    IDS_FD_SMILE            = STRID_SMILE_DET,

    // Anti-shaking Options
    IDS_ANTISHAKE_OFF       = STRID_OFF,
    IDS_ANTISHAKE_ON        = STRID_ON,

    // Quick View Time Options
    IDS_QV_OFF              = STRID_OFF,
    IDS_QV_2SEC             = STRID_2SEC,
    IDS_QV_5SEC             = STRID_5SEC,

    // Date Stamp Options
    IDS_DATE_STAMP_OFF      = STRID_OFF,
    IDS_DATE_STAMP_DATE     = STRID_DATE,
    IDS_DATE_STAMP_DATETIME = STRID_DATE_TIME,

    // Time-lapse Capture Options
    IDS_LOW_POWER_TIMELAPSE_REC_OFF     = STRID_OFF,
    IDS_LOW_POWER_TIMELAPSE_REC_5SEC    = STRID_5SEC,
    IDS_LOW_POWER_TIMELAPSE_REC_10SEC   = STRID_10SEC,
    IDS_LOW_POWER_TIMELAPSE_REC_1MIN    = STRID_1MIN,
    IDS_LOW_POWER_TIMELAPSE_REC_5MIN    = STRID_5MIN,
    IDS_LOW_POWER_TIMELAPSE_REC_10MIN   = STRID_10MIN,
    IDS_LOW_POWER_TIMELAPSE_REC_30MIN   = STRID_30MIN,
    IDS_LOW_POWER_TIMELAPSE_REC_60MIN   = STRID_60MIN,
    IDS_TIMELAPSE_REC_MERGEYUV          = STRID_MEDIA,

    // Movie Page    
    IDS_MOVIE_SIZE          = STRID_RESOLUTION,
    IDS_MOVIE_SIZE_DUAL     = STRID_RESOLUTION,
    IDS_MOVIE_EV            = STRID_EXPOSURE,
    IDS_MOVIE_DUAL_REC      = STRID_DUAL_REC,
    IDS_MOVIE_CYCLIC_REC    = STRID_CYCLIC_REC,
    IDS_MOVIE_TIMELAPSE_REC = STRID_TIMELAPSE_REC,
    IDS_MOVIE_HDR           = STRID_HDR,
    IDS_MOVIE_MOTION_DET    = STRID_MOTION_DET,
    IDS_MOVIE_AUDIO         = STRID_RECORD_AUDIO,
    IDS_MOVIE_DATEIMPRINT   = STRID_DATE_STAMP,
    IDS_MOVIE_QUALITY       = STRID_QUALITY,
    IDS_MOVIE_WB            = STRID_WB,
    IDS_MOVIE_COLOR         = STRID_COLOR,
    IDS_MOVIE               = STRID_MOVIE,
    IDS_MOVIE_GSENSOR       = STRID_GSENSOR,
    IDS_MOVIE_GPS           = STRID_GPS,
    IDS_MOVIE_PARKING = STRID_PARKING_MONITOR,
//Edog 
    IDS_EDOGMODE =STRID_RADAR_ONOFF,
    IDS_EDOGVOLUME=STRID_RADAR_VOLUME,
    IDS_EDOGMUTE=STRID_RADAR_MUTE,
    IDS_EDOGDRIVEMODE=STRID_RADAR_MODE,
    IDS_EDOGSENSITY=STRID_RADAR_SENSITIVITY,
    IDS_EDOGSPEED_LIMIT=STRID_SPEED_LIMIT,
    IDS_EDOGSPEED_ADJUST=STRID_SPEED_ADJUSTMENT,
    IDS_EDOGBROADCAST=STRID_BROADCAST,
    IDS_EDOG_DEFAULT=STRID_RADAR_DEFAULT,
    IDS_EDOG_VERSION=STRID_EDOG_VERSION,
    //Edog menu options
    IDS_EDOGMODE_OFF = STRID_OFF,
    IDS_EDOGMODE_ON = STRID_ON,    

    IDS_EDOGVOLUME_LOWEST = STRID_VOLUME_LOWEST,
    IDS_EDOGVOLUME_MED = STRID_VOLUME_MED,
    IDS_EDOGVOLUME_HIGHER = STRID_VOLUME_HIGH,
    IDS_EDOGVOLUME_HIGHEST = STRID_VOLUME_HIGHEST,
    
    IDS_EDOGMUTE_OFF=STRID_MUTE_0,
    IDS_EDOGMUTE_20= STRID_MUTE_20,
    IDS_EDOGMUTE_30=STRID_MUTE_30,
    IDS_EDOGMUTE_40=STRID_MUTE_40,
    IDS_EDOGMUTE_50=STRID_MUTE_50,
    IDS_EDOGMUTE_60=STRID_MUTE_60,
    IDS_EDOGMUTE_70=STRID_MUTE_70,
    IDS_EDOGMUTE_80=STRID_MUTE_80,
    IDS_EDOGMUTE_90=STRID_MUTE_90,
    IDS_EDOGMUTE_100=STRID_MUTE_100,
    IDS_EDOGMUTE_110=STRID_MUTE_110,
    IDS_EDOGMUTE_120=STRID_MUTE_120,      

    IDS_EDOGDRIVEMODE_CAPTURE=STRID_RADAR_MODE_CAPTURE,
    IDS_EDOGDRIVEMODE_SAFETY=STRID_RADAR_MODE_SAFETY,

    IDS_EDOGSENSITY_OFF=STRID_RADAR_SENSITIVITY_OFF,
    IDS_EDOGSENSITY_MED=STRID_RADAR_SENSITIVITY_MED,
    IDS_EDOGSENSITY_HIGH=STRID_RADAR_SENSITIVITY_HIGH,
    IDS_EDOGSENSITY_AUTO=STRID_RADAR_SENSITIVITY_AUTO,

    IDS_EDOGSPEED_LIMIT0=STRID_SPEED_LIMIT_OFF,
    IDS_EDOGSPEED_LIMIT40=STRID_SPEED_LIMIT_40,
    IDS_EDOGSPEED_LIMIT50=STRID_SPEED_LIMIT_50,
    IDS_EDOGSPEED_LIMIT60=STRID_SPEED_LIMIT_60,
    IDS_EDOGSPEED_LIMIT70=STRID_SPEED_LIMIT_70,
    IDS_EDOGSPEED_LIMIT80=STRID_SPEED_LIMIT_80,
    IDS_EDOGSPEED_LIMIT90=STRID_SPEED_LIMIT_90, 
    IDS_EDOGSPEED_LIMIT100=STRID_SPEED_LIMIT_100,
    IDS_EDOGSPEED_LIMIT110=STRID_SPEED_LIMIT_110,
    IDS_EDOGSPEED_LIMIT120=STRID_SPEED_LIMIT_120,
    IDS_EDOGSPEED_LIMIT130=STRID_SPEED_LIMIT_130,
    IDS_EDOGSPEED_LIMIT140=STRID_SPEED_LIMIT_140,
    IDS_EDOGSPEED_LIMIT150=STRID_SPEED_LIMIT_150,     
    IDS_EDOGSPEED_LIMIT160=STRID_SPEED_LIMIT_160,   

    IDS_EDOGSPEED_ADJUST_N10=STRID_NUM_N10,
    IDS_EDOGSPEED_ADJUST_N9=STRID_NUM_N9,
    IDS_EDOGSPEED_ADJUST_N8=STRID_NUM_N8,
    IDS_EDOGSPEED_ADJUST_N7=STRID_NUM_N7,
    IDS_EDOGSPEED_ADJUST_N6=STRID_NUM_N6,
    IDS_EDOGSPEED_ADJUST_N5=STRID_NUM_N5,
    IDS_EDOGSPEED_ADJUST_N4=STRID_NUM_N4,
    IDS_EDOGSPEED_ADJUST_N3=STRID_NUM_N3,
    IDS_EDOGSPEED_ADJUST_N2=STRID_NUM_N2,
    IDS_EDOGSPEED_ADJUST_N1=STRID_NUM_N1,
    IDS_EDOGSPEED_ADJUST_0=STRID_NUM_0,
    IDS_EDOGSPEED_ADJUST_P1=STRID_NUM_P1,
    IDS_EDOGSPEED_ADJUST_P2=STRID_NUM_P2,
    IDS_EDOGSPEED_ADJUST_P3=STRID_NUM_P3,
    IDS_EDOGSPEED_ADJUST_P4=STRID_NUM_P4,
    IDS_EDOGSPEED_ADJUST_P5=STRID_NUM_P5,
    IDS_EDOGSPEED_ADJUST_P6=STRID_NUM_P6,
    IDS_EDOGSPEED_ADJUST_P7=STRID_NUM_P7,
    IDS_EDOGSPEED_ADJUST_P8=STRID_NUM_P8,
    IDS_EDOGSPEED_ADJUST_P9=STRID_NUM_P9,
    IDS_EDOGSPEED_ADJUST_P10=STRID_NUM_P10,  

    IDS_EDOGBROADCAST_CONCISION=STRID_BROADCAST_COMPACTLY,
    IDS_EDOGBROADCAST_COMPLETE=STRID_BROADCAST_COMPLETE,
    
    //
    // Movie Size Options
    IDS_MOVIE_SIZE_1080FHD  = STRID_1080FHDWXH,
    IDS_MOVIE_SIZE_1080P    = STRID_1080PWXH,
    IDS_MOVIE_SIZE_720P     = STRID_720PWXH,
    IDS_MOVIE_SIZE_WVGA     = STRID_WVGAWXH,
    IDS_MOVIE_SIZE_VGA      = STRID_VGAWXH,
    IDS_MOVIE_SIZE_QVGA     = STRID_QVGAWXH,

    // Movie Size Dual Options
    IDS_MOVIE_SIZE_1080P_720P   = STRID_1080PWXH,
    IDS_MOVIE_SIZE_720P_720P    = STRID_720PWXH,

    // EV Options
    IDS_MOVIE_EV_P20        = STRID_EV_P2P0,
    IDS_MOVIE_EV_P16        = STRID_EV_P1P6,
    IDS_MOVIE_EV_P13        = STRID_EV_P1P3,
    IDS_MOVIE_EV_P10        = STRID_EV_P1P0,
    IDS_MOVIE_EV_P06        = STRID_EV_P0P6,
    IDS_MOVIE_EV_P03        = STRID_EV_P0P3,
    IDS_MOVIE_EV_00         = STRID_EV_P0P0,
    IDS_MOVIE_EV_N03        = STRID_EV_M0P3,
    IDS_MOVIE_EV_N06        = STRID_EV_M0P6,
    IDS_MOVIE_EV_N10        = STRID_EV_M1P0,
    IDS_MOVIE_EV_N13        = STRID_EV_M1P3,
    IDS_MOVIE_EV_N16        = STRID_EV_M1P6,
    IDS_MOVIE_EV_N20        = STRID_EV_M2P0,

    // Movie Dual Recording Options
    IDS_MOVIE_DUAL_REC_OFF  = STRID_OFF,
    IDS_MOVIE_DUAL_REC_ON   = STRID_ON,

    // Movie loop rec Options
    IDS_MOVIE_CYCLIC_REC_OFF    = STRID_OFF,
    IDS_MOVIE_CYCLIC_REC_3MIN   = STRID_3MIN,
    IDS_MOVIE_CYCLIC_REC_5MIN   = STRID_5MIN,
    IDS_MOVIE_CYCLIC_REC_10MIN  = STRID_10MIN,

    // Movie time lapse rec Options
    IDS_MOVIE_TIMELAPSE_REC_OFF    = STRID_OFF,
    IDS_MOVIE_TIMELAPSE_REC_100MS  = STRID_100MS,
    IDS_MOVIE_TIMELAPSE_REC_200MS  = STRID_200MS,
    IDS_MOVIE_TIMELAPSE_REC_500MS  = STRID_500MS,
    // Movie motion detect Options
    IDS_MOVIE_MOTION_DET_OFF  = STRID_OFF,
    IDS_MOVIE_MOTION_DET_ON   = STRID_ON,

    // Movie HDR options
    IDS_MOVIE_HDR_OFF  = STRID_OFF,
    IDS_MOVIE_HDR_ON   = STRID_ON,

    // Movie audio Options
    IDS_MOVIE_AUDIO_OFF     = STRID_OFF,
    IDS_MOVIE_AUDIO_ON      = STRID_ON,

    // Movie dateImprint Options
    IDS_MOVIE_DATEIMPRINT_OFF = STRID_OFF,
    IDS_MOVIE_DATEIMPRINT_ON  = STRID_ON,

    // Movie G-sensor Options
    IDS_MOVIE_GSENSOR_OFF         = STRID_OFF,
    IDS_MOVIE_GSENSOR_LOW         = STRID_GSENSOR_LOW,
    IDS_MOVIE_GSENSOR_MED         = STRID_GSENSOR_MIDDLE,
    IDS_MOVIE_GSENSOR_HIGH        = STRID_GSENSOR_HIGH,

    // Movie Quality Options
    IDS_QUALITY_FINE        = STRID_FINE,
    IDS_QUALITY_NORMAL      = STRID_NORMAL,
    IDS_QUALITY_ECONOMY     = STRID_ECONOMY,

    // Playback Page
    IDS_DELETE              = STRID_DELETE,
    IDS_PROTECT             = STRID_PROTECT,
    IDS_SLIDE_SHOW          = STRID_SLIDE_SHOW,
    IDS_MAKE_MOVIE          = STRID_MAKE_MOVIE,
    IDS_ROTATE              = STRID_ROTATE,
    IDS_DPOF                = STRID_DPOF,
    IDS_PLAYBACK            = STRID_PLAYBACK,

    // Protect Options
    IDS_PROTECT_ONE         = STRID_LOCKONE,
    IDS_UNPROTECT_ONE       = STRID_UNLOCKONE,
    IDS_PROTECT_ALL         = STRID_LOCKALL,
    IDS_UNPROTECT_ALL       = STRID_UNLOCKALL,

    // Rotate Options
    IDS_ROTATE_90           = STRID_ROTATE_90,
    IDS_ROTATE_180          = STRID_ROTATE_180,
    IDS_ROTATE_270          = STRID_ROTATE_270,

    // Slide Show Options
    IDS_SLIDE_SHOW_2SEC     = STRID_2SEC,
    IDS_SLIDE_SHOW_5SEC     = STRID_5SEC,
    IDS_SLIDE_SHOW_8SEC     = STRID_8SEC,

    // Make Movie Options
    IDS_MAKE_MOVIE_NO       = STRID_NO,
    IDS_MAKE_MOVIE_YES      = STRID_YES,
    
    // Setup Page
    IDS_DATE_TIME           = STRID_DATE_TIME,
    IDS_CAR_NUM          = STRID_CAR_NUM,
    IDS_AUTO_POWER_OFF      = STRID_AUTO_OFF,
    IDS_BEEP                = STRID_BEEPER,
    IDS_SILENT              = STRID_BEEPER,
    IDS_LANGUAGE            = STRID_LANGUAGE,
    IDS_TV_MODE             = STRID_TV_MODE,
    IDS_FREQUENCY           = STRID_FREQUENCY,
    IDS_LEDSET               = STRID_LED_SETTING,
    IDS_LCDOFF            = STRID_LCDOFF,
    IDS_DELAYOFF         =STRID_DELAYOFF,
    IDS_SENSOR_ROTATE       = STRID_SENSOR_ROTATE,
    IDS_FORMAT              = STRID_FORMAT,
    IDS_DEFAULT             = STRID_DEFAULT_SETTING,
    IDS_OPENING_LOGO        = STRID_LOGO_DISPLAY,
    IDS_PLATENUMBER         = STRID_CAR_NUM,
    IDS_VERSION             = STRID_VERSION,
    IDS_SETUP               = STRID_SETUP,

    // Power Saving Options
    IDS_OFF                 = STRID_OFF,
    IDS_1MIN                = STRID_AUTO_OFF_1MIN,
    IDS_3MIN                = STRID_AUTO_OFF_3MIN,
    IDS_5MIN                = STRID_AUTO_OFF_5MIN,
    IDS_10MIN               = STRID_AUTO_OFF_10MIN,

    // Beep Options
    IDS_SILENT_ON            = STRID_OFF,
    IDS_SILENT_OFF           = STRID_ON,

    IDS_BEEP_OFF            = STRID_OFF,
    IDS_BEEP_ON             = STRID_ON,

    // Language Options
    IDS_LANG_EN             = STRID_LANG_EN,
    IDS_LANG_DE             = STRID_LANG_DE,
    IDS_LANG_FR             = STRID_LANG_FR,
    IDS_LANG_ES             = STRID_LANG_ES,
    IDS_LANG_IT             = STRID_LANG_IT,
    IDS_LANG_PO             = STRID_LANG_PO,
    IDS_LANG_SC             = STRID_LANG_SC,
    IDS_LANG_TC             = STRID_LANG_TC,
    IDS_LANG_JP             = STRID_LANG_JP,
    IDS_LANG_RU             = STRID_LANG_RU,
    IDS_LANG_DU             = STRID_NULL_,
    IDS_LANG_TU             = STRID_NULL_,
    IDS_LANG_PB             = STRID_NULL_,
    IDS_LANG_YI             = STRID_NULL_,
    IDS_LANG_PL             = STRID_NULL_,


    // TV Mode Options
    IDS_TV_NTSC             = STRID_TV_NTSC,
    IDS_TV_PAL              = STRID_TV_PAL,

    // Frequency Options
    IDS_50HZ                = STRID_50HZ,
    IDS_60HZ                = STRID_60HZ,

    // Sensor Rotate Options
    IDS_SENSOR_ROTATE_OFF   = STRID_OFF,
    IDS_SENSOR_ROTATE_ON    = STRID_ON,

    // CAR number
    IDS_CAR_NUM_OFF   = STRID_OFF,
    IDS_CAR_NUM_ON    = STRID_ON,
    
    // LED Setting  Options
    IDS_LEDSET_OFF   = STRID_IRLED_OFF,
    IDS_LEDSET_ON    = STRID_IRLED_ON,
    IDS_LEDSET_WARNING    = STRID_IRLED_WARNING,

    // LCD Setting  Options
    IDS_LCDOFF_OFF          = STRID_OFF,
    IDS_LCDOFF_30SEC        = STRID_30SEC,
    IDS_LCDOFF_1MIN         = STRID_1MIN,
    IDS_LCDOFF_2MIN         = STRID_2MIN,
    
    // Opening Delay Off Options
    IDS_DELAYOFF_OFF        = STRID_OFF,
    IDS_DELAYOFF_10SEC       = STRID_10SEC,
    IDS_DELAYOFF_20SEC       = STRID_20SEC,    
    IDS_DELAYOFF_30SEC       = STRID_30SEC,

    // Opening GPS Options
    IDS_MOVIE_GPS_OFF       = STRID_OFF,
    IDS_MOVIE_GPS_ON        = STRID_ON,

    IDS_MOVIE_PARKING_OFF=STRID_OFF,
    IDS_MOVIE_PARKING_ON=STRID_ON,

    // Opening Logo Display Options
    IDS_LOGO_OFF            = STRID_OFF,
    IDS_LOGO_ON             = STRID_ON
};

// Menu Icon ID
enum _MENU_IDI
{
    // Photo Page
    IDI_SELFTIMER           = ICON_OK,
    IDI_PHOTO_SIZE          = ICON_OK,
    IDI_QUALITY             = ICON_OK,
    IDI_CONTINUE_SHOT       = ICON_OK,
    IDI_EV                  = ICON_OK,
    IDI_METERING            = ICON_OK,
    IDI_WB                  = ICON_OK,
    IDI_ISO                 = ICON_OK,
    IDI_COLOR_EFFECT        = ICON_OK,
    IDI_SHARPNESS           = ICON_OK,
    IDI_FD                  = ICON_OK,
    IDI_ANTISHAKE           = ICON_OK,
    IDI_QUICK_REVIEW        = ICON_OK,
    IDI_DATE_STAMP          = ICON_OK,
    IDI_PHOTO               = ICON_OK,       // Photo menu enable icon
    IDIX_PHOTO              = ICON_OK,      // Photo menu disable icon
    IDI_LOW_POWER_TIMELAPSE_REC     = ICON_OK,
    IDI_TIMELAPSE_REC_MERGEYUV      = ICON_OK,
    IDI_AUTO_UPDATE_TIME	= ICON_OK,
    // Movie size options
    IDI_MOVIE_SIZE_1080FHD  = ICON_OK,
    IDI_MOVIE_SIZE_1080P    = ICON_OK,
    IDI_MOVIE_SIZE_720P     = ICON_OK,
    IDI_MOVIE_SIZE_WVGA     = ICON_OK,
    IDI_MOVIE_SIZE_VGA      = ICON_OK,
    IDI_MOVIE_SIZE_QVGA     = ICON_OK,

    // Movie size dual options
    IDI_MOVIE_SIZE_1080P_720P   = ICON_OK,
    IDI_MOVIE_SIZE_720P_720P    = ICON_OK,

    // Photo Size Options
    IDI_PHOTO_SIZE_15M      = ICON_OK,
    IDI_PHOTO_SIZE_14M      = ICON_OK,
    IDI_PHOTO_SIZE_12M      = ICON_OK,
    IDI_PHOTO_SIZE_10M      = ICON_OK,
    IDI_PHOTO_SIZE_8M       = ICON_OK,
    IDI_PHOTO_SIZE_7M       = ICON_OK,
    IDI_PHOTO_SIZE_7MHD     = ICON_OK,
    IDI_PHOTO_SIZE_5M       = ICON_OK,
    IDI_PHOTO_SIZE_4M       = ICON_OK,
    IDI_PHOTO_SIZE_3M       = ICON_OK,
    IDI_PHOTO_SIZE_2M       = ICON_OK,
    IDI_PHOTO_SIZE_1M       = ICON_OK,
    IDI_PHOTO_SIZE_2MHD     = ICON_OK,
    IDI_PHOTO_SIZE_VGA      = ICON_OK,

    // Movie Page
    IDI_MOVIE_SIZE          = ICON_OK,
    IDI_MOVIE_SIZE_DUAL     = ICON_OK,
    IDI_MOVIE_EV            = ICON_OK,
    IDI_MOVIE_DUAL_REC      = ICON_OK,
    IDI_MOVIE_CYCLIC_REC    = ICON_OK,
    IDI_MOVIE_TIMELAPSE_REC = ICON_OK,
    IDI_MOVIE_HDR           = ICON_OK,
    IDI_MOVIE_MOTION_DET    = ICON_OK,
    IDI_MOVIE_AUDIO         = ICON_OK,
    IDI_MOVIE_DATEIMPRINT   = ICON_OK,
    IDI_MOVIE_QUALITY       = ICON_OK,
    IDI_MOVIE_WB            = ICON_OK,
    IDI_MOVIE_COLOR         = ICON_OK,

    IDI_MOVIE               = ICON_OK,       // Movie menu enable icon
    IDI_MOVIE_GPS           = ICON_OK,
    IDI_MOVIE_PARKING = ICON_OK,
    IDIX_MOVIE              = ICON_OK,      // Movie menu disable icon
    IDI_MOVIE_GSENSOR       = ICON_OK,
    // Playback Page
    IDI_DELETE              = ICON_OK,
    IDI_PROTECT             = ICON_OK,
    IDI_SLIDE_SHOW          = ICON_OK,
    IDI_MAKE_MOVIE          = ICON_OK,
    IDI_ROTATE              = ICON_OK,
    IDI_DPOF                = ICON_OK,
    IDI_PLAYBACK            = ICON_OK,    // Playback menu enable icon
    IDIX_PLAYBACK           = ICON_OK,   // Playback menu disable icon

    // Setup Page
    IDI_DATE_TIME           = ICON_OK,
    IDI_CAR_NUM       =ICON_OK,
    IDI_AUTO_POWER_OFF      = ICON_OK,
    IDI_SILENT              = ICON_OK,
    IDI_BEEP                = ICON_OK,
    IDI_LANGUAGE            = ICON_OK,
    IDI_FREQUENCY           = ICON_OK,
    IDI_TV_MODE             = ICON_OK,
    IDI_TV                        = ICON_OK,
    IDI_LEDSET              = ICON_OK,
    IDI_LCDOFF              = ICON_OK,
    IDI_DELAYOFF          = ICON_OK,
    IDI_SENSOR_ROTATE       = ICON_OK,
    IDI_FORMAT              = ICON_OK,
    IDI_DEFAULT             = ICON_OK,
//    IDI_OPENING_LOGO        = ICON_LOGO_DISPLAY,
    IDI_PLATENUMBER      = ICON_OK,
    IDI_VERSION             = ICON_OK,
    IDI_SETUP               = ICON_OK,       // Setup menu enable icon
    IDIX_SETUP              = ICON_OK,       // Setup menu disable icon

    // Language Options
    IDI_LANG_EN             = ICON_OK,
    IDI_LANG_FR             = ICON_OK,
    IDI_LANG_ES             = ICON_OK,
    IDI_LANG_PO             = ICON_OK,
    IDI_LANG_DE             = ICON_OK,
    IDI_LANG_DU             = ICON_OK,
    IDI_LANG_IT             = ICON_OK,
    IDI_LANG_RU             = ICON_OK,
    IDI_LANG_TU             = ICON_OK,
    IDI_LANG_JP             = ICON_OK,
    IDI_LANG_TC             = ICON_OK,
    IDI_LANG_SC             = ICON_OK,
    IDI_LANG_PB             = ICON_OK,
    IDI_LANG_YI             = ICON_OK,
    IDI_LANG_PL             = ICON_OK,
IDI_LOGO_ON             = ICON_ABC
};

#endif // __MENUID_H

