//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuMovieSettingRes.c"
#include "UIMenuMovieSetting.h"




typedef enum
{
	UIFLOW_MovieSetting_TOUCH_KEY_NONE,
	UIFLOW_MovieSetting_TOUCH_KEY_SHU,				
	UIFLOW_MovieSetting_TOUCH_KEY_HOME,	
	UIFLOW_MovieSetting_TOUCH_KEY_RETURN,	
	UIFLOW_MovieSetting_TOUCH_KEY_MAX	
}UIFLOW_MovieSetting_TOUCH_KEY;
//---------------------UIMenuMovieSettingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuMovieSetting)
CTRL_LIST_ITEM(UIMenuMovieSetting_TXT_Title)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_Return)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_Resotion)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_DualRec)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_CycRec)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_TmpRec)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_HDR)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_ParkingMode)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_Gsensor)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_DateStamp)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_MotionDet)
CTRL_LIST_ITEM(UIMenuMovieSetting_Status_EV)
CTRL_LIST_END



//----------------------UIMenuMovieSettingCtrl Event---------------------------
INT32 UIMenuMovieSetting_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuMovieSetting_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuMovieSetting_TP(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuMovieSetting)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuMovieSetting_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuMovieSetting_OnClose)
EVENT_ITEM(NVTEVT_KEY_TP,UIMenuMovieSetting_TP)
EVENT_END




static UIFLOW_MovieSetting_TOUCH_KEY uiMovieSettingPressed=UIFLOW_MovieSetting_TOUCH_KEY_NONE;


INT32 UIMenuMovieSetting_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuMovieSetting_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuMovieSetting_TP(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
  UINT32 uiEvent;
    UINT32 P1,P2;
    UINT32  uiSoundMask;
  
    if(paramNum>0)
        uiEvent = paramArray[0];	
	
	switch(uiEvent)
	{
		case GESTURE_DOWN2UP://GESTURE_RIGHT2LEFT:
		   
		break;			
		
		case GESTURE_UP2DOWN://GESTURE_LEFT2RIGHT:
		    		
		break;	
 
		case GESTURE_PRESSONLY:
			P1= paramArray[1];
			P2=paramArray[2];  
		    if(TPIsOnRange(&UIMenuMovieSetting_Status_ReturnCtrl,P1,P2)==TRUE)
		    	{
		    	       uiMovieSettingPressed=UIFLOW_MovieSetting_TOUCH_KEY_RETURN;
		       	//Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);	
		    	}		
                    
		   	
		break;

		case GESTURE_RELEASE:
			P1= paramArray[1];
			P2=paramArray[2];  
	            //debug_msg("^G movie GESTURE_RELEASE\r\n");
		    if(TPIsOnRange(&UIMenuMovieSetting_Status_ReturnCtrl,P1,P2)==TRUE)
		    	{
		    	       if(uiMovieSettingPressed==UIFLOW_MovieSetting_TOUCH_KEY_RETURN)
		    	       {
			       	
                                 
							Ux_CloseWindow((VControl *)(&UIMenuMovieSettingCtrl), 0);
					
		    	       }
								   
		    	}	
           else
			    {
			    
			    }
		   
				
		    uiMovieSettingPressed=UIFLOW_MovieSetting_TOUCH_KEY_NONE;
		
		break;
	}	  
	

	  
	return NVTEVT_CONSUME;
}
//----------------------UIMenuMovieSetting_TXT_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_TXT_Title)
EVENT_END

//----------------------UIMenuMovieSetting_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_Return)
EVENT_END

//----------------------UIMenuMovieSetting_Status_ResotionCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_Resotion)
EVENT_END

//----------------------UIMenuMovieSetting_Status_DualRecCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_DualRec)
EVENT_END

//----------------------UIMenuMovieSetting_Status_CycRecCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_CycRec)
EVENT_END

//----------------------UIMenuMovieSetting_Status_TmpRecCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_TmpRec)
EVENT_END

//----------------------UIMenuMovieSetting_Status_HDRCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_HDR)
EVENT_END

//----------------------UIMenuMovieSetting_Status_ParkingModeCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_ParkingMode)
EVENT_END

//----------------------UIMenuMovieSetting_Status_GsensorCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_Gsensor)
EVENT_END

//----------------------UIMenuMovieSetting_Status_DateStampCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_DateStamp)
EVENT_END

//----------------------UIMenuMovieSetting_Status_MotionDetCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_MotionDet)
EVENT_END

//----------------------UIMenuMovieSetting_Status_EVCtrl Event---------------------------
EVENT_BEGIN(UIMenuMovieSetting_Status_EV)
EVENT_END

