//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndEdogDefaultRes.c"
#include "UIMenuWndEdogDefault.h"
#include "PrjCfg.h"
#include "UIInfo.h"

//---------------------UIMenuWndEdogDefaultCtrl Debug Definition -----------------------------
#define _UIMENUWNDEDOGDEFAULT_ERROR_MSG        1
#define _UIMENUWNDEDOGDEFAULT_TRACE_MSG        0

#if (_UIMENUWNDEDOGDEFAULT_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndEdogDefaultErrMsg(...)            debug_msg ("^R UIMenuWndEdogDefault: "__VA_ARGS__)
#else
#define UIMenuWndEdogDefaultErrMsg(...)
#endif

#if (_UIMENUWNDEDOGDEFAULT_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndEdogDefaultTraceMsg(...)          debug_msg ("^B UIMenuWndEdogDefault: "__VA_ARGS__)
#else
#define UIMenuWndEdogDefaultTraceMsg(...)
#endif

extern BOOL gbGetEdogFWVersion;

//---------------------UIMenuWndEdogDefaultCtrl Global Variables -----------------------------

//---------------------UIMenuWndEdogDefaultCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndEdogDefaultCtrl Public API  ----------------------------------

//---------------------UIMenuWndEdogDefaultCtrl Private API  ---------------------------------
//---------------------UIMenuWndEdogDefaultCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndEdogDefault)
CTRL_LIST_ITEM(UIMenuWndEdogDefaultSetting_List_Text)
CTRL_LIST_ITEM(UIMenuWndEdogDefaultSetting_Static_Text)
CTRL_LIST_ITEM(UIMenuWndEdogDefaultSetting_Static_Text_Version)
CTRL_LIST_END

//----------------------UIMenuWndEdogDefaultCtrl Event---------------------------
INT32 UIMenuWndEdogDefault_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogDefault_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogDefault_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogDefault_OnKeyMode(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndEdogDefault)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndEdogDefault_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndEdogDefault_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndEdogDefault_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndEdogDefault_OnKeyMode)
EVENT_END

INT32 UIMenuWndEdogDefault_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxCtrl_SetShow(&UIMenuWndEdogDefaultSetting_Static_Text_VersionCtrl, FALSE);    
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogDefault_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogDefault_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndEdogDefaultCtrl,0); // close whole tab menu
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogDefault_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndEdogDefaultCtrl,0); // close whole tab menu
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndEdogDefaultSetting_List_TextCtrl Event---------------------------
INT32 UIMenuWndEdogDefaultSetting_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogDefaultSetting_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogDefaultSetting_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndEdogDefaultSetting_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndEdogDefaultSetting_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndEdogDefaultSetting_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndEdogDefaultSetting_List_Text_OnKeyEnter)
EVENT_END

INT32 UIMenuWndEdogDefaultSetting_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogDefaultSetting_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogDefaultSetting_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 ui32CurrListItem;

    ui32CurrListItem = UxList_GetData(pCtrl, LST_CURITM);
    switch (ui32CurrListItem)
    {
    case 0:  //cancel
        break;
    case 1:  //OK
        debug_err(("Reset default setting\n\r"));
        gbGetEdogFWVersion=FALSE;		
   	 EdgoRec_PutKeyCommand(MENU_DEFAULTSETTING,0x00);	        
	 break;
    default:
        debug_err(("No any is selected for default setting\n\r"));
        break;
    }
    Ux_CloseWindow(&UIMenuWndEdogDefaultCtrl, 0);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndEdogDefaultSetting_Static_TextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndEdogDefaultSetting_Static_Text)
EVENT_END

//----------------------UIMenuWndEdogDefaultSetting_Static_Text_VersionCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndEdogDefaultSetting_Static_Text_Version)
EVENT_END

