//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIWndNotUseRes.c"
#include "UIWndNotUse.h"
#include "UIFlow.h"
//---------------------UIWndNotUseCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIWndNotUse)
CTRL_LIST_END

//----------------------UIWndNotUseCtrl Event---------------------------
INT32 UIWndNotUse_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIWndNotUse_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIWndNotUse_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIWndNotUse)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIWndNotUse_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIWndNotUse_OnClose)
EVENT_ITEM(NVTEVT_TIMER,UIWndNotUse_OnTimer)
EVENT_END
static UINT32  gUIMotionDetTimerID = NULL_TIMER;
INT32 UIWndNotUse_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
if (gUIMotionDetTimerID==NULL_TIMER)
        {
            gUIMotionDetTimerID = GxTimer_StartTimer(10, NVTEVT_05SEC_TIMER, CONTINUE);
        }
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIWndNotUse_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
if (gUIMotionDetTimerID!=NULL_TIMER)
    {
        GxTimer_StopTimer(&gUIMotionDetTimerID);
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIWndNotUse_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32  uiEvent;
    static  UINT32 counter;
	static BOOL  test = FALSE;
    uiEvent = paramNum ? paramArray[0] : 0;

    switch(uiEvent)
    {
    case NVTEVT_05SEC_TIMER:
       Ux_CloseWindowClear(&UIWndNotUseCtrl,0);	
    break;
            }
    return NVTEVT_CONSUME;
}

