//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDHOME_H
#define UIFLOWWNDHOME_H

#include "UIFramework.h"

extern VControl UIFlowWndHomeCtrl;//Panel type 

extern VControl UIFlowWndHome_TimePnaelCtrl;//Panel type 

extern VControl UIFlowWndHome_Status_MovieModeCtrl;//List type 

typedef enum
{
UIFlowWndHome_Status_MovieMode_STRID_VIDEO_MODE,
UIFlowWndHome_Status_MovieMode_MAX
}UIFlowWndHome_Status_MovieMode_Setting;

extern VControl UIFlowWndHome_Status_PhotoModeCtrl;//List type 

typedef enum
{
UIFlowWndHome_Status_PhotoMode_STRID_PHOTO_MODE,
UIFlowWndHome_Status_PhotoMode_MAX
}UIFlowWndHome_Status_PhotoMode_Setting;

extern VControl UIFlowWndHome_Status_PlaybackModeCtrl;//List type 

typedef enum
{
UIFlowWndHome_Status_PlaybackMode_STRID_PLAYBACK_MODE,
UIFlowWndHome_Status_PlaybackMode_MAX
}UIFlowWndHome_Status_PlaybackMode_Setting;

extern VControl UIFlowWndHome_Status_RadarSetCtrl;//List type 

typedef enum
{
UIFlowWndHome_Status_RadarSet_STRID_RADAR_SET,
UIFlowWndHome_Status_RadarSet_MAX
}UIFlowWndHome_Status_RadarSet_Setting;

extern VControl UIFlowWndHome_Status_PhotoSetCtrl;//List type 

typedef enum
{
UIFlowWndHome_Status_PhotoSet_STRID_PHOTO_SET,
UIFlowWndHome_Status_PhotoSet_MAX
}UIFlowWndHome_Status_PhotoSet_Setting;

extern VControl UIFlowWndHome_Status_MovieSetCtrl;//List type 

typedef enum
{
UIFlowWndHome_Status_MovieSet_STRID_VIDEO_SET,
UIFlowWndHome_Status_MovieSet_MAX
}UIFlowWndHome_Status_MovieSet_Setting;

extern VControl UIFlowWndHome_Status_SetupCtrl;//List type 

typedef enum
{
UIFlowWndHome_Status_Setup_STRID_SETUP_SET,
UIFlowWndHome_Status_Setup_MAX
}UIFlowWndHome_Status_Setup_Setting;

extern VControl UIFlowWndHome_Status_ReturnCtrl;//List type 

typedef enum
{
UIFlowWndHome_Status_Return_STRID_RETURN_2,
UIFlowWndHome_Status_Return_MAX
}UIFlowWndHome_Status_Return_Setting;

#endif
