//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDMOVIE_H
#define UIFLOWWNDMOVIE_H

#include "UIFramework.h"

extern VControl UIFlowWndMovieCtrl;//Panel type 

extern VControl UIFlowWndMovie_RecPanelCtrl;//Panel type 

extern VControl UIFlowWndMovie_TXT_RECCtrl;//Static type 

extern VControl UIFlowWndMovie_AudioCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Audio_ICON_VOICE_ON,
UIFlowWndMovie_Audio_ICON_VOICE_OFF,
UIFlowWndMovie_Audio_MAX
}UIFlowWndMovie_Audio_Setting;

extern VControl UIFlowWndMovie_RadarVoiceCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_RadarVoice_ICON_VOICE_ON,
UIFlowWndMovie_RadarVoice_ICON_VOICE_OFF,
UIFlowWndMovie_RadarVoice_MAX
}UIFlowWndMovie_RadarVoice_Setting;

extern VControl UIFlowWndMovie_Radar_ModeCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Radar_Mode_STRID_HIGHWAY_MODE,
UIFlowWndMovie_Radar_Mode_STRID_CITY_MODE,
UIFlowWndMovie_Radar_Mode_MAX
}UIFlowWndMovie_Radar_Mode_Setting;

extern VControl UIFlowWndMovie_Radar_VolCtrl;//Static type 

extern VControl UIFlowWndMovie_Radar_Vol_LvlCtrl;//Static type 

extern VControl UIFlowWndMovie_ResolutionCtrl;//Static type 

extern VControl UIFlowWndMovie_Icon_GPSCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Icon_GPS_ICON_GPS_NS,
UIFlowWndMovie_Icon_GPS_MAX
}UIFlowWndMovie_Icon_GPS_Setting;

extern VControl UIFlowWndMovie_Status_StorageCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_Storage_ICONID_NULL,
UIFlowWndMovie_Status_Storage_ICON_SD_CARD,
UIFlowWndMovie_Status_Storage_ICON_SD_LOCK,
UIFlowWndMovie_Status_Storage_MAX
}UIFlowWndMovie_Status_Storage_Setting;

extern VControl UIFlowWndMovie_Status_batteryCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_battery_ICON_BATTERY_FULL,
UIFlowWndMovie_Status_battery_ICON_BATTERY_MED,
UIFlowWndMovie_Status_battery_ICON_BATTERY_LOW,
UIFlowWndMovie_Status_battery_ICON_BATTERY_EMPTY,
UIFlowWndMovie_Status_battery_ICON_BATTERY_ZERO,
UIFlowWndMovie_Status_battery_ICON_BATTERY_CHARGE,
UIFlowWndMovie_Status_battery_MAX
}UIFlowWndMovie_Status_battery_Setting;

extern VControl UIFlowWndMovie_YMD_StaticCtrl;//Static type 

extern VControl UIFlowWndMovie_HMS_StaticCtrl;//Static type 

extern VControl UIFlowWndMovie_Icon_Radar_SingalLvlCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Icon_Radar_SingalLvl_ICON_RADAR_SINGAL_2,
UIFlowWndMovie_Icon_Radar_SingalLvl_MAX
}UIFlowWndMovie_Icon_Radar_SingalLvl_Setting;

extern VControl UIFlowWndMovie_Icon_Radar_WaringCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Icon_Radar_Waring_ICON_RADAR_HZ_K,
UIFlowWndMovie_Icon_Radar_Waring_MAX
}UIFlowWndMovie_Icon_Radar_Waring_Setting;

extern VControl UIFlowWndMovie_Icon_Speed_limitCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Icon_Speed_limit_ICON_SPEED_LIMIT_60,
UIFlowWndMovie_Icon_Speed_limit_MAX
}UIFlowWndMovie_Icon_Speed_limit_Setting;

extern VControl UIFlowWndMovie_Txt_DistanceCtrl;//Static type 

extern VControl UIFlowWndMovie_Txt_CurSpeedCtrl;//Static type 

extern VControl UIFlowWndMovie_Status_ReturnCtrl;//List type 

typedef enum
{
UIFlowWndMovie_Status_Return_STRID_NULL_,
UIFlowWndMovie_Status_Return_MAX
}UIFlowWndMovie_Status_Return_Setting;

extern VControl UIFlowWndMovie_Status_RECCtrl;//Menu type 

typedef enum
{
UIFlowWndMovie_Status_REC_ICON_MAIN_MENU_MOVIE,
UIFlowWndMovie_Status_REC_MAX
}UIFlowWndMovie_Status_REC_Setting;

extern VControl UIFlowWndMovie_Static_CurSpeedUintCtrl;//Static type 

#endif
