//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPhotoRes.c"
#include "UIDisplay.h"
#include "UIFlowWndPhoto.h"
#include "UIFlowWndHome.h"
#include "ide.h"
#define FD_FRAME_RATE               3//10   //(10frame/30fps) = 333ms = update time

#define THIS_DBGLVL         2 //0=OFF, 1=ERROR, 2=TRACE
///////////////////////////////////////////////////////////////////////////////
#define __MODULE__          UIFlowWndPhoto
#define __DBGLVL__          ((THIS_DBGLVL>=PRJ_DBG_LVL)?THIS_DBGLVL:PRJ_DBG_LVL)
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
//#define __DBGFLT__          "[cap]"
//#define __DBGFLT__          "[fd]"
//#define __DBGFLT__          "[io]"
#include "DebugModule.h"
#include "GxTimer.h"
#include "UIInfo.h"
#include "UIAppPhoto.h"
#include "UIPhotoInfo.h"
#include "UIFlowPhotoFuncs.h"

//---------------------FlowPhotoCtrl Global Variables----------


//-----------------------------------------------------------------------------
// UIFlowWndPhoto User Definitions
//-----------------------------------------------------------------------------
// Photo mode key mask


static UINT32 g_uiSelfTimerID       = NULL_TIMER;
static UINT32 g_uiQviewTimerID      = NULL_TIMER;
static volatile BOOL g_bRedLEDOn    = FALSE;
//---------------------UIFlowWndPhotoCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPhoto)
CTRL_LIST_ITEM(UIFlowWndPhoto_StaticTXT_FreePicC)
CTRL_LIST_ITEM(UIFlowWndPhoto_StatusICN_EVC)
CTRL_LIST_ITEM(UIFlowWndPhoto_StatusICN_ISOC)
CTRL_LIST_ITEM(UIFlowWndPhoto_StaticTXT_SizeC)
CTRL_LIST_ITEM(UIFlowWndPhoto_StatusICN_AntiShakingC)
CTRL_LIST_ITEM(UIFlowWndPhoto_StatusICN_WBC)
CTRL_LIST_ITEM(UIFlowWndPhoto_StatusICN_Quality)
CTRL_LIST_ITEM(UIFlowWndPhoto_StatusICN_Storage)
CTRL_LIST_ITEM(UIFlowWndPhoto_StaticTXT_DZoom)
CTRL_LIST_ITEM(UIFlowWndPhoto_StatusICN_Battery)
CTRL_LIST_ITEM(UIFlowWndPhoto_StaticTXT_SelftimerCnt)
CTRL_LIST_ITEM(UIFlowWndPhoto_StatusICN_ContinueShot)
CTRL_LIST_ITEM(UIFlowWndPhoto_Status_Return)
CTRL_LIST_END

//----------------------UIFlowWndPhotoCtrl Event---------------------------
INT32 UIFlowWndPhoto_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPhoto_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPhoto_OnUpdateInfo(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPhoto_TP(VControl *, UINT32, UINT32 *);

INT32 UIFlowWndPhoto_OnKeyShutter2(VControl *, UINT32, UINT32 *);

INT32 UIFlowWndPhoto_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPhoto_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPhoto_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPhoto_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPhoto_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPhoto_OnTimer(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPhoto)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPhoto_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPhoto_OnClose)
EVENT_ITEM(NVTEVT_UPDATE_INFO,UIFlowWndPhoto_OnUpdateInfo)
EVENT_ITEM(NVTEVT_KEY_TP,UIFlowWndPhoto_TP)

EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIFlowWndPhoto_OnKeyShutter2)

EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIFlowWndPhoto_OnChildClose)
EVENT_ITEM(NVTEVT_STORAGE_INIT,UIFlowWndPhoto_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE,UIFlowWndPhoto_OnStorageChange)
EVENT_ITEM(NVTEVT_BATTERY,UIFlowWndPhoto_OnBattery)
EVENT_ITEM(NVTEVT_BATTERY_LOW,UIFlowWndPhoto_OnBatteryLow)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndPhoto_OnTimer)

EVENT_END

static void UIFlowWndPhoto_OnQVStart(void);



static void UIFlowWndPhoto_OnExeSetImageRation(void)
{
    if (UI_GetData(FL_PHOTO_SIZE)==PHOTO_SIZE_2MHD)
    {
         Ux_SendEvent(&CustomPhotoObjCtrl,NVTEVT_EXE_IMAGE_RATIO,1,IMAGERATIO_16_9);
    } else {
         Ux_SendEvent(&CustomPhotoObjCtrl,NVTEVT_EXE_IMAGE_RATIO,1,IMAGERATIO_4_3);
    }
}



static void UIFlowWndPhoto_InitCfgSetting(void)
{

    Ux_SendEvent(&CustomPhotoObjCtrl,   NVTEVT_EXE_SELFTIMER,   1, SysGetFlag(FL_SELFTIMER));
    Ux_SendEvent(&CustomPhotoObjCtrl,   NVTEVT_EXE_QUALITY,     1,  SysGetFlag(FL_QUALITY));
    Ux_SendEvent(&CustomPhotoObjCtrl,   NVTEVT_EXE_ISO,         1, SysGetFlag(FL_ISO));
    Ux_SendEvent(&CustomPhotoObjCtrl,   NVTEVT_EXE_EV,          1, SysGetFlag(FL_EV));
    Ux_SendEvent(&CustomPhotoObjCtrl,   NVTEVT_EXE_WB,          1, SysGetFlag(FL_WB));
    Ux_SendEvent(&CustomPhotoObjCtrl,   NVTEVT_EXE_COLOR,       1, SysGetFlag(FL_COLOR_EFFECT));
    Ux_SendEvent(&CustomPhotoObjCtrl,   NVTEVT_EXE_SHARPNESS,   1,  SysGetFlag(FL_SHARPNESS));
    Ux_SendEvent(&CustomPhotoObjCtrl,   NVTEVT_EXE_FD,          1,  SysGetFlag(FL_FD));
    Ux_SendEvent(&CustomPhotoObjCtrl,   NVTEVT_EXE_DATE_PRINT,  1,  SysGetFlag(FL_DATE_STAMP));
    Ux_SendEvent(&CustomPhotoObjCtrl,   NVTEVT_EXE_SIZE,        1,  SysGetFlag(FL_PHOTO_SIZE));

    UIFlowWndPhoto_OnExeSetImageRation();

    // set FL_CONTINUE_SHOT to off
    SysSetFlag(FL_CONTINUE_SHOT,CONTINUE_SHOT_OFF);
}

static void FlowPhoto_InitStartupFuncs(void)
{
 UINT32 StartFunc = 0;

    StartFunc |=UIAPP_PHOTO_AE;
    StartFunc |=UIAPP_PHOTO_AWB;

    Ux_SendEvent(&CustomPhotoObjCtrl,NVTEVT_EXE_START_FUNC,2,StartFunc ,UIAPP_PHOTO_NOWAITIDLE);
}

static INT32 UIFlowWndPhoto_OnExeCapture(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiEvtKeyAct = 0;

    if(paramNum > 0)
        uiEvtKeyAct = paramArray[0];

    switch(uiEvtKeyAct)
    {
        case NVTEVT_KEY_PRESS:
        {
            switch (gPhotoData.State)
            {
              case PHOTO_ST_VIEW:
                /* Check if in quick review process */
                if(SysGetFlag(FL_QUICK_REVIEW) != QUICK_REVIEW_0SEC)
                {
                    if(g_uiQviewTimerID != NULL_TIMER)
                    {
                        GxTimer_StopTimer(&g_uiQviewTimerID);
                        //g_bQviewTimerStart = FALSE;

                        // unloce AE/AWB
                        FlowPhoto_InitStartupFuncs();

                        /* Set to preview mode */
                        UI_Show(UI_SHOW_PREVIEW, TRUE);

                        /* close quick view image */
                        UI_Show(UI_SHOW_QUICKVIEW, FALSE);

                        /* Resume key after quick view completed */
                       // Input_SetKeyMask(KEY_PRESS, g_uiMaskKeyPress);
                        Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);

                        /* Update window info */
                        FlowPhoto_UpdateIcons(TRUE);
                        return NVTEVT_CONSUME;
                    }
                }

                /* Check capture prerequisite */
                if(FlowPhoto_IsStorageErr() == TRUE)
                {
                    debug_err(("UIFlowWndPhoto_OnKeyShutter2: Card or memory full!\r\n"));
                    gPhotoData.State= PHOTO_ST_WARNING_MENU;
                    return NVTEVT_CONSUME;
                }
                if (GetBatteryLevel() == BATTERY_EXHAUSTED)
                {
                    debug_err(("UIFlowWndPhoto_OnKeyShutter2: Battery is too low!\r\n"));
                    //return NVTEVT_CONSUME;
                }

                // check free pic number
                if (SysGetFlag(FL_CONTINUE_SHOT) == CONTINUE_SHOT_ON) {
                    if(FlowPhoto_GetFreePicNum() < 2)
                    {
                        UINT32 uiMsg = 0;

                        uiMsg = (UI_GetData(FL_CardStatus) == CARD_REMOVED)? UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD : UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CARD_FULL;
                        gPhotoData.State= PHOTO_ST_WARNING_MENU;
                        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,uiMsg,FLOWWRNMSG_TIMER_2SEC);
                        return NVTEVT_CONSUME;
                    }
                }

                switch (SysGetFlag(FL_SELFTIMER))          // set capture mode by system flag
                {
                case SELFTIMER_2SEC:
                    /* Suspend all keys, except S2 key while selftimer started */
                    //Input_SetKeyMask(KEY_PRESS, FLGKEY_ENTER);
                    FlowPhoto_IconDrawSelftimerTime(&UIFlowWndPhoto_StaticTXT_SelftimerCntCtrl,2);
                    gPhotoData.SelfTimerCount = 20;              // set time counter
                    gPhotoData.State = PHOTO_ST_SELFTIMER;  // set working state to self-timer state
                    //KeyScan_EnableLEDToggle(KEYSCAN_LED_GREEN, TRUE);
                    UISound_Play(DEMOSOUND_SOUND_KEY_TONE);
                    if (g_uiSelfTimerID == NULL_TIMER)
                    {
                        g_uiSelfTimerID = GxTimer_StartTimer(100, NVTEVT_01SEC_TIMER, CONTINUE);
                    }
                    break;
                case SELFTIMER_5SEC:
                    /* Suspend all keys, except S2 key while selftimer started */
                    //Input_SetKeyMask(KEY_PRESS, FLGKEY_ENTER);
                    FlowPhoto_IconDrawSelftimerTime(&UIFlowWndPhoto_StaticTXT_SelftimerCntCtrl,5);
                    gPhotoData.SelfTimerCount = 50;         // set time counter
                    gPhotoData.State = PHOTO_ST_SELFTIMER;  // set working state to self-timer state
                    //KeyScan_EnableLEDToggle(KEYSCAN_LED_GREEN, TRUE);
                    UISound_Play(DEMOSOUND_SOUND_KEY_TONE);
                    if (g_uiSelfTimerID == NULL_TIMER)
                    {
                        g_uiSelfTimerID = GxTimer_StartTimer(100, NVTEVT_01SEC_TIMER, CONTINUE);
                    }
                    break;
                case SELFTIMER_10SEC:
                    /* Suspend all keys, except S2 key while selftimer started */
                    //Input_SetKeyMask(KEY_PRESS, FLGKEY_ENTER);
                    FlowPhoto_IconDrawSelftimerTime(&UIFlowWndPhoto_StaticTXT_SelftimerCntCtrl,10);
                    gPhotoData.SelfTimerCount = 100;        // set time counter
                    gPhotoData.State = PHOTO_ST_SELFTIMER;  // set working state to self-timer state
                    //#NT#2012/8/1#Philex - begin
                    //KeyScan_EnableLEDToggle(KEYSCAN_LED_GREEN, TRUE);
                    UISound_Play(DEMOSOUND_SOUND_KEY_TONE);
                    //#NT#2012/8/1#Philex - begin   
                    if (g_uiSelfTimerID == NULL_TIMER)
                    {
                        g_uiSelfTimerID = GxTimer_StartTimer(100, NVTEVT_01SEC_TIMER, CONTINUE);
                    }
                    break;
                default:
                    /* Suspend all keys before sending capture command */
                    //Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
                    Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);

                    /* Clear the whole OSD screen */
                    UxCtrl_SetAllChildShow(pCtrl,FALSE);

                    gPhotoData.State = PHOTO_ST_CAPTURE;    // enter capture state
                    FlowPhoto_DoCapture();                  // do capture directly
                    break;
                 }
                break;
                case PHOTO_ST_SELFTIMER:
                     gPhotoData.State = PHOTO_ST_VIEW;
                     gPhotoData.SelfTimerCount = 0;
                     //KeyScan_EnableLEDToggle(KEYSCAN_LED_GREEN, FALSE);
                     FlowPhoto_IconHideSelftimer(&UIFlowWndPhoto_StaticTXT_SelftimerCntCtrl);
                     // resume press mask to default
                     //Input_SetKeyMask(KEY_PRESS, g_uiMaskKeyPress);
                    break;
            }
            break;
        }

        case NVTEVT_KEY_RELEASE:
        {
            //Rsvd
            break;
        }

        default:
            debug_err(("UIFlowWndPhoto_OnKeyShutter2: Unknown evt 0x%x\r\n", uiEvtKeyAct));
            break;
    }
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPhoto_OnUpdateInfo(VControl * pCtrl, UINT32 paramNum, UINT32 * paramArray)
{

    switch (pPhotoExeInfo->CallBackEvent)
    {
       case UIAPPPHOTO_CB_QVSTART:
            gPhotoData.State = PHOTO_ST_VIEW;
            UIFlowWndPhoto_OnQVStart();
        break;
       case UIAPPPHOTO_CB_JPGOK:
        break;
       case UIAPPPHOTO_CB_FSTOK:
            /* Update window info */
            FlowPhoto_UpdateIcons(TRUE);
        break;
       case UIAPPPHOTO_CB_CAPTUREEND:
            // unloce AE/AWB
            FlowPhoto_InitStartupFuncs();
        break;
       case UIAPPPHOTO_CB_FDEND:
        //UIFlowWndPhoto_OnFdEnd();
        break;
       case UIAPPPHOTO_CB_SDEND:
      
        break;
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPhoto_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIFlowWndPhoto_InitCfgSetting();
    FlowPhoto_InitStartupFuncs();

    /* Init window key mask variables & set key press/release/continue mask */
    gPhotoData.State = PHOTO_ST_VIEW;
    Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
    gPhotoData.SysTimeCount = 0;
    /* Update window info */
    FlowPhoto_UpdateIcons(TRUE);
    /* set FD/SD feature */
    FlowPhoto_SetFdSdProc(TRUE);


    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPhoto_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPhoto_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndPhoto_OnExeCapture(pCtrl,paramNum,paramArray);
}





INT32 UIFlowWndPhoto_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiSoundMask;

    /* Set key mask to self-original state */
    Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
   
    switch (gPhotoData.State)
    {
      case PHOTO_ST_WARNING_MENU:
            if(paramNum > 0)
            {
                if(paramArray[0] == NVTRET_ENTER_MENU)
                {
                    /* Force to lock FD/SD functions before opening Menu */
                    FlowPhoto_ForceLockFdSd();
                    /* Create Menu window */
                    //gPhotoData.State = PHOTO_ST_MENU;
                    //TM_SetMenu(&gPhotoMenu);
                    //Ux_OpenWindow(&MenuCommonItemCtrl, 0);
                    return NVTEVT_CONSUME;
                }
            }
            gPhotoData.State = PHOTO_ST_VIEW;
        break;

      case PHOTO_ST_MENU:
            // disable shutter2 sound
            uiSoundMask = Input_GetKeySoundMask(KEY_PRESS);
            uiSoundMask &= ~FLGKEY_SHUTTER2;
            Input_SetKeySoundMask(KEY_PRESS, uiSoundMask);

            gPhotoData.State = PHOTO_ST_VIEW;
            // set image ratio here
            UIFlowWndPhoto_OnExeSetImageRation();

            // unloce AE/AWB
            FlowPhoto_InitStartupFuncs();

            /* Set to preview mode */
            UI_Show(UI_SHOW_PREVIEW, TRUE);

            /* close quick view image */
            UI_Show(UI_SHOW_QUICKVIEW, FALSE);

            /* Resume key after normal capture completed */
           // Input_SetKeyMask(KEY_PRESS, g_uiMaskKeyPress);

            /* Set FD/SD functions againg after exiting Menu */
            FlowPhoto_SetFdSdProc(TRUE);
            /* Update window info */
            FlowPhoto_UpdateIcons(TRUE);
        break;
    }

    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPhoto_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPhoto_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPhoto_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 static volatile BOOL bBatteryOn = FALSE;

    UxState_SetData(&UIFlowWndPhoto_StatusICN_BatteryCtrl,STATE_CURITEM,GetBatteryLevel());
    if (KeyScan_IsACIn())
    {
       // bBatteryOn = !bBatteryOn;
       // UxCtrl_SetShow(&UIFlowWndPhoto_StatusICN_BatteryCtrl,bBatteryOn);
       UxCtrl_SetShow(&UIFlowWndPhoto_StatusICN_BatteryCtrl,TRUE);
    } else {
        UxCtrl_SetShow(&UIFlowWndPhoto_StatusICN_BatteryCtrl,TRUE);
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPhoto_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW, FLOWWRNMSG_TIMER_2SEC);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPhoto_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 NVTEVT event;


    if(paramNum > 0)
    {
       event = paramArray[0];
    } else {
       return NVTEVT_CONSUME;
    }
    switch(event)
    {
      case NVTEVT_01SEC_TIMER:
        if (gPhotoData.QuickViewCount !=0)
        {
            gPhotoData.QuickViewCount--;
            if (gPhotoData.QuickViewCount == 0)
            {
                if (g_uiQviewTimerID != NULL_TIMER)
                {
                    GxTimer_StopTimer(&g_uiQviewTimerID);
                }

                /* reset state to PHOTO_ST_VIEW */
                gPhotoData.State = PHOTO_ST_VIEW;

                /* set FD/SD feature */
                FlowPhoto_SetFdSdProc(FALSE);

                /* Set to preview mode */
                UI_Show(UI_SHOW_PREVIEW, TRUE);

                /* close quick view image */
                UI_Show(UI_SHOW_QUICKVIEW, FALSE);

                /* Update window info */
                //FlowPhoto_UpdateIcons(TRUE);

                /* Resume key after normal capture completed */
                //Input_SetKeyMask(KEY_PRESS, g_uiMaskKeyPress);

                Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);

                /* set DirID/FileID */
                {
                 UINT32 uhFilesysDirNum, uhFilesysFileNum;

                    DCF_GetNextID(&uhFilesysDirNum, &uhFilesysFileNum);
                    SysSetFlag(FL_DCF_DIR_ID, uhFilesysDirNum);
                    SysSetFlag(FL_DCF_FILE_ID, uhFilesysFileNum);
                }
            }
        }

        if (gPhotoData.SelfTimerCount != 0)
        {
            gPhotoData.SelfTimerCount--;
            if (gPhotoData.SelfTimerCount == 0)
            {
                if (g_uiSelfTimerID != NULL_TIMER)
                {
                    GxTimer_StopTimer(&g_uiSelfTimerID);
                }

                // stopping LED toggle
                //KeyScan_EnableLEDToggle(KEYSCAN_LED_GREEN, FALSE);
            }
            FlowPhoto_OnTimer01SecIndex();
        }
        break;
    }
    return NVTEVT_CONSUME;
}


static void UIFlowWndPhoto_OnQVStart(void)
{

    /* Set to quick review mode */
    //UI_Show(UI_SHOW_QUICKVIEW, TRUE);
    UI_Show(UI_SHOW_QUICKVIEW, FALSE);
    switch(SysGetFlag(FL_QUICK_REVIEW))
        {
           case QUICK_REVIEW_2SEC:
             gPhotoData.QuickViewCount = 15;
            break;
           case QUICK_REVIEW_5SEC:
             gPhotoData.QuickViewCount = 45;
            break;
           case QUICK_REVIEW_0SEC:
             gPhotoData.QuickViewCount = 1;
            break;
        }
    if (g_uiQviewTimerID == NULL_TIMER)
    {
        /* Resume only S2 key while quick view timer started */
        Input_SetKeyMask(KEY_PRESS, FLGKEY_SHUTTER2);
        g_uiQviewTimerID = GxTimer_StartTimer(100, NVTEVT_01SEC_TIMER, CONTINUE);
    }
}

typedef enum
{
	UIFLOW_PHOTO_TOUCH_KEY_NONE,
	UIFLOW_PHOTO_TOUCH_KEY_SHU,				
	UIFLOW_PHOTO_TOUCH_KEY_HOME,			
	UIFLOW_PHOTO_TOUCH_KEY_MAX	
}UIFLOW_PHOTO_TOUCH_KEY;
static UIFLOW_PHOTO_TOUCH_KEY uiPhotoKeyPressed=UIFLOW_PHOTO_TOUCH_KEY_NONE;



INT32 UIFlowWndPhoto_TP(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
  UINT32 uiEvent;
    UINT32 P1,P2;
    UINT32  uiSoundMask;
  
    if(paramNum>0)
        uiEvent = paramArray[0];	
	
	switch(uiEvent)
	{
		case GESTURE_DOWN2UP://GESTURE_RIGHT2LEFT:
		   
		break;			
		
		case GESTURE_UP2DOWN://GESTURE_LEFT2RIGHT:
		    		
		break;	
 
		case GESTURE_PRESSONLY:
			P1= paramArray[1];
			P2=paramArray[2];  
		    if(TPIsOnRange(&UIFlowWndPhoto_Status_ReturnCtrl,P1,P2)==TRUE)
		    	{
		    	       uiPhotoKeyPressed=UIFLOW_PHOTO_TOUCH_KEY_HOME;
		       	//Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);	
		    	}		
                	
                
		   	
		break;

		case GESTURE_CKICK:
			P1= paramArray[1];
			P2=paramArray[2];  
	            debug_msg("^G movie GESTURE_CKICK\r\n");
		    if(TPIsOnRange(&UIFlowWndPhoto_Status_ReturnCtrl,P1,P2)==TRUE)
		    	{
		    	       //if(uiPhotoKeyPressed==UIFLOW_PHOTO_TOUCH_KEY_HOME)
		    	       {      
					Ux_OpenWindow((VControl *)(&UIFlowWndHomeCtrl), 0);											
		    	       }
								   
		    	}	
            else  //if(TPIsOnRange(&UIFlowWndPhoro_Status_CapCtrl,P1,P2)==TRUE)
		    	{
		    	      //if(uiPhotoKeyPressed==UIFLOW_PHOTO_TOUCH_KEY_SHU)
		    	       {
		    	            Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);
		    	       	//FlowPhoto_DoCapture();
			       	//return UIFlowWndPhoto_OnExeCapture(pCtrl,paramNum,paramArray);//Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);	
		    	       }
		       	
		    	}								
		    uiPhotoKeyPressed=UIFLOW_PHOTO_TOUCH_KEY_NONE;
		
		break;
	}	  
	

	  
	return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPhoto_StaticTXT_FreePicCCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StaticTXT_FreePicC)
EVENT_END

//----------------------UIFlowWndPhoto_StatusICN_EVCCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StatusICN_EVC)
EVENT_END

//----------------------UIFlowWndPhoto_StatusICN_ISOCCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StatusICN_ISOC)
EVENT_END

//----------------------UIFlowWndPhoto_StaticTXT_SizeCCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StaticTXT_SizeC)
EVENT_END

//----------------------UIFlowWndPhoto_StatusICN_AntiShakingCCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StatusICN_AntiShakingC)
EVENT_END

//----------------------UIFlowWndPhoto_StatusICN_WBCCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StatusICN_WBC)
EVENT_END

//----------------------UIFlowWndPhoto_StatusICN_QualityCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StatusICN_Quality)
EVENT_END

//----------------------UIFlowWndPhoto_StatusICN_StorageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StatusICN_Storage)
EVENT_END

//----------------------UIFlowWndPhoto_StaticTXT_DZoomCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StaticTXT_DZoom)
EVENT_END

//----------------------UIFlowWndPhoto_StatusICN_BatteryCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StatusICN_Battery)
EVENT_END

//----------------------UIFlowWndPhoto_StaticTXT_SelftimerCntCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StaticTXT_SelftimerCnt)
EVENT_END

//----------------------UIFlowWndPhoto_StatusICN_ContinueShotCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_StatusICN_ContinueShot)
EVENT_END

//----------------------UIFlowWndPhoto_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPhoto_Status_Return)
EVENT_END

