//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndSetup_datetimeRes.c"
#include "UIFlowWndSetup_datetime.h"

#include "UIFlowWndHome.h"
#include <stdio.h>


#include "MenuCommonItem.h"
//#NT#2010/06/01#Chris Chung -begin
#include "UIFlow.h"
#include "Utility.h"
#include "RTC.h"


#define DATETIME_AMPM_ENABLE    DISABLE

#define DATETIME_MAX_YEAR       2050
#define DATETIME_DEFAULT_YEAR   2012
#define DATETIME_DEFAULT_MONTH     1
#define DATETIME_DEFAULT_DAY       1
#define DATETIME_DEFAULT_HOUR      0
#define DATETIME_DEFAULT_MINUTE    0
#define DATETIME_DEFAULT_SECOND    0

/* (57, 53) is the parent's start (x,y). */
#define DATETIME_START_X        57
#define DATETIME_START_Y        53

#define DATETIME_SHIFT_X        20

typedef enum {
    UI_DATETIME_IDX_Y,
    UI_DATETIME_IDX_M,
    UI_DATETIME_IDX_D,
    UI_DATETIME_IDX_HR,
    UI_DATETIME_IDX_MIN,
    UI_DATETIME_IDX_SEC,
} _UI_DATETIME_IDX_;

static UINT32 g_year=DATETIME_MAX_YEAR,g_month=DATETIME_DEFAULT_MONTH,g_day=DATETIME_DEFAULT_DAY;
static UINT32 g_hour=DATETIME_DEFAULT_HOUR,g_min=DATETIME_DEFAULT_MINUTE,g_second=DATETIME_DEFAULT_SECOND;
static char   itemY_Buf[32] = "0000";
static char   itemM_Buf[32] = "00";
static char   itemD_Buf[32] = "00";
static char   itemHR_Buf[32] = "00";
static char   itemMIN_Buf[32] = "00";
static char   itemSEC_Buf[32] = "00";
static char   itemAMPM_Buf[32] = "AM";
static char   itemSwitch_Buf[32] = "YY";
static char   itemOther0_Buf[32] = "/";
static char   itemOther2_Buf[32] = ":";
static char   itemOther4_Buf[32] = "/MM/DD";

_ALIGNED(4) static const UINT8 DayOfMonth[2][12] =
{
    // Not leap year
    {31,28,31,30,31,30,31,31,30,31,30,31},
    // Leap year
    {31,29,31,30,31,30,31,31,30,31,30,31}
};


//---------------------UIFlowWndSetup_datetimeCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndSetup_datetime)
CTRL_LIST_ITEM(UIFlowWndSetup_datetimeTitle)
CTRL_LIST_ITEM(UIFlowWndSetup_datetimeReturn)
CTRL_LIST_ITEM(UIFlowWndSetup_datetimePanel)
CTRL_LIST_ITEM(UIFlowWndSetup_datetime_Tab)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_YMD_VALUE_Other0)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_YMD_VALUE_Other1)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_YMD_VALUE_Other2)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_YMD_VALUE_Other3)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_Y_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_MON_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_DAY_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_H_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_MIN_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_SEC_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_Y_DOWN)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_MON_DOWN)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_DAY_DOWN)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_H_DOWN)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_MIN_DOWN)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_SEC_DOWN)
CTRL_LIST_ITEM(UIFlowWndSetup_datetime_Format)
CTRL_LIST_END


//----------------------UIFlowWndSetup_datetimeCtrl Event---------------------------
INT32 UIFlowWndSetup_datetime_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndSetup_datetime_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndSetup_datetime)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndSetup_datetime_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndSetup_datetime_OnClose)
EVENT_END
void show_datetime_format(int num)
{
UxCtrl_SetShow(&UIFlowWndSetup_datetime_FormatCtrl,FALSE);
    switch(num)
    {
        case DATE_FORMAT_DMY:
            UxStatic_SetData(&UIFlowWndSetup_datetime_FormatCtrl,STATIC_VALUE,Txt_Pointer("DD/MM/YY"));
            //DATA_FORMAT = "DD/MM/YY";
            
            break;
        case DATE_FORMAT_MDY:
            UxStatic_SetData(&UIFlowWndSetup_datetime_FormatCtrl,STATIC_VALUE,Txt_Pointer("MM/DD/YY"));
            //DATA_FORMAT = "MM/DD/YY";
            break;
        case DATE_FORMAT_YMD:
            UxStatic_SetData(&UIFlowWndSetup_datetime_FormatCtrl,STATIC_VALUE,Txt_Pointer("YY/MM/DD"));
            //DATA_FORMAT = "YY/MM/DD";
            break;
    }
    //SysSetFlag(FL_DATE_FORMAT,num);
    
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_FormatCtrl,TRUE);
}

static void UIMenuWndSetup_datetime_UpdateInfo(void)
{


    if(g_day > DayOfMonth[rtc_isLeapYear(g_year)][g_month-1])
        g_day = DayOfMonth[rtc_isLeapYear(g_year)][g_month-1];

    snprintf(itemY_Buf, 32, "%4ld", g_year);
    snprintf(itemM_Buf, 32, "%02ld", g_month);
    snprintf(itemD_Buf, 32, "%02ld", g_day);

    snprintf(itemHR_Buf, 32, "%02ld", g_hour);
    snprintf(itemMIN_Buf, 32, "%02ld", g_min);
    snprintf(itemSEC_Buf, 32, "%02ld", g_second);

    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_YCtrl, FALSE);
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_MCtrl, FALSE);
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_DCtrl, FALSE);
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_HRCtrl, FALSE);
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_MINCtrl, FALSE);
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_SECCtrl, FALSE);
    
    UxStatic_SetData(&UIFlowWndSetup_datetime_YMD_YCtrl, STATIC_VALUE, Txt_Pointer(itemY_Buf));
    UxStatic_SetData(&UIFlowWndSetup_datetime_YMD_MCtrl, STATIC_VALUE, Txt_Pointer(itemM_Buf));
    UxStatic_SetData(&UIFlowWndSetup_datetime_YMD_DCtrl, STATIC_VALUE, Txt_Pointer(itemD_Buf));
    UxStatic_SetData(&UIFlowWndSetup_datetime_YMD_HRCtrl, STATIC_VALUE, Txt_Pointer(itemHR_Buf));
    UxStatic_SetData(&UIFlowWndSetup_datetime_YMD_MINCtrl, STATIC_VALUE, Txt_Pointer(itemMIN_Buf));
    UxStatic_SetData(&UIFlowWndSetup_datetime_YMD_SECCtrl, STATIC_VALUE, Txt_Pointer(itemSEC_Buf));

    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_YCtrl, TRUE);
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_MCtrl, TRUE);
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_DCtrl, TRUE);
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_HRCtrl, TRUE);
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_MINCtrl, TRUE);
    UxCtrl_SetShow(&UIFlowWndSetup_datetime_YMD_SECCtrl, TRUE);

    
    UxStatic_SetData(&UIMenuWndSetup_datetime_YMD_VALUE_Other0Ctrl, STATIC_VALUE, Txt_Pointer(itemOther0_Buf));
    UxStatic_SetData(&UIMenuWndSetup_datetime_YMD_VALUE_Other1Ctrl, STATIC_VALUE, Txt_Pointer(itemOther0_Buf));
    UxStatic_SetData(&UIMenuWndSetup_datetime_YMD_VALUE_Other2Ctrl, STATIC_VALUE, Txt_Pointer(itemOther2_Buf));
    UxStatic_SetData(&UIMenuWndSetup_datetime_YMD_VALUE_Other3Ctrl, STATIC_VALUE, Txt_Pointer(itemOther2_Buf));


    UxCtrl_SetShow(&UIMenuWndSetup_datetime_Y_UPCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetup_datetime_MON_UPCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetup_datetime_DAY_UPCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetup_datetime_H_UPCtrl, TRUE);

    UxCtrl_SetShow(&UIMenuWndSetup_datetime_MIN_UPCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetup_datetime_SEC_UPCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetup_datetime_Y_DOWNCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetup_datetime_MON_DOWNCtrl, TRUE);

    UxCtrl_SetShow(&UIMenuWndSetup_datetime_DAY_DOWNCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetup_datetime_H_DOWNCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetup_datetime_MIN_DOWNCtrl, TRUE);
    UxCtrl_SetShow(&UIMenuWndSetup_datetime_SEC_DOWNCtrl, TRUE);
    show_datetime_format(SysGetFlag(FL_DATE_FORMAT));
}

//static CHAR    DATA_FORMAT[20] = {0};




INT32 UIFlowWndSetup_datetime_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
      RTC_DATE    Date;
    RTC_TIME    Time;

    Date = rtc_getDate();
    Time = rtc_getTime();
    g_year = Date.s.year;
    g_month = Date.s.month;
    g_day = Date.s.day;
    g_hour = Time.s.hour;
    g_min = Time.s.minute;
    g_second = Time.s.second;

     UxStatic_SetData(&UIFlowWndSetup_datetimeTitleCtrl, STATIC_VALUE, STRID_DATE_TIME);
     
    // UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS, 0);
    UIMenuWndSetup_datetime_UpdateInfo();
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndSetup_datetime_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndSetup_datetimeTitleCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetimeTitle)
EVENT_END

//----------------------UIFlowWndSetup_datetimeReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetimeReturn)
EVENT_END

//---------------------UIFlowWndSetup_datetimePanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndSetup_datetimePanel)
CTRL_LIST_END

//----------------------UIFlowWndSetup_datetimePanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetimePanel)
EVENT_END

//----------------------UIFlowWndSetup_datetime_TabCtrl Event---------------------------
INT32 UIFlowWndSetup_datetime_Tab_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndSetup_datetime_Tab_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndSetup_datetime_Tab_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndSetup_datetime_Tab_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndSetup_datetime_OnTouchPanelKey(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndSetup_datetime_Tab)
EVENT_ITEM(NVTEVT_KEY_UP,UIFlowWndSetup_datetime_Tab_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIFlowWndSetup_datetime_Tab_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIFlowWndSetup_datetime_Tab_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndSetup_datetime_Tab_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_TP,UIFlowWndSetup_datetime_OnTouchPanelKey)

EVENT_END

INT32 UIFlowWndSetup_datetime_OnTouchPanelKey(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiEvent;
    UINT32 P1,P2;
    UINT32  uiSoundMask;
  
    if(paramNum>0)
        uiEvent = paramArray[0];	
	
	switch(uiEvent)
	{
		case GESTURE_DOWN2UP://GESTURE_RIGHT2LEFT:
		   	
		break;			
		
		case GESTURE_UP2DOWN://GESTURE_LEFT2RIGHT:
		   		
		break;	
 
		case GESTURE_PRESSONLY:
					    
		break;

		case GESTURE_CKICK:
			P1= paramArray[1];
			P2=paramArray[2];  


                    if(TPIsOnRange(&UIMenuWndSetup_datetime_Y_UPCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_Y) ;  	
                        if(g_year==DATETIME_MAX_YEAR)
                            g_year = DATETIME_DEFAULT_YEAR;
                        else
                            g_year++;
                    }   				
                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_Y_DOWNCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_Y) ;    
                        if(g_year==DATETIME_DEFAULT_YEAR)
                            g_year = DATETIME_MAX_YEAR;
                        else
                            g_year--;
                    }

                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_MON_UPCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_M) ;  	
                        if(g_month==12)
                            g_month=1;
                        else
                            g_month++;
                    }			
                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_MON_DOWNCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_M) ;  	
                        if(g_month==1)
                            g_month=12;
                        else
                            g_month--;					
                    }	

                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_DAY_UPCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_D) ;  	
                        if(g_day==DayOfMonth[rtc_isLeapYear(g_year)][g_month-1])
                            g_day=1;
                        else
                            g_day++;
                    }	
                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_DAY_DOWNCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_D) ;  	
                        if(g_day==1)
                            g_day=DayOfMonth[rtc_isLeapYear(g_year)][g_month-1];
                        else
                            g_day--;
                    }	

                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_H_UPCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_HR) ;  	
                        if(g_hour==23)
                            g_hour=0;
                        else
                            g_hour++;
                    }	
                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_H_DOWNCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_HR) ;  	
                        if(g_hour==0)
                            g_hour=23;
                        else
                            g_hour--;
                    }	
                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_MIN_UPCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_MIN) ;  	
                        if(g_min==59)
                            g_min=0;
                        else
                            g_min++;
                    }	

                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_MIN_DOWNCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_MIN) ;  	
                        if(g_min==0)
                            g_min=59;
                        else
                            g_min--;
                    }	
                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_SEC_UPCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_SEC) ;  	
                        if(g_second==59)
                            g_second=0;
                        else
                            g_second++;
                    }	
                    else if(TPIsOnRange(&UIMenuWndSetup_datetime_SEC_DOWNCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        //UxTab_SetData(&UIFlowWndSetup_datetime_TabCtrl, TAB_FOCUS,UI_DATETIME_IDX_SEC) ;  	
                        if(g_second==0)
                            g_second=59;
                        else
                            g_second--;
                    }	
                    else if(TPIsOnRange(&UIFlowWndSetup_datetimeReturnCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                        rtc_setDate(g_year, g_month, g_day);
                        rtc_setTime(g_hour, g_min, g_second);
                        rtc_triggerCSET();
                        Ux_CloseWindow(&UIFlowWndSetup_datetimeCtrl,0);
                    }
                    else if(TPIsOnRange(&UIFlowWndSetup_datetime_FormatCtrl,P1,P2)==TRUE)
                    {
                    //UISound_Play(DEMOSOUND_SOUND_KEY_TONE);	
                    debug_msg("^G UIFlowWndSetup_datetime_FormatCtrl \r\n");
                        switch(SysGetFlag(FL_DATE_FORMAT))
                            {
                            case DATE_FORMAT_DMY:
                                SysSetFlag(FL_DATE_FORMAT,DATE_FORMAT_MDY);
                                SysSetFlag(FL_DateFormatIndex,DATE_FORMAT_MDY);
                                break;
                            case DATE_FORMAT_MDY:
                                SysSetFlag(FL_DATE_FORMAT,DATE_FORMAT_YMD);
                                SysSetFlag(FL_DateFormatIndex,DATE_FORMAT_MDY);
                                break;
                            case DATE_FORMAT_YMD:
                                SysSetFlag(FL_DATE_FORMAT,DATE_FORMAT_DMY);
                                SysSetFlag(FL_DateFormatIndex,DATE_FORMAT_DMY);
                                break;
                            }
                        show_datetime_format(SysGetFlag(FL_DATE_FORMAT));
                    }
                    else
                    {
                    
                    }
				
		    
		
		break;
	}	  
	
      UIMenuWndSetup_datetime_UpdateInfo();
	  
	return NVTEVT_CONSUME;
}



INT32 UIFlowWndSetup_datetime_Tab_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndSetup_datetime_Tab_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndSetup_datetime_Tab_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndSetup_datetime_Tab_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndSetup_datetime_YMD_YCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_Y)
EVENT_END

//----------------------UIFlowWndSetup_datetime_YMD_MCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_M)
EVENT_END

//----------------------UIFlowWndSetup_datetime_YMD_DCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_D)
EVENT_END

//----------------------UIFlowWndSetup_datetime_YMD_HRCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_HR)
EVENT_END

//----------------------UIFlowWndSetup_datetime_YMD_MINCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_MIN)
EVENT_END

//----------------------UIFlowWndSetup_datetime_YMD_SECCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_SEC)
EVENT_END

//----------------------UIMenuWndSetup_datetime_YMD_VALUE_Other0Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_YMD_VALUE_Other0)
EVENT_END

//----------------------UIMenuWndSetup_datetime_YMD_VALUE_Other1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_YMD_VALUE_Other1)
EVENT_END

//----------------------UIMenuWndSetup_datetime_YMD_VALUE_Other2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_YMD_VALUE_Other2)
EVENT_END

//----------------------UIMenuWndSetup_datetime_YMD_VALUE_Other3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_YMD_VALUE_Other3)
EVENT_END

//----------------------UIMenuWndSetup_datetime_Y_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_Y_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_MON_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_MON_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_DAY_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_DAY_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_H_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_H_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_MIN_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_MIN_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_SEC_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_SEC_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_Y_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_Y_DOWN)
EVENT_END

//----------------------UIMenuWndSetup_datetime_MON_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_MON_DOWN)
EVENT_END

//----------------------UIMenuWndSetup_datetime_DAY_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_DAY_DOWN)
EVENT_END

//----------------------UIMenuWndSetup_datetime_H_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_H_DOWN)
EVENT_END

//----------------------UIMenuWndSetup_datetime_MIN_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_MIN_DOWN)
EVENT_END

//----------------------UIMenuWndSetup_datetime_SEC_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_SEC_DOWN)
EVENT_END

//----------------------UIFlowWndSetup_datetime_FormatCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_Format)
EVENT_END
