//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDSETUP_DATETIME_H
#define UIFLOWWNDSETUP_DATETIME_H

#include "UIFramework.h"

extern VControl UIFlowWndSetup_datetimeCtrl;//Panel type 

extern VControl UIFlowWndSetup_datetimeTitleCtrl;//Static type 

extern VControl UIFlowWndSetup_datetimeReturnCtrl;//Static type 

extern VControl UIFlowWndSetup_datetimePanelCtrl;//Panel type 

extern VControl UIFlowWndSetup_datetime_TabCtrl;//Tab type 

typedef enum
{
UIFlowWndSetup_datetime_Tab_UIFlowWndSetup_datetime_YMD_Y,
UIFlowWndSetup_datetime_Tab_UIFlowWndSetup_datetime_YMD_M,
UIFlowWndSetup_datetime_Tab_UIFlowWndSetup_datetime_YMD_D,
UIFlowWndSetup_datetime_Tab_UIFlowWndSetup_datetime_YMD_HR,
UIFlowWndSetup_datetime_Tab_UIFlowWndSetup_datetime_YMD_MIN,
UIFlowWndSetup_datetime_Tab_UIFlowWndSetup_datetime_YMD_SEC,
UIFlowWndSetup_datetime_Tab_MAX
}UIFlowWndSetup_datetime_Tab_Setting;

extern VControl UIFlowWndSetup_datetime_YMD_YCtrl;//Static type 

extern VControl UIFlowWndSetup_datetime_YMD_MCtrl;//Static type 

extern VControl UIFlowWndSetup_datetime_YMD_DCtrl;//Static type 

extern VControl UIFlowWndSetup_datetime_YMD_HRCtrl;//Static type 

extern VControl UIFlowWndSetup_datetime_YMD_MINCtrl;//Static type 

extern VControl UIFlowWndSetup_datetime_YMD_SECCtrl;//Static type 


extern VControl UIMenuWndSetup_datetime_YMD_VALUE_Other0Ctrl;//Static type 

extern VControl UIMenuWndSetup_datetime_YMD_VALUE_Other1Ctrl;//Static type 

extern VControl UIMenuWndSetup_datetime_YMD_VALUE_Other2Ctrl;//Static type 

extern VControl UIMenuWndSetup_datetime_YMD_VALUE_Other3Ctrl;//Static type 

extern VControl UIMenuWndSetup_datetime_Y_UPCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_MON_UPCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_DAY_UPCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_H_UPCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_MIN_UPCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_SEC_UPCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_Y_DOWNCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_MON_DOWNCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_DAY_DOWNCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_H_DOWNCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_MIN_DOWNCtrl;//Static type 

extern VControl UIMenuWndSetup_datetime_SEC_DOWNCtrl;//Static type 

extern VControl UIFlowWndSetup_datetime_FormatCtrl;//Static type 
#endif
