//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupFormatConfirmRes.c"
#include "UIMenuWndSetupFormatConfirm.h"
#include "UIMenuWndSetupFormat.h"
#include "MenuCommonItem.h"
//#include "UIFlowWndWaitMoment.h"
#include "UIPlayObj.h"
#include "UIFlow.h"

UINT32 g_u32FormatIndex = 0;
static UINT32 uiMenuSetupFormatConfirmIndex=0;

//---------------------UIMenuWndSetupFormatConfirmCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupFormatConfirm)
CTRL_LIST_ITEM(UIMenuWndSetupFormatConfirm_List_Text)
CTRL_LIST_ITEM(UIMenuWndSetupFormatConfirm_Static_Text)
CTRL_LIST_END

//----------------------UIMenuWndSetupFormatConfirmCtrl Event---------------------------
INT32 UIMenuWndSetupFormatConfirm_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnKeyMode(VControl *, UINT32, UINT32 *);
//INT32 UIMenuWndSetupFormatConfirm_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnTouchKey(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndSetupFormatConfirm)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupFormatConfirm_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupFormatConfirm_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndSetupFormatConfirm_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupFormatConfirm_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupFormatConfirm_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupFormatConfirm_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupFormatConfirm_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_TP,UIMenuWndSetupFormatConfirm_OnTouchKey)

EVENT_END

INT32 UIMenuWndSetupFormatConfirm_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/07/28#Chris Chung -begin
    if(paramNum > 0)
    {
        g_u32FormatIndex = paramArray[0];
    }
    g_u32FormatIndex=1;//always is extern card ,jacky lan 
    UxList_SetData(&UIMenuWndSetupFormatConfirm_List_TextCtrl, LST_CURITM,0);

    //#NT#2009/07/28#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/12#Chris Chung -begin
    if(paramNum > 0)
    {
        if(paramArray[0]==NVTRET_WAITMOMENT && paramArray[1]==NVTRET_FORMAT)
        {
            //Ux_CloseWindow(&UIMenuWndSetupFormatCtrl, 0);
            Ux_CloseWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);				
        }
        else if(paramArray[0]==NVTRET_ENTER_MENU)
        {
            Ux_RedrawAllWind();
        }
    }
    else
    {
        Ux_RedrawAllWind();
    }
    //#NT#2009/08/12#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndSetupFormatCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //Ux_CloseWindow(&MenuCommonItemCtrl,0); // close whole tab menu
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupFormatConfirm_List_TextCtrl Event---------------------------
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupFormatConfirm_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupFormatConfirm_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupFormatConfirm_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupFormatConfirm_List_Text_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupFormatConfirm_List_Text_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(UxList_GetData(pCtrl,LST_CURITM)==UIMenuWndSetupFormatConfirm_List_Text_STRID_OK)
    {
        if(g_u32FormatIndex==0)
        {
            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
            BKG_PostEvent(NVTEVT_BKW_FORMAT_NAND);
        }
        else if(g_u32FormatIndex==1)
        {
            #if (_DUAL_CARD_FUNC_ == ENABLE)
            if ((UI_GetData(FL_CardStatus) == CARD_REMOVED) && (UI_GetData(FL_Card2Status) == CARD_REMOVED))
            #else
            if (UI_GetData(FL_CardStatus) == CARD_REMOVED)
            #endif
            {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_2SEC);
                return NVTEVT_CONSUME;
            }
            else
            {
                if(UIStorageCheck(STORAGE_CHECK_LOCKED, NULL) == TRUE)
                {
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_2SEC);
                    return NVTEVT_CONSUME;
                }
            }

            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
            BKG_PostEvent(NVTEVT_BKW_FORMAT_CARD);
        }
        else
        {
           // Ux_CloseWindow(&UIMenuWndSetupFormatCtrl, 0);
            Ux_CloseWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);				
			
        }
    }
    else
    {
        //Ux_CloseWindow(&UIMenuWndSetupFormatCtrl, 0);
        Ux_CloseWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);				
		
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    // the same behavior as ENTER key!
    return UIMenuWndSetupFormatConfirm_List_Text_OnKeyEnter(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndSetupFormatConfirm_OnTouchKey(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiEvent;
    UINT32 P1,P2;
    UINT32  uiSoundMask;
    UINT32 index;
    if(paramNum>0)
        uiEvent = paramArray[0];	
	
	switch(uiEvent)
	{
		case GESTURE_RIGHT2LEFT:						
		case GESTURE_LEFT2RIGHT:	
		case GESTURE_UP2DOWN:
		case GESTURE_DOWN2UP:
		default:
		break;
		
		case GESTURE_PRESSONLY:
			P1= paramArray[1];
			P2=paramArray[2];  
		    if(TPIsOnRangeList(&UIMenuWndSetupFormatConfirm_List_TextCtrl,P1,P2)==TRUE)
		    	{
    				uiMenuSetupFormatConfirmIndex=TP_PhaseListItem_Index(&UIMenuWndSetupFormatConfirm_List_TextCtrl,P1);
				UxList_SetData(&UIMenuWndSetupFormatConfirm_List_TextCtrl, LST_CURITM,uiMenuSetupFormatConfirmIndex);	
		    	}				
		break;

		case GESTURE_CKICK:	
			P1= paramArray[1];
			P2=paramArray[2];  
            
		    if(TPIsOnRangeList(&UIMenuWndSetupFormatConfirm_List_TextCtrl,P1,P2)==TRUE)
		    	{
                            uiMenuSetupFormatConfirmIndex=TP_PhaseListItem_Index(&UIMenuWndSetupFormatConfirm_List_TextCtrl,P1);
				UxList_SetData(&UIMenuWndSetupFormatConfirm_List_TextCtrl, LST_CURITM,uiMenuSetupFormatConfirmIndex);	
    				index=TP_PhaseListItem_Index(&UIMenuWndSetupFormatConfirm_List_TextCtrl,P1);
				if(uiMenuSetupFormatConfirmIndex==index)
				{				
					    if(uiMenuSetupFormatConfirmIndex==UIMenuWndSetupFormatConfirm_List_Text_STRID_OK)
					    {
					        if(g_u32FormatIndex==0)
					        {
					            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
					            BKG_PostEvent(NVTEVT_BKW_FORMAT_NAND);
					        }
					        else if(g_u32FormatIndex==1)
					        {
					            #if (_DUAL_CARD_FUNC_ == ENABLE)
					            if ((UI_GetData(FL_CardStatus) == CARD_REMOVED) && (UI_GetData(FL_Card2Status) == CARD_REMOVED))
					            #else
					            if (UI_GetData(FL_CardStatus) == CARD_REMOVED)
					            #endif
					            {
					                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_2SEC);
					                return NVTEVT_CONSUME;
					            }
					            else
					            {
					                if(UIStorageCheck(STORAGE_CHECK_LOCKED, NULL) == TRUE)
					                {
					                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_2SEC);
					                    return NVTEVT_CONSUME;
					                }
					            }

					            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
					            BKG_PostEvent(NVTEVT_BKW_FORMAT_CARD);
					        }
					        else
					        {
					             //Ux_CloseWindow(&UIMenuWndSetupFormatCtrl, 0);
        						Ux_CloseWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);												
					        }
					    }
					    else
					    {
					            //Ux_CloseWindow(&UIMenuWndSetupFormatCtrl, 0);
        						Ux_CloseWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);									            
					    }
				}
				else
				{
					            //Ux_CloseWindow(&UIMenuWndSetupFormatCtrl, 0);
        						Ux_CloseWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);									            
				}
		    	}	            
			else
			{
					UxList_SetData(&UIMenuWndSetupFormatConfirm_List_TextCtrl, LST_CURITM,0);
			}
		break;
	}	  	  
	return NVTEVT_CONSUME;
}

//----------------------UIMenuWndSetupFormatConfirm_Static_TextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFormatConfirm_Static_Text)
EVENT_END

