//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDEDOGDEFAULT_H
#define UIMENUWNDEDOGDEFAULT_H

#include "UIFramework.h"

extern VControl UIMenuWndEdogDefaultCtrl;//Panel type 

extern VControl UIMenuWndEdogDefaultSetting_List_TextCtrl;//List type 

typedef enum
{
UIMenuWndEdogDefaultSetting_List_Text_STRID_CANCEL,
UIMenuWndEdogDefaultSetting_List_Text_STRID_OK,
UIMenuWndEdogDefaultSetting_List_Text_MAX
}UIMenuWndEdogDefaultSetting_List_Text_Setting;

extern VControl UIMenuWndEdogDefaultSetting_Static_TextCtrl;//Static type 

extern VControl UIMenuWndEdogDefaultSetting_Static_Text_VersionCtrl;//Static type 

//---------------------UIMenuWndEdogDefaultCtrl User Export---------------------------
#endif
