//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDEDOGVOLUME_H
#define UIMENUWNDEDOGVOLUME_H

#include "UIFramework.h"

extern VControl UIMenuWndEdogVolumeCtrl;//Panel type 

extern VControl MenuWdnEdogVolume_PanelCtrl;//Panel type 

extern VControl MenuWndEdogVolume_1Ctrl;//Static type 

extern VControl MenuWndEdogVolume_2Ctrl;//Static type 

extern VControl MenuWndEdogVolume_3Ctrl;//Static type 

extern VControl MenuWndEdogVolume_4Ctrl;//Static type 

//---------------------UIMenuWndEdogVolumeCtrl User Export---------------------------
#endif
