//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndEdogVolumeRes.c"
#include "UIMenuWndEdogVolume.h"
#include "PrjCfg.h"
#include "UIInfo.h"

//---------------------UIMenuWndEdogVolumeCtrl Debug Definition -----------------------------
#define _UIMENUWNDEDOGVOLUME_ERROR_MSG        1
#define _UIMENUWNDEDOGVOLUME_TRACE_MSG        0

#if (_UIMENUWNDEDOGVOLUME_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndEdogVolumeErrMsg(...)            debug_msg ("^R UIMenuWndEdogVolume: "__VA_ARGS__)
#else
#define UIMenuWndEdogVolumeErrMsg(...)
#endif

#if (_UIMENUWNDEDOGVOLUME_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndEdogVolumeTraceMsg(...)          debug_msg ("^B UIMenuWndEdogVolume: "__VA_ARGS__)
#else
#define UIMenuWndEdogVolumeTraceMsg(...)
#endif

void UIMenuWndEdogVolumeUpdateUI()
{
	switch(SysGetFlag(FL_EDOGVOLUME))
	{
		case EDOG_VOLUME_1:
	    		UxCtrl_SetShow(&MenuWndEdogVolume_1Ctrl, TRUE);  		
	    		UxCtrl_SetShow(&MenuWndEdogVolume_2Ctrl, FALSE);  			
	    		UxCtrl_SetShow(&MenuWndEdogVolume_3Ctrl, FALSE);  			
	    		UxCtrl_SetShow(&MenuWndEdogVolume_4Ctrl, FALSE);  							
		break;
		case EDOG_VOLUME_2:
	    		UxCtrl_SetShow(&MenuWndEdogVolume_1Ctrl, TRUE);  		
	    		UxCtrl_SetShow(&MenuWndEdogVolume_2Ctrl, TRUE);  			
	    		UxCtrl_SetShow(&MenuWndEdogVolume_3Ctrl, FALSE);  			
	    		UxCtrl_SetShow(&MenuWndEdogVolume_4Ctrl, FALSE);  			
		break;
		case EDOG_VOLUME_3:
	    		UxCtrl_SetShow(&MenuWndEdogVolume_1Ctrl, TRUE);  		
	    		UxCtrl_SetShow(&MenuWndEdogVolume_2Ctrl, TRUE);  			
	    		UxCtrl_SetShow(&MenuWndEdogVolume_3Ctrl, TRUE);  			
	    		UxCtrl_SetShow(&MenuWndEdogVolume_4Ctrl, FALSE);  				
		break;
		case EDOG_VOLUME_4:
	    		UxCtrl_SetShow(&MenuWndEdogVolume_1Ctrl, TRUE);  		
	    		UxCtrl_SetShow(&MenuWndEdogVolume_2Ctrl, TRUE);  			
	    		UxCtrl_SetShow(&MenuWndEdogVolume_3Ctrl, TRUE);  			
	    		UxCtrl_SetShow(&MenuWndEdogVolume_4Ctrl, TRUE);  				
		break;			
		default:
	    		UxCtrl_SetShow(&MenuWndEdogVolume_1Ctrl, TRUE);  		
	    		UxCtrl_SetShow(&MenuWndEdogVolume_2Ctrl, FALSE);  			
	    		UxCtrl_SetShow(&MenuWndEdogVolume_3Ctrl, FALSE);  			
	    		UxCtrl_SetShow(&MenuWndEdogVolume_4Ctrl, FALSE);  				
		break;			
	}
}
//---------------------UIMenuWndEdogVolumeCtrl Global Variables -----------------------------

//---------------------UIMenuWndEdogVolumeCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndEdogVolumeCtrl Public API  ----------------------------------

//---------------------UIMenuWndEdogVolumeCtrl Private API  ---------------------------------
//---------------------UIMenuWndEdogVolumeCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndEdogVolume)
CTRL_LIST_ITEM(MenuWdnEdogVolume_Panel)
CTRL_LIST_END

//----------------------UIMenuWndEdogVolumeCtrl Event---------------------------
INT32 UIMenuWndEdogVolume_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogVolume_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogVolume_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogVolume_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogVolume_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogVolume_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndEdogVolume_OnKeyShutter2(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndEdogVolume)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndEdogVolume_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndEdogVolume_OnClose)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndEdogVolume_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndEdogVolume_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndEdogVolume_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndEdogVolume_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndEdogVolume_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndEdogVolume_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndEdogVolumeUpdateUI();
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogVolume_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogVolume_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;
	
    uiKeyAct = paramNum ? paramArray[0] : 0;

    switch (uiKeyAct) 
    {
    	case NVTEVT_KEY_PRESS:
		switch(SysGetFlag(FL_EDOGVOLUME))
		{
			case EDOG_VOLUME_1:
				SysSetFlag(FL_EDOGVOLUME,EDOG_VOLUME_2);
			break;
			case EDOG_VOLUME_2:
				SysSetFlag(FL_EDOGVOLUME,EDOG_VOLUME_3);
			break;
			case EDOG_VOLUME_3:
				SysSetFlag(FL_EDOGVOLUME,EDOG_VOLUME_4);
			break;
			case EDOG_VOLUME_4:
			break;			
			default:
				SysSetFlag(FL_EDOGVOLUME,EDOG_VOLUME_3);
			break;			
		}
		UIMenuWndEdogVolumeUpdateUI();		
   		EdgoRec_PutKeyCommand(MENU_VOLUME,SysGetFlag(FL_EDOGVOLUME));	   			
	break;
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogVolume_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;
	
    uiKeyAct = paramNum ? paramArray[0] : 0;
    switch (uiKeyAct) 
    {
    	case NVTEVT_KEY_PRESS:
		switch(SysGetFlag(FL_EDOGVOLUME))
		{
			case EDOG_VOLUME_1:				
				//SysSetFlag(FL_EDOGVOLUME,EDOG_VOLUME_4);
			break;
			case EDOG_VOLUME_2:
				SysSetFlag(FL_EDOGVOLUME,EDOG_VOLUME_1);
			break;
			case EDOG_VOLUME_3:
				SysSetFlag(FL_EDOGVOLUME,EDOG_VOLUME_2);
			break;
			case EDOG_VOLUME_4:
				SysSetFlag(FL_EDOGVOLUME,EDOG_VOLUME_3);
			break;			
			default:
				SysSetFlag(FL_EDOGVOLUME,EDOG_VOLUME_3);
			break;			
		}
		UIMenuWndEdogVolumeUpdateUI();				
   		EdgoRec_PutKeyCommand(MENU_VOLUME,SysGetFlag(FL_EDOGVOLUME));	   			
	break;
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogVolume_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndEdogVolumeCtrl,0);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogVolume_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndEdogVolumeCtrl,0);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndEdogVolume_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndEdogVolumeCtrl,0);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------MenuWdnEdogVolume_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuWdnEdogVolume_Panel)
CTRL_LIST_ITEM(MenuWndEdogVolume_1)
CTRL_LIST_ITEM(MenuWndEdogVolume_2)
CTRL_LIST_ITEM(MenuWndEdogVolume_3)
CTRL_LIST_ITEM(MenuWndEdogVolume_4)
CTRL_LIST_END

//----------------------MenuWdnEdogVolume_PanelCtrl Event---------------------------
EVENT_BEGIN(MenuWdnEdogVolume_Panel)
EVENT_END

//----------------------MenuWndEdogVolume_1Ctrl Event---------------------------
EVENT_BEGIN(MenuWndEdogVolume_1)
EVENT_END

//----------------------MenuWndEdogVolume_2Ctrl Event---------------------------
EVENT_BEGIN(MenuWndEdogVolume_2)
EVENT_END

//----------------------MenuWndEdogVolume_3Ctrl Event---------------------------
EVENT_BEGIN(MenuWndEdogVolume_3)
EVENT_END

//----------------------MenuWndEdogVolume_4Ctrl Event---------------------------
EVENT_BEGIN(MenuWndEdogVolume_4)
EVENT_END

