//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndSetup_datetimeRes.c"
#include "UIFlowWndSetup_datetime.h"
//---------------------UIFlowWndSetup_datetimeCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndSetup_datetime)
CTRL_LIST_ITEM(UIFlowWndSetup_datetimeTitle)
CTRL_LIST_ITEM(UIFlowWndSetup_datetimeReturn)
CTRL_LIST_ITEM(UIFlowWndSetup_datetimePanel)
CTRL_LIST_ITEM(UIFlowWndSetup_datetime_Tab)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_YMD_VALUE_Other0)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_YMD_VALUE_Other1)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_YMD_VALUE_Other2)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_YMD_VALUE_Other3)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_Y_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_MON_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_DAY_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_H_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_MIN_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_SEC_UP)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_Y_DOWN)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_MON_DOWN)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_DAY_DOWN)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_H_DOWN)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_MIN_DOWN)
CTRL_LIST_ITEM(UIMenuWndSetup_datetime_SEC_DOWN)
CTRL_LIST_ITEM(UIFlowWndSetup_datetime_Format)
CTRL_LIST_END

//----------------------UIFlowWndSetup_datetimeCtrl Event---------------------------
INT32 UIFlowWndSetup_datetime_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndSetup_datetime_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndSetup_datetime)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndSetup_datetime_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndSetup_datetime_OnClose)
EVENT_END

INT32 UIFlowWndSetup_datetime_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndSetup_datetime_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndSetup_datetimeTitleCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetimeTitle)
EVENT_END

//----------------------UIFlowWndSetup_datetimeReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetimeReturn)
EVENT_END

//---------------------UIFlowWndSetup_datetimePanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndSetup_datetimePanel)
CTRL_LIST_END

//----------------------UIFlowWndSetup_datetimePanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetimePanel)
EVENT_END

//----------------------UIFlowWndSetup_datetime_TabCtrl Event---------------------------
INT32 UIFlowWndSetup_datetime_Tab_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndSetup_datetime_Tab_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndSetup_datetime_Tab_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndSetup_datetime_Tab_OnKeyRight(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndSetup_datetime_Tab)
EVENT_ITEM(NVTEVT_KEY_UP,UIFlowWndSetup_datetime_Tab_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIFlowWndSetup_datetime_Tab_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIFlowWndSetup_datetime_Tab_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndSetup_datetime_Tab_OnKeyRight)
EVENT_END

INT32 UIFlowWndSetup_datetime_Tab_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndSetup_datetime_Tab_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndSetup_datetime_Tab_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndSetup_datetime_Tab_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndSetup_datetime_YMD_YCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_Y)
EVENT_END

//----------------------UIFlowWndSetup_datetime_YMD_MCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_M)
EVENT_END

//----------------------UIFlowWndSetup_datetime_YMD_DCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_D)
EVENT_END

//----------------------UIFlowWndSetup_datetime_YMD_HRCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_HR)
EVENT_END

//----------------------UIFlowWndSetup_datetime_YMD_MINCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_MIN)
EVENT_END

//----------------------UIFlowWndSetup_datetime_YMD_SECCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_YMD_SEC)
EVENT_END

//----------------------UIMenuWndSetup_datetime_YMD_VALUE_Other0Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_YMD_VALUE_Other0)
EVENT_END

//----------------------UIMenuWndSetup_datetime_YMD_VALUE_Other1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_YMD_VALUE_Other1)
EVENT_END

//----------------------UIMenuWndSetup_datetime_YMD_VALUE_Other2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_YMD_VALUE_Other2)
EVENT_END

//----------------------UIMenuWndSetup_datetime_YMD_VALUE_Other3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_YMD_VALUE_Other3)
EVENT_END

//----------------------UIMenuWndSetup_datetime_Y_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_Y_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_MON_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_MON_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_DAY_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_DAY_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_H_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_H_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_MIN_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_MIN_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_SEC_UPCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_SEC_UP)
EVENT_END

//----------------------UIMenuWndSetup_datetime_Y_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_Y_DOWN)
EVENT_END

//----------------------UIMenuWndSetup_datetime_MON_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_MON_DOWN)
EVENT_END

//----------------------UIMenuWndSetup_datetime_DAY_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_DAY_DOWN)
EVENT_END

//----------------------UIMenuWndSetup_datetime_H_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_H_DOWN)
EVENT_END

//----------------------UIMenuWndSetup_datetime_MIN_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_MIN_DOWN)
EVENT_END

//----------------------UIMenuWndSetup_datetime_SEC_DOWNCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_datetime_SEC_DOWN)
EVENT_END

//----------------------UIFlowWndSetup_datetime_FormatCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndSetup_datetime_Format)
EVENT_END

