//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupVersionRes.c"
#include "UIMenuWndSetupVersion.h"
//---------------------UIMenuWndSetupVersionCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupVersion)
CTRL_LIST_ITEM(UIMenuSetupVersionText)
CTRL_LIST_ITEM(UIMenuSetupVersionText2)
CTRL_LIST_END

//----------------------UIMenuWndSetupVersionCtrl Event---------------------------
INT32 UIMenuWndSetupVersion_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupVersion)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupVersion_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupVersion_OnClose)
EVENT_END

INT32 UIMenuWndSetupVersion_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuSetupVersionTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText)
EVENT_END

//----------------------UIMenuSetupVersionText2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText2)
EVENT_END

