//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayFileListRes.c"
#include "UIFlowWndPlayFileList.h"
//---------------------UIFlowWndPlayFileListCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileList)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_Video)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_Photo)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_Status_Return)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel1)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel2)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel3)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel4)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel5)
CTRL_LIST_ITEM(UIFlowWndPlayFileListPanel6)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile1)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile2)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile3)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile4)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile5)
CTRL_LIST_ITEM(UIFlowWndPlayFileListFile6)
CTRL_LIST_ITEM(UIFlowWndPlayFilelist_FileNum)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_PrePage)
CTRL_LIST_ITEM(UIFlowWndPlayFileList_NextPage)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListCtrl Event---------------------------
INT32 UIFlowWndPlayFileList_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayFileList_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlayFileList)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPlayFileList_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPlayFileList_OnClose)
EVENT_END

INT32 UIFlowWndPlayFileList_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayFileList_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlayFileList_VideoCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_Video)
EVENT_END

//----------------------UIFlowWndPlayFileList_PhotoCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_Photo)
EVENT_END

//----------------------UIFlowWndPlayFileList_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_Status_Return)
EVENT_END

//---------------------UIFlowWndPlayFileListPanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel1Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel1)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel1)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel2Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel2)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel2)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel3Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel3)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel3Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel3)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel4Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel4)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel4Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel4)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel5Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel5)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel5Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel5)
EVENT_END

//---------------------UIFlowWndPlayFileListPanel6Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayFileListPanel6)
CTRL_LIST_END

//----------------------UIFlowWndPlayFileListPanel6Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListPanel6)
EVENT_END

//----------------------UIFlowWndPlayFileListFile1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile1)
EVENT_END

//----------------------UIFlowWndPlayFileListFile2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile2)
EVENT_END

//----------------------UIFlowWndPlayFileListFile3Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile3)
EVENT_END

//----------------------UIFlowWndPlayFileListFile4Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile4)
EVENT_END

//----------------------UIFlowWndPlayFileListFile5Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile5)
EVENT_END

//----------------------UIFlowWndPlayFileListFile6Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileListFile6)
EVENT_END

//----------------------UIFlowWndPlayFilelist_FileNumCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFilelist_FileNum)
EVENT_END

//----------------------UIFlowWndPlayFileList_PrePageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_PrePage)
EVENT_END

//----------------------UIFlowWndPlayFileList_NextPageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayFileList_NextPage)
EVENT_END

