//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayRes.c"
#include "UIFlowWndPlay.h"
//---------------------UIFlowWndPlayCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay)
CTRL_LIST_ITEM(UIFlowWndPlay_Panel_PlayMovie)
CTRL_LIST_ITEM(UIFlowWndPlay_Panel_PlayPhoto)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_Protect)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Filename)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_MovPlayTime)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Speed)
CTRL_LIST_END

//----------------------UIFlowWndPlayCtrl Event---------------------------
INT32 UIFlowWndPlay_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPlay_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPlay_OnClose)
EVENT_END

INT32 UIFlowWndPlay_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIFlowWndPlay_Panel_PlayMovieCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay_Panel_PlayMovie)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PRE_ONE)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_Backward)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_Play)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_Forward)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_NextOne)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_Return)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PlayPause_BG)
CTRL_LIST_END

//----------------------UIFlowWndPlay_Panel_PlayMovieCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Panel_PlayMovie)
EVENT_END

//----------------------UIFlowWndPlay_Status_PRE_ONECtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PRE_ONE)
EVENT_END

//----------------------UIFlowWndPlay_Status_BackwardCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_Backward)
EVENT_END

//----------------------UIFlowWndPlay_Status_PlayCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_Play)
EVENT_END

//----------------------UIFlowWndPlay_Status_ForwardCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_Forward)
EVENT_END

//----------------------UIFlowWndPlay_Status_NextOneCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_NextOne)
EVENT_END

//----------------------UIFlowWndPlay_Status_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_Return)
EVENT_END

//----------------------UIFlowWndPlay_Status_PlayPause_BGCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PlayPause_BG)
EVENT_END

//---------------------UIFlowWndPlay_Panel_PlayPhotoCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay_Panel_PlayPhoto)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PhotoPRE_ONE)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PhotoZoomout)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PhotoZoomin)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PhotoNextOne)
CTRL_LIST_ITEM(UIFlowWndPlay_Status_PhotoReturn)
CTRL_LIST_END

//----------------------UIFlowWndPlay_Panel_PlayPhotoCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Panel_PlayPhoto)
EVENT_END

//----------------------UIFlowWndPlay_Status_PhotoPRE_ONECtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PhotoPRE_ONE)
EVENT_END

//----------------------UIFlowWndPlay_Status_PhotoZoomoutCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PhotoZoomout)
EVENT_END

//----------------------UIFlowWndPlay_Status_PhotoZoominCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PhotoZoomin)
EVENT_END

//----------------------UIFlowWndPlay_Status_PhotoNextOneCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PhotoNextOne)
EVENT_END

//----------------------UIFlowWndPlay_Status_PhotoReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Status_PhotoReturn)
EVENT_END

//----------------------UIFlowWndPlay_StaticICN_ProtectCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_Protect)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_FilenameCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Filename)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_MovPlayTime)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_SpeedCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Speed)
EVENT_END

