//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAY_H
#define UIFLOWWNDPLAY_H

#include "UIFramework.h"

extern VControl UIFlowWndPlayCtrl;//Panel type 

extern VControl UIFlowWndPlay_Panel_PlayMovieCtrl;//Panel type 

extern VControl UIFlowWndPlay_Status_PRE_ONECtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_PRE_ONE_ICON_PLAYBACK_PREONE,
UIFlowWndPlay_Status_PRE_ONE_MAX
}UIFlowWndPlay_Status_PRE_ONE_Setting;

extern VControl UIFlowWndPlay_Status_BackwardCtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_Backward_ICON_PLAYBACK_BACKWARD,
UIFlowWndPlay_Status_Backward_MAX
}UIFlowWndPlay_Status_Backward_Setting;

extern VControl UIFlowWndPlay_Status_PlayCtrl;//Status type 

typedef enum
{
UIFlowWndPlay_Status_Play_ICON_PLAYBACK_PLAY,
UIFlowWndPlay_Status_Play_ICON_PLAYBACK_PAUSE,
UIFlowWndPlay_Status_Play_MAX
}UIFlowWndPlay_Status_Play_Setting;

extern VControl UIFlowWndPlay_Status_ForwardCtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_Forward_ICON_PLAYBACK_FORWARD,
UIFlowWndPlay_Status_Forward_MAX
}UIFlowWndPlay_Status_Forward_Setting;

extern VControl UIFlowWndPlay_Status_NextOneCtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_NextOne_ICON_PLAYBACK_NEXTONE,
UIFlowWndPlay_Status_NextOne_MAX
}UIFlowWndPlay_Status_NextOne_Setting;

extern VControl UIFlowWndPlay_Status_ReturnCtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_Return_STRID_NULL_,
UIFlowWndPlay_Status_Return_MAX
}UIFlowWndPlay_Status_Return_Setting;

extern VControl UIFlowWndPlay_Status_PlayPause_BGCtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_PlayPause_BG_ICONID_NULL,
UIFlowWndPlay_Status_PlayPause_BG_MAX
}UIFlowWndPlay_Status_PlayPause_BG_Setting;

extern VControl UIFlowWndPlay_Panel_PlayPhotoCtrl;//Panel type 

extern VControl UIFlowWndPlay_Status_PhotoPRE_ONECtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_PhotoPRE_ONE_ICON_PLAYBACK_PREONE,
UIFlowWndPlay_Status_PhotoPRE_ONE_MAX
}UIFlowWndPlay_Status_PhotoPRE_ONE_Setting;

extern VControl UIFlowWndPlay_Status_PhotoZoomoutCtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_PhotoZoomout_ICON_PLAY_PHOTO_ZOOMOUT,
UIFlowWndPlay_Status_PhotoZoomout_MAX
}UIFlowWndPlay_Status_PhotoZoomout_Setting;

extern VControl UIFlowWndPlay_Status_PhotoZoominCtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_PhotoZoomin_ICON_PLAY_PHOTO_ZOOMIN,
UIFlowWndPlay_Status_PhotoZoomin_MAX
}UIFlowWndPlay_Status_PhotoZoomin_Setting;

extern VControl UIFlowWndPlay_Status_PhotoNextOneCtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_PhotoNextOne_ICON_PLAYBACK_NEXTONE,
UIFlowWndPlay_Status_PhotoNextOne_MAX
}UIFlowWndPlay_Status_PhotoNextOne_Setting;

extern VControl UIFlowWndPlay_Status_PhotoReturnCtrl;//List type 

typedef enum
{
UIFlowWndPlay_Status_PhotoReturn_STRID_NULL_,
UIFlowWndPlay_Status_PhotoReturn_MAX
}UIFlowWndPlay_Status_PhotoReturn_Setting;

extern VControl UIFlowWndPlay_StaticICN_ProtectCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_FilenameCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_SpeedCtrl;//Static type 

#endif
