//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAYFILELIST_H
#define UIFLOWWNDPLAYFILELIST_H

#include "UIFramework.h"

extern VControl UIFlowWndPlayFileListCtrl;//Panel type 

extern VControl UIFlowWndPlayFileList_VideoCtrl;//Button type 

extern VControl UIFlowWndPlayFileList_PhotoCtrl;//Button type 

extern VControl UIFlowWndPlayFileList_Status_ReturnCtrl;//List type 

typedef enum
{
UIFlowWndPlayFileList_Status_Return_STRID_NULL_,
UIFlowWndPlayFileList_Status_Return_MAX
}UIFlowWndPlayFileList_Status_Return_Setting;

extern VControl UIFlowWndPlayFileListPanelCtrl;//Panel type 

extern VControl UIFlowWndPlayFileListPanel1Ctrl;//Panel type 

extern VControl UIFlowWndPlayFileListPanel2Ctrl;//Panel type 

extern VControl UIFlowWndPlayFileListPanel3Ctrl;//Panel type 

extern VControl UIFlowWndPlayFileListPanel4Ctrl;//Panel type 

extern VControl UIFlowWndPlayFileListPanel5Ctrl;//Panel type 

extern VControl UIFlowWndPlayFileListPanel6Ctrl;//Panel type 

extern VControl UIFlowWndPlayFileListFile1Ctrl;//Static type 

extern VControl UIFlowWndPlayFileListFile2Ctrl;//Static type 

extern VControl UIFlowWndPlayFileListFile3Ctrl;//Static type 

extern VControl UIFlowWndPlayFileListFile4Ctrl;//Static type 

extern VControl UIFlowWndPlayFileListFile5Ctrl;//Static type 

extern VControl UIFlowWndPlayFileListFile6Ctrl;//Static type 

extern VControl UIFlowWndPlayFilelist_FileNumCtrl;//Static type 

extern VControl UIFlowWndPlayFileList_PrePageCtrl;//Static type 

extern VControl UIFlowWndPlayFileList_NextPageCtrl;//Static type 

#endif
