//This source code is generated by UI Designer Studio.

#ifndef UIMENUSETUPSETTING_H
#define UIMENUSETUPSETTING_H

#include "UIFramework.h"

extern VControl UIMenuSetupSettingCtrl;//Panel type 

extern VControl UIMenuSetupSetting_TXT_TitleCtrl;//Static type 

extern VControl UIMenuSetupSetting_Status_ReturnCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_Return_STRID_RETURN_FORWARD,
UIMenuSetupSetting_Status_Return_MAX
}UIMenuSetupSetting_Status_Return_Setting;

extern VControl UIMenuSetupSetting_Status_DateTimeCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_DateTime_STRID_NULL_,
UIMenuSetupSetting_Status_DateTime_MAX
}UIMenuSetupSetting_Status_DateTime_Setting;

extern VControl UIMenuSetupSetting_Status_AutoPWROffCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_AutoPWROff_STRID_NULL_,
UIMenuSetupSetting_Status_AutoPWROff_MAX
}UIMenuSetupSetting_Status_AutoPWROff_Setting;

extern VControl UIMenuSetupSetting_Status_BeepCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_Beep_STRID_NULL_,
UIMenuSetupSetting_Status_Beep_MAX
}UIMenuSetupSetting_Status_Beep_Setting;

extern VControl UIMenuSetupSetting_Status_LanguageCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_Language_STRID_NULL_,
UIMenuSetupSetting_Status_Language_MAX
}UIMenuSetupSetting_Status_Language_Setting;

extern VControl UIMenuSetupSetting_Status_TVModeCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_TVMode_STRID_NULL_,
UIMenuSetupSetting_Status_TVMode_MAX
}UIMenuSetupSetting_Status_TVMode_Setting;

extern VControl UIMenuSetupSetting_Status_HZCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_HZ_STRID_NULL_,
UIMenuSetupSetting_Status_HZ_MAX
}UIMenuSetupSetting_Status_HZ_Setting;

extern VControl UIMenuSetupSetting_Status_AutoLCDOffCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_AutoLCDOff_STRID_NULL_,
UIMenuSetupSetting_Status_AutoLCDOff_MAX
}UIMenuSetupSetting_Status_AutoLCDOff_Setting;

extern VControl UIMenuSetupSetting_Status_FormatCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_Format_STRID_NULL_,
UIMenuSetupSetting_Status_Format_MAX
}UIMenuSetupSetting_Status_Format_Setting;

extern VControl UIMenuSetupSetting_Status_DefaultCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_Default_STRID_NULL_,
UIMenuSetupSetting_Status_Default_MAX
}UIMenuSetupSetting_Status_Default_Setting;

extern VControl UIMenuSetupSetting_Status_VersionCtrl;//List type 

typedef enum
{
UIMenuSetupSetting_Status_Version_STRID_NULL_,
UIMenuSetupSetting_Status_Version_MAX
}UIMenuSetupSetting_Status_Version_Setting;

#endif
